src/components/VizPanel/VizPanel.tsx
src/core/sceneGraph.ts
src/variables/interpolation/sceneInterpolator.test.ts
src/variables/interpolation/sceneInterpolator.ts

Not sure these optimization checks are
going to be possible given dynamic function like onBuildUrl can return a string that
contains variable expressions.

Variables: Fixes to interpolation, removes optimization checks

---

package.json
src/index.ts

Expose VariableDependencyConfig class

---

jest.config.ts
src/components/VizPanel/VizPanel.tsx
src/components/VizPanel/VizPanelRenderer.tsx
src/variables/interpolation/sceneInterpolator.ts
tsconfig.json
yarn.lock

* Add title
* Use the new status message to display errors
* Apply interpolation
|Dashboards|Scenes|
|-|-|

VizPanel: Adapt the renderer to use PanelChrome new API

---

package.json
src/components/SceneApp/SceneApp.tsx
src/components/SceneApp/utils.ts
src/index.ts
yarn.lock

Based of https://github.com/grafana/grafana/pull/61746/files#diff-6fa0d2e370daf913de925cfebc01da033392fc381d64012a01fab9b046e7a088
TODO:

SceneApp: Components for building scene pages in app plugins

---

src/components/EmbeddedScene.tsx
src/variables/components/VariableValueSelectors.tsx

Before (not really true before as this is with 
After:

Variables: Improve styling and spacing 

---

package.json
src/components/SceneApp/utils.ts
src/components/VizPanel/VizPanel.tsx
src/components/VizPanel/VizPanelRenderer.tsx
src/components/layout/SceneGridRow.tsx
yarn.lock

Adds support for transparent panels, and panels without header (hover header)
Updates the dependencies for grafana/ui and data

VizPanel: Add displayMode and hoverHeader options

---

package.json
src/components/SceneRefreshPicker.test.ts
src/components/SceneRefreshPicker.tsx
src/components/SceneTimePicker.tsx
src/index.ts

Implements SceneRefreshPicker object for picking refresh rate and auto-refreshes.
Closes https://github.com/grafana/grafana/issues/63868

Implement auto-refresh for scene time range

---

package.json

Forgot to bump version when merged #38

Release custom transformations support

---

CHANGELOG.md
lerna.json
package.json
packages/scenes-app/.config/tsconfig.json
packages/scenes-app/package.json
packages/scenes-app/src/components/Routes/Routes.tsx
packages/scenes-app/src/constants.ts
packages/scenes-app/src/pages/Demos/Demos.tsx
packages/scenes-app/src/pages/Demos/getDemos.ts
packages/scenes-app/src/pages/Demos/index.ts
packages/scenes-app/src/pages/Demos/scenes/panelMenu.ts
packages/scenes-app/src/pages/Demos/utils.ts
packages/scenes-app/src/plugin.json
packages/scenes/package.json
packages/scenes/src/components/VizPanel/VizPanel.tsx
packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
packages/scenes/src/index.ts
packages/scenes/tsconfig.json
yarn.lock

VizPanel: Enable panel menus

---

packages/scenes/src/components/VizPanel/VizPanel.tsx
packages/scenes/src/core/sceneGraph.ts
packages/scenes/src/index.ts
packages/scenes/src/variables/interpolation/formatRegistry.ts
packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
packages/scenes/src/variables/interpolation/sceneInterpolator.ts
packages/scenes/src/variables/types.ts
packages/scenes/src/variables/variants/DataSourceVariable.test.ts

* Adds missing props to the object we pass to custom variable formatters

Variables: Missing variable props sent to custom variable formatters

---

yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>0.0.24--canary.91.4481377494.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.0.24--canary.91.4481377494.0
yarn add @grafana/scenes@0.0.24--canary.91.4481377494.0
```
</details>

Auto release test 

---

.github/workflows/node-ci.yml
package.json
packages/scenes-app/package.json
packages/scenes/package.json
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>0.0.25--canary.92.0f65287.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.0.25--canary.92.0f65287.0
yarn add @grafana/scenes@0.0.25--canary.92.0f65287.0
```
</details>

Auto: Another release test 

---

.github/actions/yarn-nm-install/action.yml
.github/workflows/node-ci.yml
CHANGELOG.md

- Yarn: Trying to get caching to work
- Update

Yarn: Caching should work

---

packages/scenes/src/variables/macros/AllVariablesMacro.ts

I am really puzzled why the build on main is green

Fix type import

---

.github/workflows/node-ci.yml
.github/workflows/publish-npm.yml
package.json
packages/scenes-app/package.json
packages/scenes/package.json
yarn.lock

Think it's going to work now 
<details>
<summary>📦 Published PR as canary version: <code>0.0.32--canary.107.15a46eb.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.0.32--canary.107.15a46eb.0
yarn add @grafana/scenes@0.0.32--canary.107.15a46eb.0
```
</details>

Enable auto

---

packages/scenes-app/src/demos/flexLayout.tsx
packages/scenes-app/src/demos/grid.tsx
packages/scenes-app/src/demos/gridWithRow.tsx
packages/scenes-app/src/demos/nestedScene.tsx
packages/scenes-app/src/demos/panelContext.tsx
packages/scenes-app/src/demos/panelMenu.ts
packages/scenes-app/src/demos/panelRepeater.tsx
packages/scenes-app/src/demos/queryEditor.tsx
packages/scenes-app/src/demos/utils.ts
packages/scenes-app/src/demos/variables.tsx
packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx
packages/scenes-app/src/demos/withDrilldown/scenes.tsx

An attempt at sharing more of the "controls" (and time range) between demos

SceneApp: Share defaults between demos

---

packages/scenes-app/src/demos/flexLayout.tsx
packages/scenes-app/src/pages/DemoListPage.tsx
packages/scenes/src/components/EmbeddedScene.tsx
packages/scenes/src/components/SceneApp/SceneAppPage.tsx
packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
packages/scenes/src/core/types.ts
packages/scenes/src/index.ts
packages/scenes/src/services/UrlSyncManager.test.ts
packages/scenes/src/services/UrlSyncManager.ts

This required some big changes as there are many SceneAppPage's activate at the same time when drill-downs are involved

UrlSync: Makes url sync work on SceneAppPage level 

---

packages/scenes/src/querying/SceneQueryRunner.test.ts
packages/scenes/src/querying/SceneQueryRunner.ts

Noticed a missing return statement, and some leftover state from a refactor

SceneQueryRunner: Return after setting empty state

---

docusaurus/docs/scene-layout.md
docusaurus/website/sidebars.js

Adds docs for SceneGridLayout and SceneFlexLayout.

Docs: Layout objects

---

docusaurus/docs/advanced-activation-handlers.md
docusaurus/docs/advanced-custom-scene-objects.md
docusaurus/docs/advanced-data.md
docusaurus/docs/advanced-variables.md
docusaurus/docs/variables.md
docusaurus/docs/visualizations.md
docusaurus/website/sidebars.js

Adds docs for the following topic:
- Variables
- Custom scene objects
- Retrieving data and time range using `sceneGraph`
Adds stubs for the following topics:
- Advanced variables (basically `VariableDependencyConfig`)
- Activation handlers

Docs: Add variables and advanced usage docs

---

.github/workflows/deploy.yml
docusaurus/website/docusaurus.config.js

Updates docusaurus config and adds deploy action (ref https://github.com/grafana/plugin-tools/blob/main/.github/workflows/deploy.yml)

Documentation: Publish to gh-pages

---

.github/workflows/deploy.yml

Publish docs: Use yarn install with caching action

---

docusaurus/website/sidebars.js

Docs: Bring back missing sections

---

packages/scenes-app/src/demos/variables.tsx
packages/scenes/src/core/SceneObjectBase.tsx
packages/scenes/src/core/SceneTimeRange.tsx
packages/scenes/src/core/sceneGraph/getTimeRange.ts
packages/scenes/src/core/sceneGraph/index.ts
packages/scenes/src/core/sceneGraph/sceneGraph.ts
packages/scenes/src/core/sceneGraph/utils.ts
packages/scenes/src/variables/macros/index.ts
packages/scenes/src/variables/macros/timeMacros.test.ts
packages/scenes/src/variables/macros/timeMacros.ts

Closes #195
Adds macros for `$__from' and '$__to'

Macros: Add from and to macro

---

docusaurus/docs/core-concepts.md
docusaurus/docs/getting-started.md

Minor updates to Core ideas/Getting started guides.

Docs: Minor updates

---

docusaurus/docs/core-concepts.md

Just a few small changes to the Core Concepts docs.

Core Concepts: Small docs changes

---

docusaurus/docs/advanced-variables.md

Style/wording/grammar edits for topic `advanced-variables.md`

Docs: Advanced variables section copy edit 

---

packages/scenes/src/variables/variants/query/QueryVariable.tsx

Closes https://github.com/grafana/scenes/issues/212
<details>
<summary>📦 Published PR as canary version: <code>0.12.1--canary.218.5090002639.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.12.1--canary.218.5090002639.0
yarn add @grafana/scenes@0.12.1--canary.218.5090002639.0
```
</details>

QueryVariable: Correct picker for multi-value variable

---

packages/scenes-app/README.md

Fixes https://github.com/grafana/scenes/issues/230
Removes some no longer relevant content.

Demos app Readme update

---

packages/scenes/src/querying/SceneQueryRunner.ts

Not 100% sure this is the right approach, but it seems to work, I think?
Closes #233

SceneQueryRunner: Cancel previous request when starting new one

---

packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts

Fixes 1. decribed in https://github.com/grafana/scenes/issues/263

PanelBuilders: Fix regex matcher for overrides

---

packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx
packages/scenes/src/components/SceneApp/SceneApp.test.tsx
packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
packages/scenes/src/components/SceneApp/types.ts

Adding icon and suffix available in [PageTabs](https://github.com/grafana/grafana/blob/main/public/app/core/components/Page/PageTabs.tsx).

Tabs: Add icon and suffix

---

.github/workflows/node-ci.yml
packages/scenes-app/package.json
packages/scenes/package.json
packages/scenes/src/components/SceneApp/SceneApp.test.tsx
yarn.lock

Bump grafana dependencies

---

.github/workflows/deploy-to-dev-portal-prod.yml

Fixing paths

---

docusaurus/website/README.md
docusaurus/website/docusaurus.config.devportal.js
docusaurus/website/docusaurus.config.devportal.prod.js
docusaurus/website/package.json
docusaurus/website/src/css/custom.css
yarn.lock

This PR adds basic search functionality to the website and a link in the header and footer to return to the dev-portal homepage.
https://github.com/grafana/scenes/assets/73201/eb15cdd7-7214-42ff-8ce2-e674b12f056c
Related: https://github.com/grafana/grafana-developer-portal/issues/9

Website: Add search and links to dev portal home

---

docusaurus/docs/visualizations.md

Closes https://github.com/grafana/scenes/issues/252

Docs: Override matchers

---

README.md
docusaurus/website/src/pages/index.tsx
packages/scenes/README.md

<details>
<summary>📦 Published PR as canary version: <code>1.0.0--canary.323.6086435392.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.0.0--canary.323.6086435392.0
yarn add @grafana/scenes@1.0.0--canary.323.6086435392.0
```
</details>

Scenes 1.0 release prep

---

packages/scenes/src/core/SceneObjectBase.test.ts
packages/scenes/src/core/SceneObjectBase.tsx
packages/scenes/src/core/types.ts

Just an idea that could make SceneObjectRef a bit easier to use and discover

SceneObject: Add getRef for easier SceneObjectRef usage

---

packages/scenes/src/components/VizPanel/VizPanel.test.tsx
packages/scenes/src/components/VizPanel/VizPanel.tsx

Fixes https://github.com/grafana/scenes/issues/336
Was recently added and now notice some panels not migrating correctly.
https://github.com/grafana/grafana/pull/73782

VizPanel: Support async migration handlers

---

packages/scenes/src/core/types.ts
packages/scenes/src/querying/layers/SceneDataLayerControls.tsx

Allow providing `isHidden` state to data layer providers.

Data layer controls: Allow hiding

---

docs/advanced-activation-handlers/index.html
docs/advanced-behaviors/index.html
docs/advanced-custom-datasource/index.html
docs/advanced-custom-scene-objects/index.html
docs/advanced-data/index.html
docs/advanced-time-range-comparison/index.html
docs/advanced-variables/index.html
docs/core-concepts/index.html
docs/getting-started/index.html
docs/scene-app-drilldown/index.html
docs/scene-app-tabs/index.html
docs/scene-app/index.html
docs/scene-layout/index.html
docs/transformations/index.html
docs/variables/index.html
docs/visualizations/index.html
index.html
markdown-page/index.html

Adding redirects to new urls 
Related to https://github.com/grafana/scenes/pull/362

Adding redirects from github.io pages to developer portal

---

packages/scenes/src/components/SceneTimeRangeCompare.tsx
packages/scenes/src/core/SceneTimeRange.tsx
packages/scenes/src/core/SceneTimeZoneOverride.tsx
packages/scenes/src/utils/evaluateTimeRange.ts
packages/scenes/src/utils/parseUrlParam.test.ts
packages/scenes/src/utils/parseUrlParam.ts

<details>
<summary>📦 Published PR as canary version: <code>1.6.0--canary.360.6273406733.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.6.0--canary.360.6273406733.0
yarn add @grafana/scenes@1.6.0--canary.360.6273406733.0
```
</details>

SceneTimeRangeCompare: Enable URL sync

---

packages/scenes-app/src/demos/panelRepeater.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.8.1--canary.369.6313200407.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.8.1--canary.369.6313200407.0
yarn add @grafana/scenes@1.8.1--canary.369.6313200407.0
```
</details>

Demos: Fix panel repeater demo

---

packages/scenes-app/src/demos/filteringData.tsx
packages/scenes-app/src/demos/index.ts

Adds a simple demo showcasing how to implement basic regex filtering of the data from `SceneQueryRunner`.

Demos: Client side data filtering

---

packages/scenes/src/index.ts

<details>
<summary>📦 Published PR as canary version: <code>1.9.1--canary.385.6383655779.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.9.1--canary.385.6383655779.0
yarn add @grafana/scenes@1.9.1--canary.385.6383655779.0
```
</details>

SceneFlexLayout: Export SceneFlexItemLike

---

packages/scenes/src/variables/variants/query/QueryVariable.tsx

Sort should be disabled by default

QueryVariable: Fix sort default value

---

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx

Fixes some events that where published when nothing changed

AdHocFiltersVariable: Fixes issue with unnessary change events

---

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx

Minor refactor and also makes
sure the expr (value) is rendered
in the constructor

AdhocFilterVariable: Render expr (value) in constructor

---

packages/scenes/src/index.ts

Had the need to reference this type in the data trail prototype

Export VizPanelBuilder

---

docusaurus/website/src/css/custom.css

**What this PR does / why we need it**:
Updates the styles for admonitions / alerts so links are more visible.

Website: Update theme for alerts

---

packages/scenes-app/src/pages/DemoListPage.tsx

After the new defaults of the css grid I had to update autoRows here

DemoList: Fixes demo list card height

---

packages/scenes-app/src/demos/variables.tsx
packages/scenes/src/variables/components/VariableValueSelect.tsx

Fixes https://github.com/grafana/scenes/issues/213 
A possible way to fix selecting or removing values without triggering cascading updates or dashboard data queries for every change

Variables: Multi select batch update

---

packages/scenes/src/components/VizPanel/VizPanel.test.tsx
packages/scenes/src/components/VizPanel/VizPanel.tsx

VizPanel: Fixes series visibility toggling

---

packages/scenes/src/variables/components/VariableValueSelect.tsx
packages/scenes/src/variables/variants/MultiValueVariable.ts

* Set's the new option noMultiValueWrap
* Adds new option for max visible values

Variables: No wrapping selects

---

packages/scenes/src/components/VizPanel/VizPanelMenu.tsx

Alt fix to https://github.com/grafana/grafana/pull/78683

VizPanelMenu: Fix auto focus / keyboard navigation issue

---

packages/scenes/src/variables/variants/CustomVariable.test.ts
packages/scenes/src/variables/variants/CustomVariable.tsx

Scenes version of https://github.com/grafana/grafana/pull/78800

CustomVariable: Interpolate query

---

packages/scenes-app/src/components/Routes/Routes.tsx
packages/scenes-app/src/constants.ts
packages/scenes-app/src/monitoring-app/GrafanaMonitoringApp.tsx
packages/scenes-app/src/monitoring-app/SceneRadioToggle.tsx
packages/scenes-app/src/monitoring-app/SceneSearchBox.tsx
packages/scenes-app/src/monitoring-app/scenes.tsx
packages/scenes-app/src/monitoring-app/traffic.tsx
packages/scenes-app/src/monitoring-app/transforms.ts
packages/scenes-app/src/monitoring-app/utils.ts
packages/scenes-app/src/plugin.json

Thinking of cleaning up (removing) the /scenes folder from the main repo. 
Don't want to delete this demo app as it's kind of useful.

Moving the grafana monitoring demo app to scenes-app

---

README.md

Tiny PR just to point to the developer docs.

Update README with developer docs

---

README.md

I made a formatting error in #520 🤦‍♂️

Correct developer docs link in README

---

packages/scenes-app/package.json
packages/scenes/package.json

Revert "Chore: Update peer dependencies"

---

packages/scenes/src/components/VizPanel/VizPanel.test.tsx
packages/scenes/src/components/VizPanel/VizPanel.tsx

Fixes #539
And probably #450 as well.

Fixes issue with exemplar link

---

packages/scenes-app/src/demos/groupByDemo.tsx
packages/scenes/src/index.ts
packages/scenes/src/querying/SceneQueryRunner.test.ts
packages/scenes/src/querying/SceneQueryRunner.ts
packages/scenes/src/variables/components/VariableValueSelect.tsx
packages/scenes/src/variables/groupby/AggregationsSet.tsx
packages/scenes/src/variables/groupby/AggregationsSetVariable.tsx
packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
packages/scenes/src/variables/groupby/GroupByVariable.tsx
packages/scenes/src/variables/groupby/findActiveAggregationsSetByUid.ts
packages/scenes/src/variables/groupby/findActiveGroupByVariablesByUid.ts
packages/scenes/src/variables/variants/MultiValueVariable.ts

Exploration of an alternative approach to https://github.com/grafana/scenes/pull/548. 
This brings aggreagations as a Scene Variable. Seems to be working fine, just had to do minor changes to the multi value variable interface in order allow clearing the value.
Todo:

POC: Group by variable

---

scripts/dev.sh

Change to use `link:` protocol instead of `portal:` to link scenes lib to grafana during local development.
Also declare react as both dep and peerDep, for better yarn resolution.
still wip, as you can see by the dodgy debug stuff in the files :) 
matching grafana PR https://github.com/grafana/grafana/pull/81789

Fix dev script for node_modules

---

packages/scenes/src/index.ts
packages/scenes/src/variables/variants/guards.ts

<details>
<summary>📦 Published PR as canary version: <code>2.6.6--canary.583.7831819278.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.6.6--canary.583.7831819278.0
yarn add @grafana/scenes@2.6.6--canary.583.7831819278.0
```
</details>

GroupBy: Add variable type guard

---

packages/scenes/src/components/VizPanel/VizPanel.test.tsx
packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx

Was a mistake in the unit test and code that made this bug possible :)

VizPanel: Fixes streaming issue

---

packages/scenes/src/core/SceneObjectBase.tsx

Only needs to scan state props part of the state change

SceneObjectBase: Minor optimization to setParent

---

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx

fix: adhoc filter placeholder to "Select value"

---

packages/scenes-app/src/demos/verticalControlsLayoutDemo.tsx
packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx

It's not working for some reason. Some timing issue, the autoFocus + openMenuOnFocus is working for the key select but not the value select 
Update: It is working now.
* Handled by #620

AdHocFilters: Auto focus value when key is selected

---

packages/scenes/src/behaviors/LiveNowTimer.ts
packages/scenes/src/behaviors/index.ts
packages/scenes/src/components/SceneRefreshPicker.tsx
packages/scenes/src/components/VizPanel/VizPanel.tsx
packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx

First pass at migrating https://github.com/grafana/grafana/pull/37769 to scenes.
Not every nuance of the feature has been migrated, but it's a start.

Scenes: Implement "Live now" feature

---

packages/scenes/src/behaviors/LiveNowTimer.ts

Needed to move the `enabled` prop to state for DashboardSettings toggle

LiveNow: Move enabled property to state

---

packages/scenes/src/core/SceneObjectBase.test.ts
packages/scenes/src/core/SceneObjectBase.tsx
packages/scenes/src/core/types.ts
packages/scenes/src/index.ts
packages/scenes/src/variables/components/VariableValueSelectors.tsx

Changes https://github.com/grafana/scenes/pull/679 and makes this new behavior optional & opt-in

SceneObjectBase: useState add options that make the new activation behavior optional

---

packages/scenes/src/core/SceneObjectBase.test.ts
packages/scenes/src/core/SceneObjectBase.tsx

Needed for the RowRepeatBehavior which we remove / add during editing a dashboard

SceneObject: Handle new or removed behaviors

---

packages/scenes-app/src/react-demo/Home.tsx
packages/scenes/src/react-context/index.ts

Fix import issue and renaming issue

---

packages/scenes-app/src/plugin.json

Updated the reference to the plugin.json schema (it was pointing to the old one).

Plugin.json: update schema reference URL in scenes-app

---

packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
packages/scenes/src/components/SceneApp/types.ts

Allowing passthrough of layout prop

SceneAppPage: add PageLayoutType 'layout' prop

---

packages/scenes-react/src/variables/CustomVariable.test.tsx
packages/scenes-react/src/variables/CustomVariable.tsx
packages/scenes-react/src/variables/types.ts

Adds more props and tests to Custom Variable in react-scenes.

Add more props + tests to CustomVariable

---

packages/scenes/src/components/layout/LazyLoader.tsx

Makes use of the memoized `useStyles2` hook and improves names of the used CSS class.

LazyLoader: add use of `useStyles2` and improve name

---

packages/scenes/src/core/SceneTimeRange.test.tsx
packages/scenes/src/core/SceneTimeRange.tsx
packages/scenes/src/querying/SceneDataTransformer.test.ts
packages/scenes/src/querying/SceneQueryRunner.test.ts

Resolves https://github.com/grafana/grafana/issues/90538

Add triggering RefreshEvent on time range refresh

---

packages/scenes-react/src/hooks/useVariableValue.test.tsx
packages/scenes-react/src/hooks/useVariableValue.ts
packages/scenes-react/src/index.ts

Add useVariableValue hook for single value use

ScenesReact: Add useVariableValue for single values

---

packages/scenes/src/core/SceneTimeRange.test.tsx
packages/scenes/src/core/SceneTimeRange.tsx
packages/scenes/src/core/types.ts

SceneTimeRange: Support initialize time range with time and time.window

---

.github/workflows/node-ci.yml

This PR changes the ci workflow and uses a github app to authenticate

Fix pipeline

---

docusaurus/docs/advanced-data.md
packages/scenes-react/src/components/VizPanel.tsx
packages/scenes-react/src/hooks/useDataTransformer.ts
packages/scenes/src/index.ts
packages/scenes/src/querying/DataProviderSharer.ts

Adding and exporting a new utility provider 
alt names
* DataProviderForwarder
* DataProviderProxy

DataProvideSharer: Add and export DataProviderSharer

---

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx

<details>
<summary>📦 Published PR as canary version: <code>5.23.4--canary.958.11745371152.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.23.4--canary.958.11745371152.0
npm install @grafana/scenes@5.23.4--canary.958.11745371152.0
yarn add @grafana/scenes-react@5.23.4--canary.958.11745371152.0
yarn add @grafana/scenes@5.23.4--canary.958.11745371152.0
```
</details>

New filters UI: adds some basic unit tests

---

packages/scenes-app/src/demos/groupByDatasource.tsx
packages/scenes-app/src/demos/groupByStatic.tsx

Changes the queries in the groupBy demos to use an aggregate function

SceneApp: Change queries in groupBy demos

---

docusaurus/docs/visualizations.md

Typo in docusaurus/docs/visualizations.md: optionl -> optional.

Fix typo in visualizations.md

---

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx

<details>
<summary>📦 Published PR as canary version: <code>5.30.0--canary.997.12251815420.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.30.0--canary.997.12251815420.0
npm install @grafana/scenes@5.30.0--canary.997.12251815420.0
yarn add @grafana/scenes-react@5.30.0--canary.997.12251815420.0
yarn add @grafana/scenes@5.30.0--canary.997.12251815420.0
```
</details>

VizPanel: Set selectionId for PanelChrome

---

packages/scenes/src/querying/SceneQueryRunner.test.ts
packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap

Tests for the ScopesBridge impl

SceneQueryRunner: Add tests for scopes

---

packages/scenes/src/core/PanelBuilders/__snapshots__/VizPanelBuilder.test.ts.snap

VizPanelBuilders: Update failing snapshot test

---

packages/scenes/README.md

I've been missing documentation for this for quite a while, so I thought I'd add it. Probably not the best writing, so feel free to come with suggestions for improving.

README: Explain usage of the "release" label

---

packages/scenes/src/variables/VariableDependencyConfig.test.ts

<details>
<summary>📦 Published PR as canary version: <code>6.17.1--canary.1140.15417528383.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.17.1--canary.1140.15417528383.0
npm install @grafana/scenes@6.17.1--canary.1140.15417528383.0
yarn add @grafana/scenes-react@6.17.1--canary.1140.15417528383.0
yarn add @grafana/scenes@6.17.1--canary.1140.15417528383.0
```
</details>

VariableDependencyConfig: Fix test

---

packages/scenes/src/querying/layers/SceneDataLayerBase.ts
packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx

Closes https://github.com/grafana/hyperion-planning/issues/246

Annotations: Add scopes variable dependency
