.github/workflows/publish-npm.yml, .gitignore, .yarnrc.yml, README.md, package.json
This introduces changes that allows using scenes in app plugins:
1. Changes PnP linker to NodeModules - otherwise local plugins cannot resolve dependencies in scenes when the package is linked.
2. Moves required deps from `devDependencies` to `dependencies`.
3. Adds workflow for automatic NPM publishing when package.json version changes
=> Config changes to allow app plugins local development

package.json, src/querying/SceneQueryRunner.ts, src/utils/getDataSource.ts, src/variables/variants/query/QueryVariable.test.tsx, src/variables/variants/query/QueryVariable.tsx
Query variable can now depend on dynamically configured data source. This PR: 
1. Unifies data source retrieval between QueryVariable and SceneQueryRunner
2. Adds interpolation to `datasource` property of QueryVariable
=> SceneQueryRunner: Enable datasource property interpolation 

package.json, src/querying/SceneQueryRunner.test.ts, src/querying/SceneQueryRunner.ts
This PR makes sure the SceneQueryRunner scene object is passed down to `runRequest` function via scoped vars for `template_srv` to interpolate queries when interpolation is handled in the data source implementation.
This can be observed i.e. :
- in http://localhost:3000/scenes/Variables?var-server=AA&var-pod=AAA&var-handler=AAAA&from=now-6h&to=now - legend is now correctly shown.
- in any Prometheus query that uses template vars.
=> SceneQueryRunner: Pass scene object via scoped vars to enable query interpolation

src/variables/sets/SceneVariableSet.test.tsx, src/variables/sets/SceneVariableSet.ts
I somehow thought calling unsubscribe was enough but of course not we also need to clear these other sets in deactivate
=> SceneVariableSet: Fixes issue with deactivation cleanup

package.json, src/components/EmbeddedScene.tsx
This is just a nit to make sure k8s demo works as expected. Will be soon replaced by SceneAppPage.
=> Embedded scene: Allow initialising URL sync for an EmbeddedScene externally

src/variables/sets/SceneVariableSet.test.tsx, src/variables/sets/SceneVariableSet.ts
This tries to solve two major things
* Figure out when we do not need to call validateAndUpdate again after re-activation (when the current value & options are valid)
* Notify the scene of changes when the variable was changed while in-active (Both for other variables, and other scene objects)
=> SceneVariableSet: Improved logic for when to validateAndUpdate variables and notify scene of changes

src/querying/SceneQueryRunner.test.ts, src/querying/SceneQueryRunner.ts
This fixes an issue with queries being issued with maxDataPoints=0, when i.e. queries are issued before the consumer (VizPanel) has set it's final width. This can be observed with scenes that are re-activated and queries are triggered by i.e. variable change.
This PR makes sure than `width=0` updates are ignored if the container width was previously set.
=> SceneQueryRunner: Update container width only when it is greater than 0

src/components/SceneTimePicker.tsx, src/components/VizPanel/VizPanelRenderer.tsx, src/core/SceneObjectBase.test.ts, src/core/SceneObjectBase.tsx, src/core/SceneTimeRange.tsx, src/core/types.ts
* Activate time range objects 
* When VizPanel detects a local time range render it's component in the PanelChrome header 
* Remove onIntervalChanged from SceneTimeRangeLike interface
=> SceneTimeRange: Some time range model changes 

package.json, src/components/SceneApp/SceneApp.test.tsx, yarn.lock
This PR adds test scenarios for common routing patterns (nav to scene page, across tabs and drill-down).
Wish we could test the `preserveUrlKeys` but I think we have to save this for an e2e as it requires the Grafana environment to be properly tested.
=> SceneApp: Add test scenarios for routing

src/core/SceneComponentWrapper.tsx, src/core/SceneObjectBase.tsx, src/variables/sets/SceneVariableSet.test.tsx
Noticed that using SceneApp with scenes with variables and URL sync enabled causes a lot of unnessary re-renders due to re-renders being triggered due to location changes (due to useLocation or useRouteParams),
these re-renders trickles all the way down.
By wrapping all components in React.memo we make
sure the only thing that triggers re-render is
* State update
* New instance
* isEditing change
=> SceneComponentWrapper: Wrap in React.memo to eliminate unnessary re-renders

src/index.ts, src/variables/components/VariableValueInput.tsx, src/variables/variants/TextBoxVariable.tsx
Closes https://github.com/grafana/grafana/issues/63867
Adds support for TextBoxVariable.
Not sure if I handled the url-sync stuff properly, so let me know. 🙂
=> Add support for TextBoxVariable

package.json, src/variables/variants/query/createQueryVariableRunner.ts, src/variables/variants/query/guards.ts
When working on o11y app, @domas and @bfmatei noticed an issue with resolving template variables. The issue is described in https://github.com/grafana/app-o11y-kwl/pull/176#pullrequestreview-1330604155.
After some investigation I found out that there was variables support change in Prometheus data source, introduced in https://github.com/grafana/grafana/pull/63529.
This change surfaced an issue of Scene's `QueryVariable` missing custom variables support implementation. This PR brings this according to how it's implemented in core.
=> QueryVariable: Enable custom variable support

src/variables/interpolation/formatRegistry.test.ts, src/variables/interpolation/formatRegistry.ts
When interpolating variables for json format in [template_srv.ts](https://github.com/grafana/grafana/blob/f8d89eff562dfb7c90b0bb617c639339af30d55c/public/app/features/templating/template_srv.ts#L128), when the variable value is a string, the formatter wraps it in an extra set of unnecessary quotation marks:
I added a check for typeof variable to prevent this.
=> Return value without stringify

src/components/VizPanel/VizPanelRenderer.tsx, src/core/types.ts, src/querying/SceneQueryRunner.test.ts, src/querying/SceneQueryRunner.ts, src/querying/transformations.ts
This is an alternative to https://github.com/grafana/scenes/pull/50 that explores a more compositional approach.
* Separate query runner and transformations so we can re-process transformations without query
* Now SceneQueryRunner is more simple and does not know or care about transformations 
The downside with this is that it's going to be a bit more complex for components that interact with the query runners, they might have to check if is it a normal query runner or a QueryRunnerWithTransforms.
Like updating queries state from panel edit could be more complex, also when adding new transforms it would mean changing and adding this new wrapping query runner. But it does keep the SceneQueryRunner itself simpler.
=> QueryRunner: Alternative more compositional approach to transformations

src/components/VizPanel/VizPanelRenderer.tsx, src/core/types.ts, src/querying/SceneQueryRunner.test.ts, src/querying/SceneQueryRunner.ts, src/querying/transformations.ts
This refactors SceneQueryRunner to provide more flexibility around transformations
* To support getting data without transforms applied (not fully implmented in this PR but would be easy to add)
* To support re-process transformations without triggering query
* Support custom transformation scene objects that transform data based on changing variables, or other scene objects they subscribe to (like search box) 
* To support variable use in transformations (When change only triggers transform), not fully implemented in PR
Example use case is to simplify use cases like:
the point of this is component is to simplify use cases covered in https://github.com/grafana/grafana/blob/f7d37a34b2e110d4edb21100535333456da4e8db/public/app/features/scenes/apps/SceneSearchBox.tsx#L53
=> QueryRunner: Support triggering processing transformations without re-issung query

src/core/SceneObjectBase.tsx, src/core/types.ts
In general nicer to have the simple interfaces as core constraints rather than the full class hierarchy.
=> Types: depend on SubscriptionLike rather than Subscription directly 

src/components/layout/SceneFlexLayout.tsx
This fixes an issue where the layout child could not say "Use height 100%, overflow: auto", they would just extend their parent bounds beyond what it actually had.
For some reason it works with absolute positioned divs (in inner layout children), which is why it works for VizPanelRenderer.
This css fix makes it possible to have layout child components likke this.
```css
<div style={{ height: '100%', width: '100%', overflow: 'auto' }}>
<Stack direction="column">
<div style={{ background: 'red', height: '80px' }}>asd</div>
<div style={{ background: 'red', height: '80px' }}>asd</div>
<div style={{ background: 'red', height: '80px' }}>asd</div>
<div style={{ background: 'red', height: '80px' }}>asd</div>
<div style={{ background: 'red', height: '80px' }}>asd</div>
<div style={{ background: …
```
=> SceneFlexLayout: Fix issue with layout children being able to extrend their bounds

packages/scenes/README.md
npm is not able to pull image due to relative path. So changing this to fixed url.
=> Fix logo in README

CHANGELOG.md, packages/scenes/src/components/SceneByFrameRepeater.tsx, packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneDataTransformer.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/variants/query/QueryVariable.tsx
Alternative to https://github.com/grafana/scenes/pull/66
Closes #66 
* Add prevState to subscribeToState handler
* Simplify subscribeToState argument to be a handler callback to just receive state (and prevState) as separate args
* Reuse the existing event and eventbus instead of having separate subject
=> SceneObject: subscribeToState signature change and implementation change

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Text panels do not have queries (and a few others), but still hit the query runner path.
This lets the panels load rather than sitting with a "no data" message.  We may also want to bypass the query runner entirely, but it seems better to complete normally than to not show anything.
With these change https://github.com/grafana/grafana/pull/64936 now shows more panels OK:
Still failing with "-- Dashboard --" datasource... but this is progress!
=> SceneQueryRunner: support empty/missing queries

CHANGELOG.md, packages/scenes/src/components/NestedScene.tsx, packages/scenes/src/components/SceneByFrameRepeater.tsx, packages/scenes/src/components/layout/SceneFlexLayout.tsx, packages/scenes/src/core/SceneComponentWrapper.tsx, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/sceneGraph.ts, packages/scenes/src/core/types.ts
The editing interfaces and props felt a bit too specific to an unknown future editing mode.
But I still want to support something like that edit mode and support wrapping objects in something like an edit wrapper.
By adding a componentWrapper property to SceneObject I was able to build a similar edit mode with edit wrappers around each of the layout objects.
https://github.com/grafana/grafana/pull/64996
=> SceneObject: Remove interfaces and props for editing

CHANGELOG.md, packages/scenes/src/components/EmbeddedScene.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/services/UrlSyncManager.ts
@domasx2 identified some issues with URL sync when it comes to clearing / restoring state (one of the more complex parts of url sync) 
* Restoring state if the initial state was undefined did not work 
* Coming back to a scene did not remember the initialStates (that is used to restore state when url does not contain the state), this required a change so that we do not new up a new UrlSyncManager every initUrlSync but instead preserve the same instance for as long as that scene exists.
* Also updated the tests to more accurately reflect usage (initUrlSync called, then scene is activated)
=> UrlSyncManager: Improvements and fixes

packages/scenes/src/components/layout/SceneGridRow.tsx, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/services/SceneObjectUrlSyncConfig.ts, packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/services/UrlSyncManager.ts, packages/scenes/src/variables/macros/UrlTimeRangeMacro.ts, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/src/variables/variants/TextBoxVariable.tsx
After the changes in https://github.com/grafana/scenes/pull/96 there is now technically no need for the getUrlState function to pass in state, but it could instead always use current state. The reason for it passing in state was to be able to pass in old state so we could remember the initial state and restore it when url state was removed. 
Burt all of that is no longer needed, so I think it makes sense to simplify this interface and have get just be getUrlState. 
There is a small argument that this could potentially be useful at some point and adding it later could be painful 
The  SceneObjectUrlSyncHandler interface has changed. The function `getUrlState` no longer takes state as parameter. The implementation needs to use the current scene object state instead.
=> UrlSync: Simplify url sync interface

packages/scenes/src/index.ts, packages/scenes/src/variables/interpolation/formatRegistry.test.ts, packages/scenes/src/variables/interpolation/formatRegistry.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.ts, packages/scenes/src/variables/macros/AllVariablesMacro.ts, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, yarn.lock
This PR replaces the `FormatRegistryID` with `VariableFormatID` defined in schema package.
Motivation is to get the formats described consistently so we *can* have the same thing in backend macros
=> Interpolation: FormatRegistryID is now replaced by VariableFormatID from schema package

packages/scenes-app/provisioning/datasources/default.yaml, packages/scenes-app/src/constants.ts, packages/scenes-app/src/pages/Home/Home.tsx
Adding a few warning messages that would have helped me (non-documentation reading 😬 ) figure out why things were not working faster.
=> App: Show errors in the landing page if system is not configured properly

packages/scenes/src/components/NestedScene.tsx, packages/scenes/src/components/SceneByFrameRepeater.tsx, packages/scenes/src/components/SceneCanvasText.tsx, packages/scenes/src/components/SceneReactObject.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/events.ts, packages/scenes/src/core/types.ts, packages/scenes/src/core/utils.ts, packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/variables/VariableDependencyConfig.ts, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
* Simplify types now that the union type SceneObjectState is no longer needed 
* Removes SceneLayoutChildState
=> LayoutTypes: Cleanup old types that are no longer needed 

packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/core/utils.ts, packages/scenes/src/services/UrlSyncManager.ts, packages/scenes/src/variables/sets/SceneVariableSet.ts
* Resolves a circular dependency between utils and SceneObjectBase
* Adds forEachChild to SceneObject interface and SceneObjectBase (this is really useful, both in core lib and in https://github.com/grafana/grafana/pull/65413 to traverse the tree and find object or perform actions)
* Adds _ prefix to some private functions to make things more consistent
=> SceneObject: Add forEachChild to SceneObject interface and SceneObjectBase 

packages/scenes/src/variables/macros/DataValueMacro.test.ts, packages/scenes/src/variables/macros/DataValueMacro.ts
Stupid javascript or stupid developer (me)? Answer: both!
=> ValueMacro: Fixes so __value works for rowIndex 0

packages/scenes-app/src/pages/Demos/getDemos.ts, packages/scenes-app/src/pages/Demos/scenes/variables.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts, packages/scenes/src/variables/variants/TestVariable.tsx, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
Closes https://github.com/grafana/grafana/issues/65832
Closes https://github.com/grafana/scenes/issues/29
First approach to refreshing variables that are dependant on time range.
1. Removed time range dependency from QueryVariable
2. Implemented logic in SceneVariableSet that will add all time range dependant variables to the update queue. My understanding is that doing this and calling `_updateNextBatch` is sufficient to trigger the chain of variable updates.
=> SceneVariableSet: Refresh variables that depend on time range

package.json
After having been frustrated with having to cd into packages/scenes-app and running yarn dev there, and then not being able to run root yarn commands etc. I think
having these root scripts makes sense.
=> PackageJson: Simple scripts to run app dev from root

packages/scenes/src/core/sceneGraph.test.ts, packages/scenes/src/core/sceneGraph.ts
After using the newly merged findObject finction in the behaviors branch I discovered some bugs with it where it would go up and down the same part of the scene treee
=> FindObject: Fixes search logic so that it does not get stuck in infine  loops

packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes/src/components/NestedScene.tsx, packages/scenes/src/components/layout/SceneFlexLayout.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx, packages/scenes/src/core/types.ts
This allows SceneFlexLayout to be used as a child of another SceneFlexLayout, without the need for wrapping it with SceneFlexItem. Tried to make SceneFlexLayout to implement SceneFlexItemLike interface, but it's quite tricky since the primarily because the `body` and `children` differentiation.
=> FlexLayout: Allow SceneFlexLayout to be child of another flex layout

packages/scenes-app/src/demos/dynamicPage.tsx, packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes-app/src/demos/grid.tsx, packages/scenes-app/src/demos/gridWithRow.tsx, packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/nestedScene.tsx, packages/scenes-app/src/demos/panelContext.tsx, packages/scenes-app/src/demos/panelMenu.ts, packages/scenes-app/src/demos/panelRepeater.tsx, packages/scenes-app/src/demos/queryEditor.tsx, packages/scenes-app/src/demos/variables.tsx, packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx, packages/scenes-app/src/demos/withDrilldown/panels.tsx, packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx, packages/scenes/src/components/SceneApp/SceneAppPageView.tsx, packages/scenes/src/components/SceneApp/types.ts
I used a bit of a hack before to connect the demo page it's parent by doing this
```
getPage: (routeMatch, parent: SceneAppPageLike) => {
demo.setState({ getParentPage: () => parent });
``` 
Setting state inside getPage is not allowed as this is called in the React render path (and was a bit hacky either way). So this refactors the demos to be generated inside the getPage instead. To not duplicate the demo title and url I changed the signature a bit so that the demo getPage call get's passed in SceneAppState which already includes the title & url and getParentPage 
* Also adds a cache for drilldown pages 
* Will need to be reworked a bit, have a follow-up PR for this that refactors SceneAppPage a bit to add support for fallback routes
=> SceneApp: Correctly build demo pages with getParentPage 

packages/scenes/src/core/SceneComponentWrapper.tsx
* Wait with rendering scene objects' real component until after activation is completed 
Enables
* Activation logic can now happen before the first rendering of the SceneObject Component 
* Behaviors can run before children are activated (and set isHidden for example to prevent children from activating/rendering)
=> SceneObjectBase: Activate parents before children

docusaurus/docs/visualizations.md, docusaurus/website/sidebars.js, packages/scenes-app/src/demos/customPanelPlugin.tsx, packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/runtimePanelPlugin.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/components/VizPanel/registerRuntimePanelPlugin.ts, packages/scenes/src/index.ts
This PR makes it possible for scene app plugins to include custom visualizations without those visualizations having to be defined as standalone panel plugins. 
This can in a way already be accomplished via a custom SceneObject but requires plugins using PanelChrome directly and there is quire a bit of complexity in using that and setting the correct loading state and props for PanelChrome. 
Only problem with this implementation that I can think of right now
* The id of the runtime registered panel plugin could conflict with other plugins. This is not a problem right now as each scene app plugin get's it's own version of scenes so they get their own version of the runtimePanelPlugin registry. But if we where to switch to federated modules in the future then this could become a problem. …
=> VizPanel: Support runtime registered panel plugins  

packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
* Set padding property on PanelChrome based on plugin.noPadding (stat panel mainly use this)
* Fix the layout demo so that it's more useful, removing some of the properties that set defaults (fill)
=> VizPanel: Support noPadding panel plugins

scripts/demo.sh
Follow up to a previous PR https://github.com/grafana/scenes/pull/162 where there was a missing script step to build the Scenes library.
Adding it now.
=> Scenes app: add script step to build scenes

docusaurus/docs/scene-layout.md, packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/responsiveLayout.tsx, packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx, packages/scenes/src/components/SceneCanvasText.tsx, packages/scenes/src/components/layout/SceneFlexLayout.tsx, packages/scenes/src/index.ts
Just started exploring this, opening a draft so no one else starts on it and get some early feedback.
I noticed that this is actually pretty tricky as all constraints you put change when you change flex direction. Say you have a row of stat panels and the row has a maxHeight of 150px, if we have a responsive rule to change the direction of that row to column then all those panels would be also constrained to 150px. So every responsive rule would also have to change / remove the height (and potentially width constraints).
I am trying to make SceneFlexLayout responsive by default as well, in order for this to not require too much work for every scene. What I think is required is minHeight constraints (either on row or visualization level). …
=> FlexLayout: Responsive breakpoints

packages/scenes-app/src/demos/dynamicPage.tsx, packages/scenes/src/components/SceneApp/SceneAppPageView.tsx, packages/scenes/src/components/SceneApp/types.ts
Why: 
App observability app needs to show multiple images after title. 
I am torn on how best to expose it
* Just use the plain renderTitle that Page/PluginPage expose 
* Use `React.ComponentType<{page: SceneAppPage}>`  component (this way you can define a title component that can be passed the page model).
* Or titleObject, a full scene object handling title rendering.
=> SceneAppPage: Add support for custom title

docusaurus/docs/visualizations.md, packages/scenes-app/src/demos/responsiveLayout.tsx, packages/scenes-app/src/demos/utils.ts, packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx, packages/scenes-app/src/demos/withDrilldown/panels.tsx, packages/scenes-app/src/demos/withDrilldown/scenes.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Want to polish up the Grafana monitoring scene to use for demos during GrafanaCon, so needed actions.
Think this is a pretty straight forward way to expose it.
Allow either react nodes or a scene object.
React node should be useful for links to other places while a scene object
could be more useful if it's a button that changes state on current scene.
=> VizPanel: Support adding header actions to top right corner of PanelChrome 

packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
Noticed duplicate breadcrumbs in the Grafana monitoring app. We did not catch in the scenes-app because it only happens on the first level and if the page has tabs (which our Demos list does not have).
=> SceneAppPage: Fixes issue with duplicate breadcrumbs

docusaurus/docs/core-concepts.md, docusaurus/docs/getting-started.md
Style/wording/grammar edits for topics `getting-started.md` and `core-concepts.md`
Also adds some intro text to avoid stacked headings.
@dprokop I've left a couple questions in the text
=> Docs: Getting started section copy edit

docusaurus/docs/advanced-activation-handlers.md, docusaurus/docs/advanced-custom-scene-objects.md, docusaurus/docs/advanced-data.md
Style/wording/grammar edits for topics `advanced-activation-handlers.md`, `advanced-custom-scene-objects.md`, and `advanced-data.md`.
Also adds some intro text to state what information is in the topic.
=> Docs: Advanced usage section copy edit

docusaurus/docs/scene-app-drilldown.md, docusaurus/docs/scene-app-tabs.md, docusaurus/docs/scene-app.md, docusaurus/website/sidebars.js
- Style/wording/grammar edits for topics `scene-app-drilldown.md`, `scene-app-tabs.md`, and `scene-app.md` based on Scenes glossary.
- Fixed step numbering.
- Updated sidebar heading from **Scene apps** to **Scenes apps** per glossary.
=> Docs: Scenes apps section copy edit

packages/scenes/src/querying/SceneDataTransformer.ts
With https://github.com/grafana/scenes/pull/190 I forgot to handle the standalone `SceneDataTransformer` that doesn't have SQR attached to it. This caused panel not being rendered. This PR resolves data display readiness according to `SceneDataTransformer` data provider.
<details>
<summary>📦 Published PR as canary version: <code>0.8.1--canary.194.5016069301.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.8.1--canary.194.5016069301.0
yarn add @grafana/scenes@0.8.1--canary.194.5016069301.0
```
</details>
=> SceneDataTransformer: Correctly resolve isDataReadyToDisplay

docusaurus/docs/scene-app-drilldown.md, docusaurus/docs/visualizations.md, packages/scenes-app/src/demos/runtimePanelPlugin.tsx, packages/scenes/src/components/SceneApp/SceneAppPageView.tsx, packages/scenes/src/components/SceneApp/utils.ts, packages/scenes/src/index.ts
- Exposes `getLinkUrlWithAppUrlState` under `sceneUtils` object.
- Changes `getLinkUrlWithAppUrlState` not to require `params` as an argument. This now happens under the hood using runtime's `locationService`
- Moves `registerRuntimePanelPlugin` to `sceneUtils`
Ref https://github.com/grafana/scenes/issues/180
<details>
<summary>📦 Published PR as canary version: <code>0.9.0--canary.193.5042913418.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.9.0--canary.193.5042913418.0
yarn add @grafana/scenes@0.9.0--canary.193.5042913418.0
```
</details>
=> Scene utils: Expose helper for building drilldown links

packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/core/sceneGraph/getTimeRange.ts, packages/scenes/src/core/sceneGraph/index.ts, packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/core/sceneGraph/utils.ts, packages/scenes/src/variables/macros/timeMacros.ts
Based on https://github.com/grafana/scenes/pull/197 
Wanted to get rid of duplicate implementation of `getTimeRange` in  https://github.com/grafana/scenes/blob/from-to-macros/packages/scenes/src/variables/macros/timeMacros.ts#L61 but this resulted in a circular dependency.
This PR slightly changes the structure of the `sceneGraph` utils so that we can refactor them in the future if more issues like this appear. Currently, the `getTimeRange` util is extracted to a separate file making it possible to re-use directly in code that uses it (`timeMacros`). 
The `sceneGraph` API remains unchanged.
=> Refactor sceneGraph structure to avoid circular dependencies

packages/scenes-app/src/demos/timeZones.tsx, packages/scenes/src/variables/macros/index.ts, packages/scenes/src/variables/macros/timeMacros.test.ts, packages/scenes/src/variables/macros/timeMacros.ts
Adds `__timezone` macro working with scene time range and timezone override.
Closes https://github.com/grafana/scenes/issues/166
=> Macros: Add __timezone macro

packages/scenes/src/components/SceneApp/SceneAppPageView.tsx, packages/scenes/src/components/SceneApp/types.ts
Closes #170
<details>
<summary>📦 Published PR as canary version: <code>0.10.0--canary.196.5054162429.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.10.0--canary.196.5054162429.0
yarn add @grafana/scenes@0.10.0--canary.196.5054162429.0
```
</details>
=> SceneAppPage: Support react elements in subtitle

packages/scenes/src/components/SceneRefreshPicker.tsx, packages/scenes/src/components/SceneTimePicker.tsx
Seeing scene apps with this:
I think we should default to isOnCanvas true behavior, only core dashboards will have these in the nav toolbar (and not for long), all other use cases should use the canvas style
=> TimeRangePicker: Default to the "isOnCanvas" true look

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Noticed that queries are not re-issued when moving between different tabs / drilldowns after changing the time range
=> SceneQueryRunner: Re-run queries onActivate when time range changed

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Noticed a bug on https://ops.grafana-ops.net/a/grafana-app-observability-app/services/datadog-proxy-gateway/overview?var-prometheus=ops-cortex&var-loki=Loki-Ops&var-tempo=Tempo%20%28tempo-ops%29&from=now-6h&to=now 
where it issues the first request with the default 500 data points, second request it issues using containerWidth. 
containerWidth should only be used for maxDataPoints if maxDataPointsFromWidth is true. 
Not sure what the default behavior should be here. because SceneQueryRunner can be placed anywhere in the tree and it's only when it's on VizPanel and when there is a timeseries graph visualization that using containerWidth for maxDataPoints is actually good I figured it best to make it opt in.
=> SceneQueryRunner: Only use containerWidth when maxDataPointsFromWidth is true

docusaurus/docs/advanced-activation-handlers.md, docusaurus/docs/advanced-data.md, docusaurus/docs/advanced-variables.md, docusaurus/docs/core-concepts.md, docusaurus/docs/getting-started.md, docusaurus/docs/scene-app-drilldown.md, docusaurus/docs/scene-app.md, docusaurus/docs/transformations.md
Reviewing the admonitions in the docs, there doesn't seem to be an underlying pattern for when we use `:::note` vs `:::info`. There should be a clear difference in why we use one admonition type vs another, so I've changed all the admonition types to `:::note` for consistency. 
Also, if this content should ever become part of the main Grafana doc set, this will make the move easier, since we don't use an `:::info` type admonition.
Another option is to make all the admonitions `:::info` style because those are rendered with a blue background rather than white (`:::note` admonitions are rendered in white) and stand out more in the docs. Code snippets are also rendered with a white background.
=> Docs: Unify admonition styles

docusaurus/docs/visualizations.md, lerna.json, packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts, packages/scenes/src/core/PanelBuilders/StandardFieldConfigBuilders.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts, packages/scenes/src/core/PanelBuilders/__snapshots__/VizPanelBuilder.test.ts.snap, packages/scenes/src/core/PanelBuilders/index.ts, packages/scenes/src/core/PanelBuilders/types.ts, packages/scenes/src/index.ts, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, yarn.lock
This PR introduces an API for building VizPanels using core visualizations easily. It supports code support for core panel types for Options and FieldConfig. 
We need to merge https://github.com/grafana/grafana/pull/69678 first before proceeding with this ✅ 
TODO:
<details>
<summary>📦 Published PR as canary version: <code>0.16.0--canary.225.5291385533.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.16.0--canary.225.5291385533.0
yarn add @grafana/scenes@0.16.0--canary.225.5291385533.0
```
</details>
=> PanelBuilders: Typed API for VizPanel creation

lerna.json, packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/queryCancellation.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneDataTransformer.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Not sure this is the right approach (specifically with how I'm getting the closest SceneQueryRunner), but it seems to work.
Part of #207
Will tackle query variable cancellation in another PR
<details>
<summary>📦 Published PR as canary version: <code>0.17.0--canary.220.5309552119.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.17.0--canary.220.5309552119.0
yarn add @grafana/scenes@0.17.0--canary.220.5309552119.0
```
</details>
=> VizPanel: Allow queries to be cancelled

docusaurus/docs/scene-layout.md, packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/split.tsx, packages/scenes-app/src/demos/withDrilldown/scenes.tsx, packages/scenes/src/components/layout/Splitter.tsx, packages/scenes/src/components/layout/split/SplitLayout.ts, packages/scenes/src/components/layout/split/SplitLayoutRenderer.tsx, packages/scenes/src/components/layout/split/Splitter.tsx, packages/scenes/src/index.ts
Adds a SplitLayout scene object.
I wanted to use the opportunity to write an accessible and robust Splitter component (possibly one we can add to grafana-ui). To this end it supports keyboard controls, shortcuts, aria values, and maintains proportions if a screen is resized. Min/max dimensions can also be set on splitter panes.
I think there's still room for refactoring and improvement, but it's a start.
Solves #176
=> SplitLayout: Add Splitter and SplitLayout

packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Missed this for `PanelBuilders`.
<details>
<summary>📦 Published PR as canary version: <code>0.17.1--canary.235.5323872416.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.17.1--canary.235.5323872416.0
yarn add @grafana/scenes@0.17.1--canary.235.5323872416.0
```
</details>
=> PanelBuilders: Add method for setting behaviors

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
- SceneGridRow: Fix url sync issues that collapses rows
- correct fix
Noticied that when loading dashboards some rows where collapsed when loaded in scenes runtime
=> SceneGridRow: Fix rows auto collapsing on load due to url sync

packages/scenes-app/src/demos/lazyLoad.tsx, packages/scenes/src/components/layout/grid/LazyLoader.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
When testing core dashboards loaded in scenes runtime I noticed that every panel grid resize change caused big flickering due to all panels unmounting and re-mounting. 
* Root cause was a new component instance LazyLoader was created on every render (when isLazy was false)
* But to fix I ended up refactoring the LazyLoader so to avoid the unnecessary wrapping div (it just needed forwardRef)
* Also fixed the lazy demo which had two issues:
** Lazy was not enabled!! :) 
** Was just not assigning any query on every panel so was just using same data  (this likely introduced in recent refactor to use PanelBuilders)
=> SceneGridLayout: Fixes issues with unmount on every re-render

packages/scenes-app/src/demos/grid.tsx, packages/scenes-app/src/demos/gridWithRow.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Just think it makes more intuitive sense to default this to undefined (false)
=> GridLayout: Default isDraggable to false (unset)

packages/scenes/src/components/layout/grid/types.ts, packages/scenes/src/core/types.ts
* Makes the isDraggable and isResizable optional 
* Makes StatelessBehavior generic so you can define one with a typed scene object parametere
=> SceneGridItem: Makes isDraggable and isResizable optional 

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes #250 
When implementing `SceneQueryRunner` we missed `rangeRaw` on `DataQueryRequest`. This property is used by some of the Grafana data sources, i.e. Influx.
<details>
<summary>📦 Published PR as canary version: <code>0.19.0--canary.253.5517537976.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.19.0--canary.253.5517537976.0
yarn add @grafana/scenes@0.19.0--canary.253.5517537976.0
```
</details>
=> SceneQueryRunner: Provide rangeRaw in request

packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts
Closes #263
When implementing `FieldConfigOverridesBuilder` we exposed an API that's a superset to what's possible in overrides configuration when configuring by-value overrides. 
This PR simplifies the API of `matchFieldsByValue` to only allow relevant options configuration.
<details>
<summary>📦 Published PR as canary version: <code>0.21.0--canary.267.5584998646.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.21.0--canary.267.5584998646.0
yarn add @grafana/scenes@0.21.0--canary.267.5584998646.0
```
</details>
=> FieldConfigOverridesBuilder: Simplify matchFieldsByValue API

packages/scenes-app/package.json, packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/package.json, packages/scenes/src/components/NestedScene.tsx, yarn.lock
With https://github.com/grafana/grafana/pull/70999 merged in grafana core, we have observed an issue with the integration test in https://github.com/grafana/grafana-plugin-examples: https://github.com/grafana/grafana-plugin-examples/actions/runs/5574823448/jobs/10206287399
Not sure why, but the type change there in grafana/schema surfaced an issue with the scenes dependency on grafana/experimental. Experimental has a fixed dependency on ^9.5.2 grafana packages, and apparently this dependency is being resolved as source of schema types for scenes API.
This PR:
- Removes dependency on grafana/experimental - we should not use it for production anyways.
- Marks data/ui/runtime/schema dependencies as peer deps, to indicate version requirements for consumers.
<details>
<summary>📦 Published PR …
=> Mark grafana dependencies as peerDependencies

.github/workflows/deploy-to-dev-portal-dev.yml, docusaurus/website/docusaurus.config.devportal.js
This PR:
- Adds a github action that deploys dataplane docusaurus content into dev portal dev bucket, triggered manually
- Adds a docusaurus config necessary to remove the landing page so it can work from a subdirectory
We will simplify the docusaurus configs later once production deployment is in place
=> Adding developer portal dev workflow and config

packages/scenes/src/variables/components/VariableValueSelectors.tsx
Closes https://github.com/grafana/scenes/issues/269
Nit to make sure labels are not wrapped.
=> VariableValueSelectors: Don't wrap labels

packages/scenes-app/src/demos/flexLayout.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
I've noticed a runtime error appearing when there is plugin not found error comming from panel plugin import. That's because [an error thrown from `importPanelPlugin` is not wrapped in a promise](https://github.com/grafana/grafana/blob/dash-loaders-lib-panel/public/app/features/plugins/importPanelPlugin.ts#L20), hence we cannot rely on `Promise.catch` in VizPanel.
=> VizPanel: Handle plugin not found scenario correctly

packages/scenes/src/core/SceneObjectBase.tsx
I think something like this is good to have as I found some bugs in scene apps related to reusing scene instances in multiple scenes.
=> SceneObject: Warn if parent is already set to another SceneObject

packages/scenes/src/core/sceneGraph/utils.ts, packages/scenes/src/index.ts
Have a scenario where I want to only clone the state of a scene object, and not it's containing scene object instance.
This is for the discard mechanic found in https://github.com/grafana/grafana/pull/73873, If I do a full clone and then try to reuse that state with another
instance I hit my setParent warning of changing scene parent.
DashboardScene want's to copy it's current state so it can revert back to it, so it wants to clone it's state (but not itself)
=> sceneUtils: cloneSceneObjectState

docusaurus/docs/core-concepts.md, packages/scenes/src/core/SceneObjectRef.test.ts, packages/scenes/src/core/SceneObjectRef.ts, packages/scenes/src/core/sceneGraph/utils.ts, packages/scenes/src/index.ts
Can't figure out how to make this be clonable (without making clone a lot more complicated), and even then there is no guarantee it will work as the reference could be to a scene object in a different scene graph tree.  
But not sure if this SceneObjectRef is any better than simple having a function in state that returns the instance alla
```ts
getDashboard: () => dashboard,
```
<details>
<summary>📦 Published PR as canary version: <code>0.27.1--canary.304.6034526594.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.27.1--canary.304.6034526594.0
yarn add @grafana/scenes@0.27.1--canary.304.6034526594.0
```
</details>
=> SceneObjectRef: Provide a way to have references to other scene objects without impacting parent 

packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
This was reverted in main repo as well as it caused issues, seeing another issue with the time picker showing under panel.
<details>
<summary>📦 Published PR as canary version: <code>0.28.1--canary.308.6035159966.0</code></summary>
<br />
```bash
npm install @grafana/scenes@0.28.1--canary.308.6035159966.0
yarn add @grafana/scenes@0.28.1--canary.308.6035159966.0
```
</details>
=> SceneGridLayout: Remove z-index

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts
Hit this limitation when trying to render a VizPanel in panel edit (outside any layout). 
I don't think we should require VizPanel to always be placed inside a layout
=> VizPanel: Allow panels to rendered without layout parent

packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneApp.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx, packages/scenes/src/components/SceneApp/types.ts, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Trying to simplify (and optimize) https://github.com/grafana/scenes/pull/309 a bit by 
* Skipping having to walk the full scene graph and progressively setting & resetting props (to make deeper props override) 
* Skip providing the enricher via SceneApp state (I don't think this is needed right now). For scene app plugin just setting the app name should be enough. We do not have any other prop they can set. And when we do I think we should have some built-in mechanism to set panel or query tracking name directly on SQR or VizPanel. 
To skip the direct instanceof SceneAppPage and check getParentPage I do that instead in SceneAppPage by implementing the enrichDataRequest method. 
Closes https://github.com/grafana/scenes/issues/298
=> DataQueryRequest enricher

packages/scenes/src/utils/getDataSource.ts, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
The datasource reference can be null (for instance default).
=> QueryVariable: Support null ds

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Fixe a bug with all MultiValueVariables with isMulti true and the initial/default value is not an array.
This causes the UrlSyncManager to only pass the first value from the URL to updateFromUrl. So if you have multiple
values selected and do a full page reload only the first item would be set after url sync.
This change fixes this bug by making sure we always return an array in getUrlState.
=> MultiValueVariable: Fix url sync for isMulti when default value is not an array

packages/scenes-app/src/demos/grid.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Left over state from before we introduced layout item wrappers
=> VizPanel: Remove left-over isDraggable/isResizable state

packages/scenes/src/index.ts, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts, packages/scenes/src/variables/types.ts, packages/scenes/src/variables/variants/LocalValueVariable.ts
This is to block query execution for repeating panels where the variable is refreshed on time range change. 
- LocalValueVariable: Special variable value to better support repeating panels
- Update comment
=> Variables: New LocalValueVariable to better support repeating panels 

LICENSE, package.json
Decided that the AGPL license is going to limit adoption too much, as it will basically
force any plugin that uses this library to also be OSS.
So we decided to switch to Apache 2.0
=> License: Switch to Apache 2.0

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx, packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Noticed panels appearing below other rows when expanding a collapsed row.
Happens if you collapse a row. and then collapse another row above it.
Then try to expand the first row. The children it contains have to high y position
and needs to be corrected. We had a condition that only corrected the row child position
if it needed to be made higher not smaller.
I checked the current arch toggleRow logic and it did not have this condition that only correct y pos when greater 
<details>
<summary>📦 Published PR as canary version: <code>1.2.0--canary.326.6111681445.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.2.0--canary.326.6111681445.0
yarn add @grafana/scenes@1.2.0--canary.326.6111681445.0
```
</details>
=> SceneGridLayout: Fix toggle row issue

packages/scenes/src/components/SceneControlsSpacer.tsx, packages/scenes/src/components/SceneTimePicker.tsx
This is a fix for flickering that happens in core dashboards when we
discard the edits the time range controls for 1 frame move left.
This is due to all objects being inactive & active when restoring state.
The component wrapper does not render the component when inactive causing
this flickering when this spacer component is not rendered. For some
reason the time range controls are rendered before.
I think we might need to revisit this spacer logic at some point, either
introduce separate props for "filters" (left aligned), and controls (right aligned),
or some layout option on a Controls type/ interface.
<details>
<summary>📦 Published PR as canary version: <code>1.2.0--canary.332.6168332968.0</code></summary>
<br />
```bash
npm install …
```
=> SceneControlsSpacer: Fix flickering

packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.ts
Based on https://github.com/grafana/scenes/pull/328
This adds a `dataLayerFilters` property to SceneQueryRunner to perform annotations filtering per panel. This should serve exclusively Grafana Dashboard use case, as in apps, annotations could possibly be scoped to a panel by scene hierarchy.
=> DataLayers: Add filtering options to SceneQueryRunner

packages/scenes/src/core/types.ts, packages/scenes/src/querying/layers/SceneDataLayerControls.tsx, packages/scenes/src/utils/ControlsLabel.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/components/VariableValueSelectors.tsx, packages/scenes/src/variables/types.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Based on #337 
This unifies the loading indicator (that serves as a cancellation trigger) between data layer controls and variable controls.
Before:
After:
=> Unify layers and variables loading/cancellation UI

packages/scenes-app/src/demos/annotations.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.test.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.ts, packages/scenes/src/querying/layers/SceneDataLayerControls.test.tsx, packages/scenes/src/querying/layers/SceneDataLayerControls.tsx, packages/scenes/src/querying/layers/TestDataLayer.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts, packages/scenes/src/utils/ControlsLabel.tsx, packages/scenes/src/utils/LoadingIndicator.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/components/VariableValueSelectors.tsx, packages/scenes/src/variables/types.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Introduces the possibility of canceling data layer queries using a button (spinner) in the data layer control.
- `SceneDataLayerBase` now has `data: PanelData` state so that layer doesn't have to implement it.
- `SceneDataLayerBase` now has `runLayer` abstract method that should implement query execution logic and subscription setup. `runLayer` is now executed also in the base class, so that layers don't have to implement `shouldRunQueriesOnActivate`. This is now handled in the base class, so activation handlers should not be needed in the layers, unless some peculiar logic is required.
- `SceneDataLayerControls` now renders a loading spinner for layers that take >500ms to resolve results. Clicking on the icon will cancel layer query. …
=> DataLayers: Allow cancelling layers from layer control

packages/scenes/src/querying/layers/SceneDataLayerControls.tsx, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/utils/ControlsLabel.tsx, packages/scenes/src/utils/getMessageFromError.ts
Just a cosmetic addition that shows an error message in the data layer control when there's a data source loading error. Other errors for standard annotation queries are emitted from the `runRequest` call.
https://github.com/grafana/scenes/assets/2376619/b760ee5f-3b1d-4736-8f21-5e0b0bf9b4aa
<details>
<summary>📦 Published PR as canary version: <code>1.3.1--canary.342.6223317385.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.3.1--canary.342.6223317385.0
yarn add @grafana/scenes@1.3.1--canary.342.6223317385.0
```
</details>
=> AnnotationsDataLayer: Handle data source error

packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.test.ts, packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.ts
Noticed an issue with filtering when applying data layers in https://github.com/grafana/grafana/pull/74610.
Basically, the resulting frames were all assigned the same length and hence incorrect results were added to frame that should have had annotations filtered out.
<details>
<summary>📦 Published PR as canary version: <code>1.3.2--canary.343.6224826285.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.3.2--canary.343.6224826285.0
yarn add @grafana/scenes@1.3.2--canary.343.6224826285.0
```
</details>
=> Annotations filtering operator: Correctly populate filtered frames

packages/scenes/src/components/SceneApp/SceneAppPage.test.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx
Fixes infinite recursion of enrichDataRequest when SceneAppPage is rendered standalone (without a SceneApp parent). 
Also simplify the logic 
<details>
<summary>📦 Published PR as canary version: <code>1.3.3--canary.345.6226201564.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.3.3--canary.345.6226201564.0
yarn add @grafana/scenes@1.3.3--canary.345.6226201564.0
```
</details>
=> SceneAppPage: Fix infinite recurision of enrichDataRequest

packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
* Adds bind for query method passed to runRequest
* makes the upgrading of legacy queries a bit more tolerant (and also non mutating) 
<details>
<summary>📦 Published PR as canary version: <code>1.4.0--canary.348.6245532201.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.4.0--canary.348.6245532201.0
yarn add @grafana/scenes@1.4.0--canary.348.6245532201.0
```
</details>
=> Variables: Fixes issue with running variable queries with custom or legacy runner

packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
Argh, 
just as I merged https://github.com/grafana/scenes/pull/348 I found an issue with it, sadly typescript did not catch it because query is typed: any in QueryVariable 
<details>
<summary>📦 Published PR as canary version: <code>1.5.0--canary.350.6245657382.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.5.0--canary.350.6245657382.0
yarn add @grafana/scenes@1.5.0--canary.350.6245657382.0
```
</details>
=> Variables: Fix issue with previous fix

packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
This is to allow public dashboards handling in core - in particular to allow PublicAnnotationsDataSource drop in and skipping annotations post processing for public dash.
<details>
<summary>📦 Published PR as canary version: <code>1.3.4--canary.347.6238186653.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.3.4--canary.347.6238186653.0
yarn add @grafana/scenes@1.3.4--canary.347.6238186653.0
```
</details>
=> AnnotationsDataLayer: Provide inheritance extension points

packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/querying/layers/annotations/utils.ts
Moves core deduplication logic to `AnnotationsDataLayer`, ref https://github.com/grafana/grafana/blob/main/public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts#L64
<details>
<summary>📦 Published PR as canary version: <code>1.5.2--canary.351.6247316628.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.5.2--canary.351.6247316628.0
yarn add @grafana/scenes@1.5.2--canary.351.6247316628.0
```
</details>
=> AnnotationsDataLayer: Events deduplication

packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/transformations.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/querying/SceneDataTransformer.ts, packages/scenes/src/querying/SceneQueryRunner.ts
This PR applies work by @ryantxu (https://github.com/grafana/grafana/pull/73451) to `SceneDataTransformer`.
Additionally, adds transformations demo to the demo app.
<details>
<summary>📦 Published PR as canary version: <code>1.5.2--canary.354.6254117203.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.5.2--canary.354.6254117203.0
yarn add @grafana/scenes@1.5.2--canary.354.6254117203.0
```
</details>
=> SceneDataTransformer: Handle transformation errors

docusaurus/docs/scene-app.md, packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneApp.tsx, packages/scenes/src/index.ts
The problem with our current useMemo recommended approach is that the whole scene app and all the data/scene caches are lost when you leave the app (say click on a link to explore, and then go back)
So this adds a new useSceneApp that adds a global cache that stays put even when you leave the app
=> SceneApp: Introduce a useSceneApp hook that should replace useMemo as method of caching SceneApp instance 

packages/scenes/src/core/types.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts, packages/scenes/src/variables/VariableDependencyConfig.ts, packages/scenes/src/variables/VariableValueRecorder.ts
This mostly does the same thing as `SceneQueryRunner` to support variables in annotation queries. Tests are literally the same.
`SceneDataLayerBase` handles basic behaviors (like skipping execution on activation when the variable is not loaded), while AnnotationsDataLayer implements the variables to support itself. `SceneDataLayerBase` also handles variable values recording, hence the subtle change in `VariableValueRecorder`.
<details>
<summary>📦 Published PR as canary version: <code>1.6.0--canary.358.6274180040.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.6.0--canary.358.6274180040.0
yarn add @grafana/scenes@1.6.0--canary.358.6274180040.0
```
</details>
=> AnnotationsDataLayer: Add variables support

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/getEnrichedDataRequest.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts, packages/scenes/src/utils/test/TestSceneWithRequestEnricher.ts
Needed for core dashboards to provide `publicDashbboardsAccessToken` to annotation queries. This is using `DataRequesEnricher`.
<details>
<summary>📦 Published PR as canary version: <code>1.7.1--canary.364.6298364243.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.7.1--canary.364.6298364243.0
yarn add @grafana/scenes@1.7.1--canary.364.6298364243.0
```
</details>
=> AnnotationsDataLayer: Support query request enriching

packages/scenes-app/src/demos/dynamicPanelOptions.tsx, packages/scenes-app/src/demos/index.ts, packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/PanelBuilders/FieldConfigBuilder.ts, packages/scenes/src/core/PanelBuilders/FieldConfigBuilders.ts, packages/scenes/src/core/PanelBuilders/PanelOptionsBuilder.ts, packages/scenes/src/core/PanelBuilders/PanelOptionsBuilders.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts, packages/scenes/src/core/PanelBuilders/index.ts, packages/scenes/src/index.ts
Closes https://github.com/grafana/scenes/pull/266
This PR implements logic for dynamically updating panel options and field config. 
It also refactors `VizPanelBuilder` a bit, so that field config and options are built using a respective, composed builder. I think this makes sense as for programmatic options/field config updates it's good to have typed builders for `Options` and `FieldConfig` types - at least for the built-in Grafana visualizations. So the user can use exactly the same API as they would use for building panel using `PanelBuilders`.
<details>
<summary>📦 Published PR as canary version: <code>1.8.0--canary.363.6298066504.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.8.0--canary.363.6298066504.0
yarn add …
```
=> VizPanel: Allow options and field config updates

packages/scenes/src/variables/components/VariableValueSelectors.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts, packages/scenes/src/variables/variants/TestVariable.tsx
Fixes #349
Shows and logs variable errors happening in the validateAndUpdate observable / rxjs process
=> SceneVariableSet: Show and log errors

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/core/SceneTimeZoneOverride.tsx, packages/scenes/src/core/types.ts
* Adds weekStart support (needed for core dashboards)
* Make sure we pass fiscalYearMonth everywhere
=> SceneTimeRange: Add weekStart support and make sure fiscalYearMonth is used everywhere

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
This is an opinion the old variable system supports (but only in the persisted model, not exposed in the UI from what I can tell). 
This was the simplest way I found to disable url sync for
* QueryVariable
* CustomVariable
* DataSourceVariable
=> Variables: Support skipUrlSync option

packages/scenes-app/src/demos/dynamicPage.tsx, packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx, packages/scenes/src/components/SceneApp/types.ts
* Adds ability to specify custom fallback page on `SceneAppPage`
* Update `dynamicPage` demo to use this feature to show loading message while tab is loading
Context:
App o11y service overview needs to load some metadata from metrics data source before it can figure out what tabs to show for a particular service.  For this purpose it uses a custom "loader" scene that initializes required variables and a query runner to load the metadata. But if user cold opens URL for a tab, tabs are not initialized yet. Currently we rely on a routing "hack" to show the loader scene instead of "page not  found" fallback scene. This can be nicely solved by allowing `SceneAppPage` to provide a custom fallback page.
Related discussion: https://raintank-corp.slack.com/archives/C04FRQ2S0AV/p1695390081582359
I …
=> SceneAppPage: Custom fallback page

packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
If the SceneApp is created with useMemo which is invalidated shortly after initial loading (causing unmount & remount of the embedded scene). This caused a state mismatch in SceneAppPageView where the local react state initialized did not match the scene state of the page containerState.initializedScene 
https://github.com/grafana/grafana-k8s-plugin/pull/819/files#diff-3bfbfb0a9f4447beaacffbc8799fc57325273a246e52244ba42dcb8d420966fdR43
Fix
* Reverted back to using only page state to know if it it initialized. And to solve the issue of re-initializing it (needed for Url sync) when coming back I clear initializedState when SceneAppPageView is unmounted. 
Not sure how to write a unit test for this, was only able to replicate it with this change to how we create the demo app
```ts
export …
```
=> SceneAppPageView: Fixes react and scene state missmatch

packages/scenes-app/src/demos/adhocFiltersDemo.tsx, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
With the change in core to pass filters via request object, and to start using it in Prometheus made it so that the new adhoc filters feature was not working with scenes anymore (for prometheus). 
So I have to make this change now (before updating latest packages, hence the typescript ignore).
related to 
https://github.com/grafana/grafana/pull/75552
=> AdhocFilters: Pass filters via request object

docusaurus/docs/advanced-adhoc-fIlters.md, docusaurus/docs/advanced-adhoc-fIlters.tsx, docusaurus/website/sidebars.js
=> AdhocFilters: Add docs for AdhocFilterSet and AdhocFiltersVariable

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/src/variables/variants/TestVariable.tsx
Fixes issue with a variable query returning no options. The All state should be set, but
was not.
<details>
<summary>📦 Published PR as canary version: <code>1.14.0--canary.391.6404398888.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.14.0--canary.391.6404398888.0
yarn add @grafana/scenes@1.14.0--canary.391.6404398888.0
```
</details>
=> Variables: Fix issue with all value state and no options

packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/variables/components/VariableValueInput.tsx
Started working on https://github.com/grafana/scenes/issues/383 , but found the demo scene needing some refactoring :) 
The demo scene was a bit messy with some duplicated variables and a layout that was hard to get an overview of. 
* Simplify and reduce unnecessary layout elements 
* Reduce some duplicated variables (don't need two interval variables)
* Added a new scene that has DataSourceVariable and TextBoxVariable 
* Remove unnecessary nested scene (we still have one, but we do no need two)
=> Variables: Updates the demo scene

packages/scenes/src/behaviors/ActWhenVariableChanged.ts
This helps making it possible to use the behavior without declaring a variable of the behavior and the behavior parent and capturing their instances in a lambda.
Having the behavior be part of the callback makes it possible to write the onChange callback as a pure function.
=> ActWhenVariableChanged: Add behavior to onChange callback

packages/scenes/src/variables/TestScene.ts, packages/scenes/src/variables/components/VariableValueInput.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/variants/TextBoxVariable.test.tsx, packages/scenes/src/variables/variants/TextBoxVariable.tsx
=> TextBoxVariable: Fixes and make it auto size

docusaurus/docs/variables.tsx, packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/variables/VariableDependencyConfig.ts, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/constants.ts, packages/scenes/src/variables/utils.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx, packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts, packages/scenes/src/variables/variants/query/toMetricFindValues.ts
Closes #208
Tested with Graphite (and TestData data source). 
This is such a messy feature that barely works (in the old template variable system implementation) for some legacy data sources. 
Discovered some strange things.
On the old code we only check the query if it's a string or if it has a "target" property (only graphite query editor has this)
https://github.com/grafana/grafana/blob/main/public/app/features/variables/pickers/OptionsPicker/actions.ts#L81 
I solved this in this implementation by stringifying the whole query model then looking for "__searchFilter" .
Second strange / buggy thing in the old implementation is: For Custom and Standard variable support we pass it as scopedVars but not with leading underscores (so it wont work as way to interpolate the query). …
=> QueryVariable: Support for queries that contain "$__searchFilter" 

packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx
I removed this bit a few weeks ago because I thought it was not needed. Must have tested with demo app that had not rebuilt properly.
=> SceneAppPage: Fix enrichDataRequest call for drilldown pages

packages/scenes/src/components/VizPanel/VizPanel.tsx
This is one required to handle the auto migration of old angular panels. 
Because the panel type change migration handlers already work by mutating a "PanelModel" like object I am continuing to use that model here as it makes the logic very simple, we just build this mutatable panel model-like object once and pass it through the custom handler, and then through the normal migration handler. 
used in https://github.com/grafana/grafana/pull/76100
=> VizPanel: Add support for a custom migration handler

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
To support keybindings that need access to hovered over panel (and maybe some e2e tests) we need these data attributes on the element.
Used in https://github.com/grafana/grafana/pull/76233 
<details>
<summary>📦 Published PR as canary version: <code>1.15.0--canary.403.6466736145.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.15.0--canary.403.6466736145.0
yarn add @grafana/scenes@1.15.0--canary.403.6466736145.0
```
</details>
=> Markup: element data keys changes 

packages/scenes/src/variables/variants/IntervalVariable.tsx
The old variable system uses `$__auto_interval`... and in the scenes, we changed the prefix to be `$__auto`
<details>
<summary>📦 Published PR as canary version: <code>1.15.1--canary.407.6480642750.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.15.1--canary.407.6480642750.0
yarn add @grafana/scenes@1.15.1--canary.407.6480642750.0
```
</details>
=> Scenes: Interval Variable now considers $__auto_interval

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
Working on fixing "viewPanel" for repeated panels on full page reload, and this old condition caused the panel to be empty as the row level SceneVariableSet is not active when viewing the panel. 
This old condition is not needed anymore now that we have fixed the flow of activation by not rendering components until they are active (so that higher level objects are activated before children). 
<details>
<summary>📦 Published PR as canary version: <code>1.16.0--canary.405.6471182532.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.16.0--canary.405.6471182532.0
yarn add @grafana/scenes@1.16.0--canary.405.6471182532.0
```
</details>
=> SceneVariableSet: isVariableLoadingOrWaitingToUpdate should ignore isActive state

packages/scenes/src/components/SceneTimePicker.test.tsx, packages/scenes/src/components/SceneTimePicker.tsx
Implements `onMoveBackward` and `onMoveForward` for `SceneTimePicker`, more or less following the logic of `getShiftedTimeRange` from core grafana
Closes #406
=> SceneTimePicker: Add posibility to navigate backwards/forwards an absolute time range

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Removes the last trailing comma.
It was not a problem for prometheus as it was valid label filter expression but
it's not valid for loki.
<details>
<summary>📦 Published PR as canary version: <code>1.19.0--canary.411.6525620163.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.19.0--canary.411.6525620163.0
yarn add @grafana/scenes@1.19.0--canary.411.6525620163.0
```
</details>
=> AdHocVariable: Fixes trailing comma

packages/scenes/src/core/SceneTimeRange.tsx
Fixes https://github.com/grafana/scenes/issues/412
When setting the time range, `moment.toISOString` method was used that returns UTC time. This changes the time range update function to respect the closest time zone.
<details>
<summary>📦 Published PR as canary version: <code>1.19.1--canary.413.6544510710.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.19.1--canary.413.6544510710.0
yarn add @grafana/scenes@1.19.1--canary.413.6544510710.0
```
</details>
=> SceneTimeRange: Respect time zone when updating time range

packages/scenes/src/core/SceneTimeRange.tsx
Reverts grafana/scenes#413
as it breaks the time range URL from / to iso string formatting
=> Revert "SceneTimeRange: Respect time zone when updating time range"

packages/scenes/src/variables/variants/DataSourceVariable.test.ts, packages/scenes/src/variables/variants/DataSourceVariable.tsx, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
old (current) template variable system DataSourceVariable was changed in May in the main repo to put uid as the value (https://github.com/grafana/grafana/pull/69259) 
Fixes https://github.com/grafana/scenes/issues/383
=> DataSourceVariable: Value should be uid, and other fixes

packages/scenes-app/src/demos/cssGridLayoutDemo.tsx, packages/scenes/src/components/layout/CSSGrid/SceneCSSGridLayout.tsx
=> SceneCSSGridLayout: Make rowGap and columnGap use grid units

packages/scenes/src/variables/interpolation/formatRegistry.test.ts, packages/scenes/src/variables/interpolation/formatRegistry.ts
Sqlstring format should escape double quotes since the formatted value is nested in a JSON object sent to query API, see https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L193
Without escaping double quotes the JSON gets malformed and we get errors like the following:
=> Variables: Fixes SQL formatting and escaping double quotes 

docusaurus/docs/scene-layout.md, docusaurus/docs/scene-layout.tsx, packages/scenes-app/src/demos/docs-examples.tsx
Fixes #421 
Question: should we put some clarification in the docs about the difference between `SceneCSSGridLayout` and `SceneGridLayout`?
As an alternative to `SceneFlexLayout`, `SceneCSSGridLayout` is now available to wrap scene items in a CSS grid. To create a scene with a CSS grid with two columns and rows with a height of `150px`, see example below:
```ts
const queryRunner = new SceneQueryRunner({
datasource: {
type: 'prometheus',
uid: 'gdev-prometheus',
},
queries: [
{
refId: 'A',
expr: 'rate(prometheus_http_requests_total{}[5m])',
},
],
});
const scene = new EmbeddedScene({
$data: queryRunner,
body: new SceneCSSGridLayout({
templateColumns: 'repeat(auto-fit, minmax(400px, 1fr))`,
autoRows: '150px',
children: [
PanelBuilders.timeseries().setTitle('Graph 1').build(), …
```
=> [cr] adds docs for SceneCSSGridLayout

packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Adds API to VizPanel to allow panel links rendering. There is no component for links rendering in the library, as the dashboard's link renderer heavily depends on core-only code.  https://github.com/grafana/grafana/pull/77295
We may consider adding some generic link renderer, but I would wait with that until we get request for panel links support in the lib.
<details>
<summary>📦 Published PR as canary version: <code>1.20.1--canary.437.6693096080.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.20.1--canary.437.6693096080.0
yarn add @grafana/scenes@1.20.1--canary.437.6693096080.0
```
</details>
=> VizPanel: Allow title items configuration

packages/scenes/src/components/layout/CSSGrid/SceneCSSGridLayout.tsx
Adds optional properties `gridRow` and `gridColumn` to `SceneCSSGridItem`. This allows an item to span multiple rows and columns in a `SceneCSSGridLayout`.
=> feat: support gridRow and gridColumn for SceneCSSGridItem

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Closes #404
Provides a way to pass panel id to PanelProps via PanelContext instanceState
=> VizPanel: Support passing legacyPanelId to PanelProps

packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx
I am removing this condition as I don't think it's needed, at least not if you use the data source variable consistently (in both the set and queries)
=> SceneQueryRunner: Fixes adhoc filters when using a variable data source

packages/scenes-app/src/demos/cursorSync.tsx, packages/scenes/src/behaviors/CursorSync.ts
The pie chart legend hover events are not working. They highlight slices on the same panel and using the standard DataHoverEvent. The panel relies on being able to subscribe to local events. But the scenes PanelContextEventBus filters out any local events. 
Removing this filtering, panels filter out local events they don't care about using:
```ts
if (eventBus === evt.origin) {
return;
}
```
Trying to make the needed changes to get that to work. But when testing the cursor sync demo I am unable to get it to work (with or without these changes). All cursors show on all panels. Think uPlot cursor sync scope key has broken. 
We could also try to revive https://github.com/grafana/grafana/pull/71866
=> PanelContext: Eventbus should not filter out local events

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Noticed that dashboards with variables that have different value / text representation, after a full page reload the panel repeats only showed the "id" (value) representation and was not showing the correct text representation. 
The issue as that we did not compare the text values when deciding to update or not
=> Variables: Fixes url sync issue for key/value multi value variables

packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/utils.ts
In core grafana we received a community contribution to implement natural sort. https://github.com/grafana/grafana/pull/78024 
This PR just adds their changes and a few unit tests.
=> Variables: Add natural sort from core grafana to query variables

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Fixing regression I've introduced in https://github.com/grafana/scenes/pull/464
=> VizPanel: Don't show popup when description is empty

packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
This PR adds a new property for adhoc filters, so that the tag keys can be filtered based on a regex
=> Adhoc filters: Add tagKeyRegexFilter prop

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
We want to avoid false detection of stale time lines and compare using the underlying `moment.unix()` time stamp for the `from`s and the `to`s, so that we don't accidentally compare object instances.
See:
- https://github.com/grafana/grafana/issues/78185
=> fix: compare time ranges using actual unix time vs objects

packages/scenes/src/index.ts, packages/scenes/src/variables/variants/guards.ts
- Added type guards for scene variables
- Expose guards through `sceneUtils`
Fixes [#78405](https://github.com/grafana/grafana/issues/78405)
<details>
<summary>📦 Published PR as canary version: <code>1.24.0--canary.472.6942909529.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.24.0--canary.472.6942909529.0
yarn add @grafana/scenes@1.24.0--canary.472.6942909529.0
```
</details>
=> Variables: Add type guards for variables

packages/scenes/src/querying/SceneQueryRunner.ts
Fixes https://github.com/grafana/scenes/issues/462
Collecting data layers assumed queries have been resolved already. This is not true, layers can definitely finish sooner than queries, there is no guarantee. And using non-null assertions is bad anyway ;)
Fixes:
-  transformation errors we all saw during bug  bash today 
- [data.timeRange](https://github.com/grafana/scenes/blob/main/packages/scenes/src/querying/SceneQueryRunner.ts#L251) being undefined if layers finish sooner than queries 
<details>
<summary>📦 Published PR as canary version: <code>1.24.1--canary.474.6946948769.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.24.1--canary.474.6946948769.0
yarn add @grafana/scenes@1.24.1--canary.474.6946948769.0
```
</details>
=> Fix non-null assertion in SceneQueryRunner

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Fixes an issue seen on ops (in bugbash) where variable had an error. The error was caused by
the wrong data source variable to be selected.
The dashboard was saved with the datasource name in the "current.value" property (since data source
variables used to only have the name as both value and text).
The old variable system supports this by validating the current value by looking up option
by both text and value.
https://github.com/grafana/grafana/blob/main/public/app/features/variables/state/actions.ts#L526
I am refining that logic a bit by first looking through all options by value, and if nothing is found
take and option that matches by text.
=> Variables: Fixes validation issue where the current saved value only matches text representation

packages/scenes/src/variables/variants/DataSourceVariable.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
Noticed that errors that happen on QueryVariables did not go away (once I had switched to correct data source and was getting options)
=> Variables: Clear error state

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Fixes an issue when there was a difference between maxDataPoints passed to SQR and maxDataPoints passed to PanelQueryRunner in the core.
The difference is that we use `useMeasure` in scenes and `AutoSizer` in core to calculate the width of a panel. The version of AutoSizer we use always returns width as [Int](https://github.com/bvaughn/react-virtualized-auto-sizer/blob/1.0.11/src/AutoSizer.ts#L149) while useMeasure return floats. 
Given the testing I performed, `Math.round` is what we want to do here to have parity with core maxDataPoints rounding.
This is easily testable locally. You can i.e. set up gdev-prometheus data source and observe what is the maxDataPoints sent with the request.
<details>
<summary>📦 Published PR as canary version: …
=> VizPanelRenderer: Round visualization width pushed to data provider

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes an issue where SceneQueryRunner was waiting for variables but shouldRunQueriesOnActivate returned false (due to data layer received and setting this.state.data) 
<details>
<summary>📦 Published PR as canary version: <code>1.24.5--canary.481.6981394489.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.24.5--canary.481.6981394489.0
yarn add @grafana/scenes@1.24.5--canary.481.6981394489.0
```
</details>
=> SceneQueryRunner: Fixes issue with waiting for variables

packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
For feature parity in Dashboards Variable Settings migration, we need the `definition` prop defined in query variables. 
This PR adds the prop to the state. Also adds an example, I am not sure if the example is needed as the new prop is not doing anything special here. 
<details>
<summary>📦 Published PR as canary version: <code>1.26.0--canary.489.7088562794.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.26.0--canary.489.7088562794.0
yarn add @grafana/scenes@1.26.0--canary.489.7088562794.0
```
</details>
=> Variables:  Query - Add optional `definition` prop to state

packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
Talking with @torkelo and @itsmylife we decided to always run variable queries with dashboard time range, regardless of the refresh config. Otherwise, the variable query may produce results that are not in line with the data displayed in a dashboard.
=> QueryVariable: Run query with scene time range on when configured to run on load

packages/scenes-app/src/pages/DemoListPage.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
fixes https://github.com/grafana/scenes/issues/500
Our test cases did not include a case where chained variables did not include the use of the first variable. So we had a test case for variable dependencies like 
B depends on A
C depends on A and B
but we did not have a case for 
B depends on A
C depends on B 
Luckily it was a simple thing to fix :) 
<details>
<summary>📦 Published PR as canary version: <code>1.28.1--canary.501.7194502273.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.28.1--canary.501.7194502273.0
yarn add @grafana/scenes@1.28.1--canary.501.7194502273.0
```
</details>
=> Variables: Fixes issue with chained variable and cascading updates

packages/scenes/src/variables/macros/timeMacros.test.ts, packages/scenes/src/variables/macros/timeMacros.ts
Fixes https://github.com/grafana/scenes/issues/507 
I think instead of a fix like https://github.com/grafana/grafana/pull/79645  we could change this macro to just return the variable expression when no data or request is found, this way this behavior is not changed for other data sources. 
The variable interpolation engine behaves similarly, in that it returns the variable expression unchanged when a variable cannot be found
=> IntervalVariable: Makes it return the original variable expression when data or request is not present

packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/interactiveTableDemo.tsx, packages/scenes-app/src/demos/utils.ts
Adds a demo using InteractiveTable that renders sub scenes in the expandable rows. 
This I think highlights one scenario where scenes lib is making something a bit harder than it should be. 
To render the expanded row scene we need to first attach it it to the scene. It's not too complicated but still feels like there is something here we could do to make this scenario easier.
=> Demos: Adds an example with InteractiveTable with exandable rows that shows sub scenes 

packages/scenes/src/components/layout/split/Splitter.tsx
Fixes a small issue where if the panel was being altered with arrows keys and focus was lost (e.g. by clicking somewhere), panel size would continue to be modified when arrow keys were lifted.
=> Splitter: Fixes small issue with keyboard control

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Noticed some intermittent unexepcted cancelled queries in network logs.
Found that the problem is that if `SceneQueryRunner` has `maxDataPointsFromWidth=true` and variables change/complete before width is received, it will run queries without waiting for width. Then  width is received immediately after and new execution is triggered.
This PR prevents variable update callback from executing queries if container width has not been received yet.
=> SceneQueryRunner: Fix redundant execution on variable change

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
In case annotations come with result of query instead of from layers, new annotations would be appended to list of previous annotations instead of replacing them. Eg, when cahnging time range, annotations from previous time range remain visible. If time ranges overlap, annotations get duplicated, triplicated etc. 
This PR refactors query runner to merge annotations from layers and query result without keeping annotations from previous runs.
=> Fix issue with duplicate annotations

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/core/SceneTimeZoneOverride.tsx, packages/scenes/src/core/types.ts, packages/scenes/src/utils/evaluateTimeRange.ts
Dashboards PR: https://github.com/grafana/grafana/pull/79703
This enables support for `UNSAFE_nowDelay` in Dashboards. It is prefixed as `UNSAFE` because we don't know how used and useful is this.
This allows us to override the now time by entering a time delay. This option accommodates known delays in data aggregation to avoid null values.
=> SceneTimeRange: Support delay now to avoid data drops in charts

packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
While investing some variable timing issues with SceneQueryRunner and investigating changing SceneVariableSet to update scene after each variable update is complete (instead of waiting for all variables) I realised one scenario is not handled currently. 
Example:
* var A  (depends on time range)
* var B (depends on B)
* Query Q (depends only on B) 
When time range updates A starts loading, and Query Q also gets the new time range and checks it's dependencies loading state (only B) which is not loading so starts a new query. Later after A completes and starts B and B updates it triggers a new query for Q (So double queries for this time range update). 
We have not hit this in current tests / and manual scenarios as for the initial activation we add both A and B to the update queue so on …
=> Variables: Checking if a dependency is loading should also check that dependency dependencies

packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts, packages/scenes/src/variables/VariableDependencyConfig.ts
a continuation of https://github.com/grafana/scenes/pull/525  (base) 
Exploration unifying / moving handling of "waitingForVariable" state to VariableDependencyConfig. 
This flag / state is just to know that we wanted to do something but could not, for example: 
* Issue query on activation 
* Issue query on time range change 
But we can't do that as one of the variable dependencies (or a dependency of a dependency) where in a loading state. But this means that we now want to know when any variable update is completed not just a direct dependency as just because a dependency of a dependency where in loading state does not mean any dependency changed value (just that they could have). 
TODO
* Add some more tests to VariableDependencyConfig
=> Variables: Move handling of "waitingForVariables" to VariableDependencyConfig 

packages/scenes/src/components/layout/split/SplitLayout.ts, packages/scenes/src/components/layout/split/SplitLayoutRenderer.tsx
This will allow for fixing the current issue with the panel editor in scenes
=> SplitLayout: Allow pane style overrides to be passed through

packages/scenes-app/package.json, packages/scenes/package.json
**Related PR:** https://github.com/grafana/scenes/pull/295
Updated the `@grafana/*` peer dependencies to the latest released version (`10.2.3`). (Please let me know if this shouldn't be done yet for some reason. I came across this while trying to update the scaffolded dependencies in the `@grafana/create-plugin` tool.)
=> Chore: Update peer dependencies

packages/scenes-app/src/demos/grid.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
I don't think we need to disable the new tooltips, like proposed in https://github.com/grafana/grafana/pull/80496 
This PR adds all the changes needed to support them
* Decremental z-index 
* Layout context that provides the boostZIndex context method 
<details>
<summary>📦 Published PR as canary version: <code>1.30.0--canary.530.7559055334.0</code></summary>
<br />
```bash
npm install @grafana/scenes@1.30.0--canary.530.7559055334.0
yarn add @grafana/scenes@1.30.0--canary.530.7559055334.0
```
</details>
=> SceneGridLayout: Support new visualization tooltips

packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneDataTransformer.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes an issue with the new approach to shared query (DashboardDataSource), this data source now rely on the getResultStream of the data providers and SceneDataTransfomer was not emitting updates on the result stream when no transformations where added. 
@dprokop this fixes the issue with the "Get help" drawer showing a loading panel that never completes.
Also changes the SceneQueryRunner so that the result stream includes the data layers.
=> SceneDataTransformer: Fixes issue with getResultStream not emitting values when there are no transformations

packages/scenes/src/variables/interpolation/sceneInterpolator.ts, packages/scenes/src/variables/variants/LocalValueVariable.ts
Provides a fix for SQL data source queries used in a repeated row scenario (discovered when dogfooding dashboard scene for viewers). The root cause problem lies in the `SqlDatasource` implementation which [relies on variable.multi and vairbale.includeAll ](https://github.com/grafana/grafana/blob/main/packages/grafana-sql/src/datasource/SqlDatasource.ts#L80) to format the string correctly. 
This PR brings two  properties to the `LocalValueVariable`. Marking them as ommited in LocalValueVariabel for a reason being LocalValueVariable is used ONLY in the repeats scenatio which assume a variable being a multi one.
@zoltanbedi  I would love to fix this in `SqlDatasource` as the dependency there on the multi/include all sounds not solid - think about a single value variable that has include all …
=> LocalValueVariable: Provide backwards compatibility for SQL-ish data source

packages/scenes/src/core/sceneGraph/index.ts, packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx
Depends on https://github.com/grafana/grafana/pull/81071
This passes scene queries to `getTagKeys` calls so that data source can decide which dimensions are applicable in a scene given provided queries context.
=> AdHocFiltersSet: Pass scene queries to getTagKeys calls

package.json, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, yarn.lock
**Problem**
When the `AdHocFilterSet` is activated, this registers the filters into a global object to be findable by the SceneQueryRunner.
When rendering the components for the `AdHocFiltersVariable` because we were not using the component from the model, the `AdHocFilterSet` scene object was not activated, so they were not findable by the SceneQueryRunner.
**Solution**
Use the component from the scene object instead of importing and using the static class property.
_This was found while implementing: https://github.com/grafana/grafana/pull/81318_ 
<details>
<summary>📦 Published PR as canary version: <code>2.2.1--canary.550.7712757823.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.2.1--canary.550.7712757823.0
yarn add …
```
=> AdHocFiltersVariable: AdHocFilterSet is not activated when the parent variable is mounted

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
**Problem**
When creating a variable using `AdHocFiltersVariable.create()` the `applyMode` state prop was not configurable. This was forcing to use AdHocFiltersVariable in `manual` only. But in the Dashboard use case reflected here https://github.com/grafana/grafana/pull/81318 where we use AdHocFiltersVariable to manage filters for dashboard panels, we need `applyMode: same-dashboard`
**Solution**
Accept `applyMode` as the initial state but default to `manual` if it is not defined. This will avoid breaking changes.
<details>
<summary>📦 Published PR as canary version: <code>2.2.1--canary.553.7712958297.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.2.1--canary.553.7712958297.0
yarn add @grafana/scenes@2.2.1--canary.553.7712958297.0 …
```
=> AdHocFiltersVariable: The `create()` factory supports `applyMode` as parameter

packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.ts
Fixes issues with reactivating annotation dataLayers, where the `SceneQueryRunner` subs would get stale and needed to be refreshed.
`SceneDataLayerBase - querySub` also needs to be reinitialised on dataLayer reactivation.
<details>
<summary>📦 Published PR as canary version: <code>2.2.2--canary.554.7713830844.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.2.2--canary.554.7713830844.0
yarn add @grafana/scenes@2.2.2--canary.554.7713830844.0
```
</details>
=> Fix dataLayer subscriptions refresh on reactivation

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts, packages/scenes/src/variables/variants/TestVariable.tsx
Fixes #556 
Say you have variable A, and B (B depends on A). If B is very slow and loading and you change A it should cancel B and add it to update queue.
=> SceneVariableSet: Cancel query when dependency changes

packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/services/UrlSyncManager.ts, packages/scenes/src/utils/test/activateFullSceneTree.ts
Finally after being unable to replicate this url overwrite scenario in a unit test I managed to figure out how to replicate it. 
It's when you subscribe to a scene object's state (a scene object that has url sync), and in that subscription you change another object's state (which also has url sync). 
So what was happening was this 
Two scene objects: A (name=A)  B (other=B).   both with url sync for properties name & other respectively 
* Change state of Object A (name=update) -> 
* Triggers state change handler =>
* State change handler changes state of Object B (other=muu)  =>
* UrlSyncManager updates state url with (other=muu) => 
* Url location change triggers sync from URL for Object A as the url as state name=A and state is `name=updated`, so the old value is used to overwrite the …
=> UrlSync: Fixes overwrite issue where later state change overwrites earlier change

packages/scenes-app/src/demos/adhocFiltersDemo.tsx, packages/scenes-app/src/demos/grid.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
* Fix missing resize handled due to not rendering children in the grid item wrapper
* Add css class name to grid wrapper so we can if we want to style resize handle a bit differently for scenes dashboards 
* fix height issue in demo
=> SceneGridLayout: Fixes missing resize handles

packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
Fixes https://github.com/grafana/support-escalations/issues/9205
* Makes selects virtualized to handle many options  (Select get's super slow when option count is > 5000) 
* Fixes very bad bug in QueryVariable where every query was thought to contain __searchFilter 
Fixes https://github.com/grafana/grafana/issues/81931
<details>
<summary>📦 Published PR as canary version: <code>2.6.1--canary.569.7796550591.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.6.1--canary.569.7796550591.0
yarn add @grafana/scenes@2.6.1--canary.569.7796550591.0
```
</details>
=> Variable: Fixes performance issues with variables with many select options

packages/scenes/src/variables/groupby/GroupByVariable.tsx
Required for https://github.com/grafana/grafana/pull/81717
We missed this type rename :( 
<details>
<summary>📦 Published PR as canary version: <code>2.6.2--canary.571.7799339718.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.6.2--canary.571.7799339718.0
yarn add @grafana/scenes@2.6.2--canary.571.7799339718.0
```
</details>
=> GroupBy variable: Fix variable type

packages/scenes/src/services/SceneObjectUrlSyncConfig.ts, packages/scenes/src/variables/variants/TextBoxVariable.test.tsx, packages/scenes/src/variables/variants/TextBoxVariable.tsx
The key was statically assigned in SceneObjectUrlSyncConfig, update the signature for SceneObjectUrlSyncConfig so that keys can be made into function 
<details>
<summary>📦 Published PR as canary version: <code>2.6.3--canary.574.7800968870.0</code></summary>
<br />
```bash
npm install @grafana/scenes@2.6.3--canary.574.7800968870.0
yarn add @grafana/scenes@2.6.3--canary.574.7800968870.0
```
</details>
=> TextBoxVariable: Fixes url sync key when name changes

packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/variableRepeater.tsx, packages/scenes/src/components/SceneByVariableRepeater.tsx, packages/scenes/src/index.ts
Closes #528 
Closes #516 
Like with the by frame repeater this could be improved by caching scene objects etc and not doing a repeat on activation when variable value is the same.  But I think it's a an ok start for now. 
https://github.com/grafana/scenes/assets/10999/ab82c27a-45bc-4171-a56f-4c360a940d22
=> ByVariableRepeater: Repeat layout for each variable value

packages/scenes-app/src/demos/grid.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
With the new custom resize handle styling I don't need any changes in core (can close this https://github.com/grafana/grafana/pull/81856) 
* New custom resize handle (Always visible when dragging enabled)
* Made it a bit bigger than the previous (bigger hit/hover area) so easier to click on 
The cursor that looks stuck is a bug in the recording software 
https://github.com/grafana/scenes/assets/10999/394d2625-ffdf-49f2-a293-4af10346f7c1
=> ResizeHandle: New style

packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Tiny change `16x` to `16px` to resolve:
=> SceneGridLayoutRenderer: fix svg height unit

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/VariableDependencyConfig.test.ts, packages/scenes/src/variables/VariableDependencyConfig.ts
Builds on https://github.com/grafana/scenes/pull/586 and fixes some bugs in main as well 
* Instead of subscribing to state of adhoc filters and group by (which also triggers when the variable goes into loading state) we now use the variable system. 
Bugfix 
* Currently we do not re-subscribe to adhoc filters nor group by when a query runner re-activates so nothing happens when coming back to a cached scene.
=> AdHoc/GroupBy: Use variable system as way to subscribe to changes

packages/scenes/src/behaviors/SceneQueryController.ts
* First I created the query controller to use it in the image renderer to know when all queries are complete
* Then discovered puppeteer has a built in `page.waitForNetworkIdle({ timeout: options.timeout * 1000 });` that allow you to wait for network requests to finish so[ decided to use that ](https://github.com/grafana/grafana-image-renderer/pull/496/)
* Then I discovered we cannot use that approach as we have async data sources that make requests and then wait up 10 seconds  before fetching the results in a separate request (Athena) 
* Then tried to use a bit of logic inside runRequest to keep a counter of all requests in Loading state but that does not work for template variables (some do not go through runRequest)
* So we do have to use the QueryController 
Instead of …
=> QueryController: Update global window query counter

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/VariableDependencyConfig.ts
* Now handles adhoc filters / group bys that are added after the first query
* Now handles adhoc filters / group by that are removed and re-added (so different instance) 
* Now handles adhoc filters / group by value changes that happen while inactive 
<details>
<summary>📦 Published PR as canary version: <code>3.2.0--canary.596.7890015712.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.2.0--canary.596.7890015712.0
yarn add @grafana/scenes@3.2.0--canary.596.7890015712.0
```
</details>
=> SceneQueryRunner: Improved way to detect changes to adhoc filters and group by variables

packages/scenes/src/variables/VariableDependencyConfig.test.ts, packages/scenes/src/variables/VariableDependencyConfig.ts
**Problem:**
If `variableNames` is defined, means the dependencies are explicit, so the state shouldn't be checked. This was causing a circular dependency here https://github.com/grafana/grafana/pull/81318
**Solution**
Do not check the state if `variableNames` is defined 
<details>
<summary>📦 Published PR as canary version: <code>3.2.1--canary.598.7892152279.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.2.1--canary.598.7892152279.0
yarn add @grafana/scenes@3.2.1--canary.598.7892152279.0
```
</details>
=> VariableDependencyConfig: do not scan state if `variableNames` is defined

packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Replicating the current logic of the old variable system: https://github.com/grafana/grafana/blob/6c42bd31c63d818fe74e50ea4ef684f849a544e0/public/app/features/variables/query/reducer.ts#L168 
Sets the value to `''` and text to 'None' , but I think setting both text and value to `''` is probably best 
All variables that extend from MultValueVariable (Query, DataSource, Custom) now clear the current value if no options / values are returned by query, clears to empty string or array depending on multi or not.
=> Variables: Clear current value when no options are returned

packages/scenes/src/variables/utils.ts
It is hardening the stringifying of the JSON to avoid circular dependencies.
The object can contain circular structures when extracting variables from a value object. For example, references to the parent object. See [this](https://drone.grafana.net/grafana/grafana/160784/1/6).
=> VariableDependencyConfig can extract variables from circular structures

docusaurus/docs/advanced-variables.md, packages/scenes/src/variables/VariableDependencyConfig.test.ts, packages/scenes/src/variables/VariableDependencyConfig.ts
**Problem**
By default, when no `statePaths` was defined in `VariableDependencyConfig`, the whole state was parsed. This is not an expected behavior if no specific criteria to find variables is defined.
**Solution**
Enable wildcard for `statePaths` to try to find variables in every state path.
```ts
class TestObj extends SceneObjectBase<TestState> {
public constructor() {
super({
query: 'query with ${queryVarA} ${queryVarB}',
otherProp: 'string with ${otherPropA}',
nested: {
query: 'nested object with ${nestedVarA}',
},
});
}
}
it('Should be able to extract dependencies from all state', () => {
const sceneObj = new TestObj();
const deps = new VariableDependencyConfig(sceneObj, { statePaths: ['*'] });
expect(deps.getNames()).toEqual(new Set(['queryVarA', 'queryVarB', 'nestedVarA', …
```
=> VariableDependencyConfig: Support `*` to extract dependencies from every state path

packages/scenes/src/behaviors/SceneQueryController.test.ts, packages/scenes/src/behaviors/SceneQueryController.ts, packages/scenes/src/querying/registerQueryWithController.ts
Fixes a bug in SceneQueryController that resulted in negative __grafanaRunningQueryCount due to double counting completed queries. 
This is caused by wrapper calling queryCompleted on first packet with state != LoadingState.Done (needed for some data sources who's observable never really completes), and we called queryCompleted on observable complete. 
Added a simple check in queryCompleted that the query is part of the running set, now we only try to remove it once and decrement __grafanaRunningQueryCount once 
<details>
<summary>📦 Published PR as canary version: <code>3.3.1--canary.600.7900942701.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.3.1--canary.600.7900942701.0
yarn add @grafana/scenes@3.3.1--canary.600.7900942701.0
``` …
=> SceneQueryController: Fixes double complete counting

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Adds query caching options to the SQR API.
<details>
<summary>📦 Published PR as canary version: <code>3.5.0--canary.603.7902695293.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.5.0--canary.603.7902695293.0
yarn add @grafana/scenes@3.5.0--canary.603.7902695293.0
```
</details>
=> SceneQueryRunner: Add query caching options

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Fixes https://github.com/grafana/scenes/issues/590
Fixes an issue with panels that use the panel data frames or fields as memoizable instance references. Since applyFieldConfig always returned new frames a simple resize invalidated the memoization used by the TracesPanel 
<details>
<summary>📦 Published PR as canary version: <code>3.6.1--canary.609.7970792291.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.6.1--canary.609.7970792291.0
yarn add @grafana/scenes@3.6.1--canary.609.7970792291.0
```
</details>
=> VizPanel: Fixes issue with non memoizable PanelData

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
For panel edit we need to move data provider to the parent of VizPanel, but still need VizPanel to provider the container width. So changing this logic to always call setContainerWidth on the data provider, not only when it's the data provider is defined on the same level as the VizPanel
=> VizPanel: Pass container width to data provider always

packages/scenes/src/components/VizPanel/VizPanel.tsx
So the legend options get changed based on which sorting should be applied but in case of no sorting the values for `sortBy` and `sortDesc` are undefined. 
This then turns into a problem here:
https://github.com/grafana/scenes/blob/efa082d3c27452f4ad6504d8784cea72c2e62a31/packages/scenes/src/components/VizPanel/VizPanel.tsx#L236
since after  `mergeWIth`  the target properties are used.
I changed the `replace` to true, skipping the `mergeWith` because I did not want to break some other logic in `onOptionsChange`
=> Legend sorting fix

package.json, yarn.lock
Seeing auto failure on PRs and main, hoping this fixes it 
<details>
<summary>📦 Published PR as canary version: <code>3.6.2--canary.617.8016493124.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.6.2--canary.617.8016493124.0
yarn add @grafana/scenes@3.6.2--canary.617.8016493124.0
```
</details>
=> Auto: Updating auto

packages/scenes-app/src/demos/adhocFiltersDemo.tsx, packages/scenes/src/variables/adhoc/AdHocFilterBuilder.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
- Includes an optional `addFilterButtonText` field
- Added a tab of "vertical variants" to the adhoc filter demo page
=> feat: allow label for adhoc filter add button

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
This PR changes the grid row to group the row title and actions together so the row css `justifyContent: space-between` doesn't keep them apart.
=> Group row title and actions together on the left side

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
In the old arch, hovering over the row title area would show the actions. To achieve this we need to refactor some things around the `SceneGridRow`
<details>
<summary>📦 Published PR as canary version: <code>3.8.2--canary.625.8111759979.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.8.2--canary.625.8111759979.0
yarn add @grafana/scenes@3.8.2--canary.625.8111759979.0
```
</details>
=> Style rows to show actions on entire group hover

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
The grid row has a `isDraggable` prop that seems like it's not set anywhere. We can maybe make use of the parent layout to determine whether a row is draggable and remove that prop? Or set that one if it makes more sense. Not sure what approach is better.
<details>
<summary>📦 Published PR as canary version: <code>3.8.2--canary.626.8137562729.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.8.2--canary.626.8137562729.0
yarn add @grafana/scenes@3.8.2--canary.626.8137562729.0
```
</details>
=> Rows are draggable when scene layout is draggable

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
I noticed a bug in scenes dashboards with AnnotationDataLayer not working with data source variables, resulting in error `AnnotationsDataLayer.js:95 AnnotationsDataLayer error {message: 'Datasource ${ds} was not found'}` 
I tracked it down to an issue with scene $data, $timeRange and $variables being activated before the local (own) level activation handlers. Resulting in data layers on the top dashboard level being activated before the dashboard scene itself (that sets the window.__grafanaSceneContext without this the variable system is not working (because scopedVars with sceneObject was not passed in AnnotationsDataLayer)
Changes
* Call own local level activation handlers before calling $data, $timeRange, $variables and $behaviors activation handlers
* Pass scopedVars with context when …
=> SceneObjectBase: Call self activation handlers before child data, time range and variable handlers

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Fixes https://github.com/grafana/grafana/issues/83912 
Alternative fix (that does not restore old bug) of https://github.com/grafana/scenes/pull/633
<details>
<summary>📦 Published PR as canary version: <code>3.9.2--canary.636.8171497001.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.9.2--canary.636.8171497001.0
yarn add @grafana/scenes@3.9.2--canary.636.8171497001.0
```
</details>
=> VizPanel: Fixes issue updating field config

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
- supports a new optional prop on `AdHocFiltersVariable`: `defaultKeys` 
- these default keys are then returned by `getTagKeys`
<details>
<summary>📦 Published PR as canary version: <code>3.11.0--canary.612.8230146272.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.11.0--canary.612.8230146272.0
yarn add @grafana/scenes@3.11.0--canary.612.8230146272.0
```
</details>
=> Variables: Support static keys in AdHocFiltersVariable

packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Some migrations require panel id (like graph => timeseries migration handler that transforms time regions to annotations) 
<details>
<summary>📦 Published PR as canary version: <code>3.11.0--canary.638.8200246516.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.11.0--canary.638.8200246516.0
yarn add @grafana/scenes@3.11.0--canary.638.8200246516.0
```
</details>
=> PanelMigrations: Fixes incorrect panel.id in migration handler

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Looking at the old code in PanelQuery runner we always increment structureRev when the processed frames differ, so moved the comparison to after apply field config. 
We are still missing some streaming related optimizations in this function (that we have PanelQueryRunner). But leaving that for another future. 
<details>
<summary>📦 Published PR as canary version: <code>3.13.1--canary.643.8277858909.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.13.1--canary.643.8277858909.0
yarn add @grafana/scenes@3.13.1--canary.643.8277858909.0
```
</details>
=> VizPanel: Fixes incrementing structureRev

packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Fixed moving panels when opening a dashboard 
* Switch to CSS transforms for animation
* Add `react-grid-layout--enable-move-animations` class when isDraggable is enabled
=> SceneGridLayout: Fixes moving panels when opening dashboards

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Addresses https://github.com/grafana/grafana/pull/83157#issuecomment-1997271369
in `AdHocFilterRenderer` the selected value for that select is constructed from the filter key [here](https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx#L30). this uses the `toOption` method which just [takes the value and applies it as both the label and value](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/selectUtils.ts#L3)
this changes the behaviour when `defaultKeys` are present to find the matching option from the list of `defaultKeys`, then uses `toSelectableValue` to convert it. that way both the label and internal value are preserved correctly
=> AdHocFilter: Correctly show the label for a matching default key

packages/scenes/src/core/types.ts, packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneDataTransformer.ts
- Add transformations to annotations dataframes
- Keep compatibility with previous transformations defined as `CustomTransformOperator`, we just send them normal dataframes
Valid transformations array could now look like:
```ts
transformations: [
{
operator: () => (source: Observable<DataFrame[]>) => source.pipe(map((frames) => frames)),
topic: DataTopic.Annotations,
},
{
id: DataTransformerID.organize,
options: {
excludeByName: {},
indexByName: {},
renameByName: {},
includeByName: {},
},
topic: DataTopic.Annotations,
},
sortFramesTransformation,
addTWCFieldSeriesIndexTransformation,
addDefaultSeriesNameTransformation,
],
```
Fixes #451 
<details>
<summary>📦 Published PR as canary version: <code>3.14.0--canary.651.8356712670.0</code></summary>
<br />
:sparkles: Test out this PR locally …
=> Add transformations to annotations dataframes

packages/scenes/src/core/types.ts
A problem with the ordering of Pr merges I think created this missing import in main 
<details>
<summary>📦 Published PR as canary version: <code>3.14.1--canary.655.8371909776.0</code></summary>
<br />
```bash
npm install @grafana/scenes@3.14.1--canary.655.8371909776.0
yarn add @grafana/scenes@3.14.1--canary.655.8371909776.0
```
</details>
=> Core: Fixes type issue introduced by merge

packages/scenes/src/querying/SceneQueryRunner.ts
Fixes a bug I have discovered in core Grafana: https://github.com/grafana/grafana/issues/84818
The problem is that in the PanelEditor in core Grafana we are using the cloned version of the data provider. When it's activated, it uses data layers results (via ReplaySubject in the layer) causing the `onLayersReceived` being called. But, this function depends on SQR's private `_resultAnnotations` propert, that is not cloned given it's a instance property, not part of the object state.  Hence we are losing the query-provided annotations.
However, it's actually reflecting a state of an object as it holds annotation results that might have been part of a query response. So, it is technically SQR's state. 
There are alternatives to this approach:
1. Move `_resultAnnotations` / `_layerAnnotations` …
=> SceneQueryRunner: Meaningful cloning

packages/scenes/src/utils/ControlsLabel.tsx
There was a UX request to show an explicit info icon whenever a variable had a description.
This PR adds the icon when the description is present, and shows the tooltip when the new icon is on-hover.
The tooltip was removed from the surrounding field component and now will only appear when interacting with the new icon.
=> ControlsLabel: style: use info icons for description

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
The PR https://github.com/grafana/scenes/pull/632 made it so that we did not support the old URL value for the ALL VALUE. 
This restores the backward compatible support for "All" in URL (changed to $__alll)
<details>
<summary>📦 Published PR as canary version: <code>4.0.2--canary.656.8387068694.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.0.2--canary.656.8387068694.0
yarn add @grafana/scenes@4.0.2--canary.656.8387068694.0
```
</details>
=> MultiValueVariable: Fixes issue with initial url sync when using old All url value

packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
In some circumstances using datasource variables the target datasource is not matched with the panel datasource. This causes issues for datasources using `DataSourceWithBackend`.
This makes sure we set the target datasource to the correct datasource.
=> Check if target datasource is matching the panel ds, if not set the target ds to panel ds.

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
This fixes panel positioning glitching when drag/dropping a panel into a row.
There were 2 issues:
- Moving panels into/out of rows caused a existing parent warning
- After moving a panel into a row, when calling `toggleRow` the `firstPanelYPos` [here](https://github.com/grafana/scenes/blob/main/packages/scenes/src/components/layout/grid/SceneGridLayout.tsx#L72) would be wrongly selected because `sortChildrenByPosition` would not sort row children also, thus causing a glitch.
Fixes https://github.com/grafana/grafana/issues/83292
<details>
<summary>📦 Published PR as canary version: <code>4.1.1--canary.663.8521906375.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.1.1--canary.663.8521906375.0
yarn add …
```
=> Fix drag and drop panels in rows

packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/macros/timeMacros.test.ts, packages/scenes/src/variables/macros/timeMacros.ts
In the old architecture `$__interval` was passed to the backend as `$__interval`. With scenes this changed so that we're always adding curly braces e.g. `${__interval}`. The Influx db datasource does not handle this well. So for backwards compatibility we should probably keep the variable as is, without the braces.
<details>
<summary>📦 Published PR as canary version: <code>4.1.1--canary.666.8521778570.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.1.1--canary.666.8521778570.0
yarn add @grafana/scenes@4.1.1--canary.666.8521778570.0
```
</details>
=> Fix issue where curly braces are always added to IntervalMacro. 

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx, packages/scenes/src/components/layout/grid/utils.test.ts, packages/scenes/src/components/layout/grid/utils.ts
**Problem**
When using Grafana on a TV, the users want to have all the widgets available on the screen. However, the screen size can vary between rooms, so they mark "auto size" when playing a playlist to have the dashboard fit vertically in the screen.
When migrating to the dashboard, this feature stopped working.
**Solution**
To be able to adapt the grid to the available height, we modify the RGL cells height to make sure they don't overflow the bottom of the grid view. 
https://github.com/grafana/scenes/assets/5699976/cdc7eb00-9a9e-417e-888c-eb2edb6414bb
<details>
<summary>📦 Published PR as canary version: <code>4.2.0--canary.658.8522699461.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.2.0--canary.658.8522699461.0
yarn add …
```
=> Autofit: Fit widget in the screen depending on the height

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
The refresh picker did not have a value of `auto` hence it did not provide 100% parity with the existing functionality in core dashboards.
This PR brings that functionality back using the same mechanism that was used in the previous dashboards system.
<details>
<summary>📦 Published PR as canary version: <code>4.4.0--canary.667.8550830076.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.4.0--canary.667.8550830076.0
yarn add @grafana/scenes@4.4.0--canary.667.8550830076.0
```
</details>
=> SceneRefreshPicker: Implement mechanism for auto interval

packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
This used to be needed for the new viz tooltips, but should no longer be needed now that they're [portaled](https://github.com/grafana/grafana/pull/81986).
This also fixes an issue where panels lower down a page always appeared beneath ones above when being moved around.
See also: https://github.com/grafana/grafana/pull/85563
Closes #622 
<details>
<summary>📦 Published PR as canary version: <code>4.3.1--canary.675.8546552145.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.3.1--canary.675.8546552145.0
yarn add @grafana/scenes@4.3.1--canary.675.8546552145.0
```
</details>
=> Chore: Remove viz panel tooltip related code that is no longer needed

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
- Avoid adding default `fieldConfig` to annotations, follow what we do in grafana ([link](https://github.com/grafana/grafana/blob/2f5be54252b860925997249163b5f6c4f81acc1c/packages/grafana-data/src/field/fieldOverrides.ts#L600))
Why? When adding links to a panel like so:
```txt
fieldConfig: {
defaults: {
...
links: [
{some link}
],
},
},
```
The links were getting added not only to the series, but also to each field in the annotations, resulting in the annotation having repeated links that did not belong there.
=> VizPanel: Do not apply the visualization's field config to annotation data frames

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
https://github.com/grafana/scenes/assets/36818606/7487da9c-bc39-4992-98bc-95c96dc9c7d8
This is a different approach to https://github.com/grafana/scenes/pull/669 that fixes https://github.com/grafana/grafana/issues/83916.  
It involves saving the initial layout when a drag action starts and checks on drag stop if the state is invalid (e.g.: a row is within a row). If layout is invalid we flag it so that when `onLayoutChange` is called we load the old layout and revert to it. I'm not entirely happy with this solution but think this is the best approach for now to get this to the finish line.
- In the future, I think we can try to wrap the entire uncollapsed row with the `GridItemWrapper` to clearly highlight it for row dragging, although I'm not sure how panels dragging would work in this …
=> Disallow drag and drop rows within uncollapsed rows

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
Show the computed auto value when auto is selected.
<details>
<summary>📦 Published PR as canary version: <code>4.5.3--canary.680.8568953297.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.5.3--canary.680.8568953297.0
yarn add @grafana/scenes@4.5.3--canary.680.8568953297.0
```
</details>
=> SceneRefreshPicker: Show the auto calculated value when auto is selected

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes https://github.com/grafana/grafana/issues/84575
Fixes an issue where the DashboardDS would not get the correct data from the source panels `SceneQueryRunner._results` because the source panel `_results` buffer would be empty. This affected the dashboard DS in various scenarios but was observed consistently when creating a new dashboard.
In a new dashboard, if you would create a new panel, it's `_results` buffer in the query runner would be empty. As soon as you saved the dashboard and refreshed the page the buffer would populate and thus the DashboardDS would also work.
The problem was in `SceneQueryRunner` cloning where we now emit the data in the clone so it can be picked up by the DashboardDS.
<details>
<summary>📦 Published PR as canary version: …
=> Clone SceneQueryRunner together with _results

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts
This addresses a problem with `getTagValues` being called with queries from all runners in a scene, including inactive ones. 
This is problematic i.e. in a panel edit scenario in Grafana core. When one goes to panel edit all other panels are de-activated, but `getTagValues` for filters would still be executed with queries from runners of those inactive panels.
<details>
<summary>📦 Published PR as canary version: <code>4.5.7--canary.685.8631031033.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.5.7--canary.685.8631031033.0
yarn add @grafana/scenes@4.5.7--canary.685.8631031033.0
```
</details>
=> Filters/GroupBy: Resolve queries only from active query runners

packages/scenes/src/core/SceneComponentWrapper.tsx
This is a companion fix to https://github.com/grafana/grafana/pull/86093 to make sure bugs like that cannot happen again by fixing the issue in SceneComponentWrapper so that we never render model components before they are activated. 
<details>
<summary>📦 Published PR as canary version: <code>4.7.0--canary.692.8683393495.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.7.0--canary.692.8683393495.0
yarn add @grafana/scenes@4.7.0--canary.692.8683393495.0
```
</details>
=> SceneComponentWrapper: More robust activation

packages/scenes/src/variables/variants/LocalValueVariable.test.ts, packages/scenes/src/variables/variants/LocalValueVariable.ts
Alternative to https://github.com/grafana/grafana/pull/85934 
I think if we have to do that try catch there, might just be simpler to support this scenario in LocalValueVariable
=> LocalValueVariable: Do not throw when missing parent variable

packages/scenes/src/components/SceneRefreshPicker.tsx
Fixes problem of RefreshPicker jumping around / changing width. Same technique is used in Explore so this is using same property on RefreshPicker
=> RefreshPicker: Fixed width when going betwen normal and loading state

packages/scenes/src/variables/VariableDependencyConfig.ts
Issue reported here [Dashboard Migration: ${__all_variables} not updating their value in panels #86296](https://github.com/grafana/grafana/issues/86296)
I noticed that `$__all_variables` is not being updated when a variable changes. I lack context in this area, and this is my attempt to understand it. 
Is there a better way to fix this issue?
https://github.com/grafana/scenes/assets/239999/81570ceb-3650-44af-8339-498a3b90f4d4
=> Fix ${__all_variables} not updating their value in panels

packages/scenes/src/variables/variants/IntervalVariable.tsx
The interval variable was not correctly changing when the name was updated. This is because the url sync config option `keys` property was set statically to whatever the name was when the variable object was created. This PR changes the property to a function, so the key is looked up when `getKeys` is called
=> Interval variable: Make interval variable properly update on name change

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts, packages/scenes/src/variables/types.ts, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts, packages/scenes/src/variables/variants/TestVariable.tsx
i think this does what we want, but leaving as draft for now to check the approach before adding tests etc
what this does:
- takes the rendering logic from `VariableValueSelectMulti`
- enhances with `isFetchingOptions` and `isOptionsOpen` logic controlled by `onOpenMenu`/`onCloseMenu`
- fetches and waits for new options when opening the menu via `model.validateAndUpdate()`
some questions:
- does this logic only apply to group by, or would we want it for any multi value variable?
- if so, could move this new logic back into `VariableValueSelectMulti` 🤔 
Fixes #686 
<details>
<summary>📦 Published PR as canary version: <code>4.11.2--canary.687.8737546972.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.11.2--canary.687.8737546972.0
yarn …
```
=> GroupBy: Fetch options when opening menu

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFilterValue.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
Ensures we find the selected option from the list and get the full key/value object instead of creating a new object from just the key
<details>
<summary>📦 Published PR as canary version: <code>4.11.3--canary.690.8783271240.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.11.3--canary.690.8783271240.0
yarn add @grafana/scenes@4.11.3--canary.690.8783271240.0
```
</details>
=> AdhocFilters: Show label for selected key

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Trying to fix https://github.com/grafana/grafana/issues/86554 
Also changing / skipping using instanceState for legacyPanelId as this is a bit problematic as this state is really reserved to only be used by the panel plugin so for Grafana to use it causes issues (we have to make sure we preserve legacyPanelId when we handle onInstanceStateChange. 
I am tempted to just add legacyPanelId to VizPanel state (instead of parsing it from key) but not sure. 
<details>
<summary>📦 Published PR as canary version: <code>4.12.0--canary.702.8784713837.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.12.0--canary.702.8784713837.0
yarn add @grafana/scenes@4.12.0--canary.702.8784713837.0
```
</details>
=> VizPanel: Fixes issue updating instanceState

packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
Show group menus correctly in scenes dashboards.
Fixes https://github.com/grafana/grafana/issues/84807
<details>
<summary>📦 Published PR as canary version: <code>4.12.1--canary.704.8799450327.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.12.1--canary.704.8799450327.0
yarn add @grafana/scenes@4.12.1--canary.704.8799450327.0
```
</details>
=> Fix how the submenus appear for menus of type group

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Part of the fix for https://github.com/grafana/grafana/issues/86420 and relates panel time range issues. 
This fixes the problem where SceneQueryRunner was detecting a change to it's scoped time range
=> SceneQueryRunner: Support detecting new local time range

packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.ts
This adds the same functionality as is present in Grafana's `TemplateSrv`,
allowing users to pass an array as the fifth argument to `interpolate` and
have it populated with `VariableInterpolation`s indicating whether the
variable was found and containing some details about the match.
=> sceneGraph: handle interpolations argument in interpolate

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Fixes https://github.com/grafana/grafana/issues/87167 
A previous fix for this https://github.com/grafana/scenes/pull/656 only added a unit test for the scenario where includeAll and isMulti was false (so not truly multi value). when isMulti is true the URL value is an array and so the comparison that checked for the old legacy ALL URL value did not pass as the urlValue was an array with "All" 
<details>
<summary>📦 Published PR as canary version: <code>4.13.2--canary.712.8910747975.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.13.2--canary.712.8910747975.0
yarn add @grafana/scenes@4.13.2--canary.712.8910747975.0
```
</details>
=> MultiValueVariable: Fixes support for legacy All url value

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Instead of using queries by default to filter the options for the `AdHocFiltersVariable`, make it an opt-in option.
Adds `useQueriesAsFilterForOptions` to state definition.
Notes:
- When updating grafana to use this new version, we need to ensure that the dashboards opt-in
- https://github.com/grafana/grafana/pull/87244 
Related:
- https://github.com/grafana/grafana/pull/85674
- https://github.com/grafana/scenes/pull/685
=> AdHocFiltersVariable: create an opt-in state variable for using queries to filter the options

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Closes https://github.com/grafana/hyperion-planning/issues/38
Before:
After:
<details>
<summary>📦 Published PR as canary version: <code>4.13.3--canary.715.8927266597.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.13.3--canary.715.8927266597.0
yarn add @grafana/scenes@4.13.3--canary.715.8927266597.0
```
</details>
=> Allow filter selectors to wrap

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
- adds the `allowCreateWhileLoading` option to the value select
- adjusts when `isValuesOpen` is set to true to be as soon as the `onClick` is fired. otherwise the menu will reopen once the options finally resolve even if you've already selected and added a custom value
Fixes https://github.com/grafana/hyperion-planning/issues/23
<details>
<summary>📦 Published PR as canary version: <code>4.14.2--canary.721.8986239090.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.14.2--canary.721.8986239090.0
yarn add @grafana/scenes@4.14.2--canary.721.8986239090.0
```
</details>
=> AdHoc filters: Allow adding custom value while loading

packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneDataTransformer.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes an issue in SceneDataTransformer where it would emit untransformed series when annotations where present. 
Because the two transformation observables where done in parallel the annotations one can complete before the series one and this cause the untransformed series data to be emitted. 
Now I wait for both series + annotation transforms to be completed before emitting anything, this also greatly reduces state updates. 
Also an unrelated change in SceneQueryRunner that is most just a cleaner logic change  
<details>
<summary>📦 Published PR as canary version: <code>4.15.0--canary.720.8986092576.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.15.0--canary.720.8986092576.0
yarn add @grafana/scenes@4.15.0--canary.720.8986092576.0 …
```
=> SceneDataTransformer: Fixes transformer emitting untransformed series

packages/scenes/src/core/PanelBuilders/index.ts, packages/scenes/src/index.ts
I wanted to use `FieldConfigOverridesBuilder` but that type/class is not exported. I didn't see any obvious reason to not export it.
=> Types: Export `FieldConfigOverridesBuilder`

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
- changes `keySelect` to set `isKeysOpen` synchronously as soon as the `onOpenMenu`/`onCloseMenu` callbacks are called
- if this is set asynchronously once the options are resolved, can potentially cause issues with slow connections. example:
- throttle connection to slooooooow
- take a configured filter (with key + value)
- open the key dropdown
- click outside to close the key dropdown
- open the value dropdown
- click outside to close the value dropdown
- wait for everything to resolve
- expected: dropdowns remain closed
- (haven't tested this, but) i think actually both dropdowns will be open, which shouldn't be possible and could cause any manner of issues
Fixes https://github.com/grafana/hyperion-planning/issues/28
<details>
<summary>📦 Published PR as canary version: …
=> AdHoc filters: Apply `isKeysOpen` state changes synchronously

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
- passes a custom `isValidNewOption` function to the valueSelect
- allows any non-zero-length string as a valid option
- this prevents showing a `No options found` message when entering the same custom value as was initially present
- adds a unit test to prevent regressions 
Fixes https://github.com/grafana/hyperion-planning/issues/25
<details>
<summary>📦 Published PR as canary version: <code>4.17.2--canary.723.8999827741.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.17.2--canary.723.8999827741.0
yarn add @grafana/scenes@4.17.2--canary.723.8999827741.0
```
</details>
=> AdHoc filters: Allow typing the same custom value

packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/utils/test/utils.tsx
Fixes an annoying issue where a multi-value variable would trigger a cascading update even when the value did not change, for example when just opening the variable multi select and closing it without changing anything
=> Variables: Do not update value when value and text are the same

packages/scenes/src/querying/SceneDataTransformer.test.ts, packages/scenes/src/querying/SceneDataTransformer.ts
Fixes #717 
<details>
<summary>📦 Published PR as canary version: <code>4.18.0--canary.725.9002029358.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.18.0--canary.725.9002029358.0
yarn add @grafana/scenes@4.18.0--canary.725.9002029358.0
```
</details>
=> SceneDataTransformer: Performance optimizations

packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Noticed panels moving about when coming back to dashboard from dashboard settings and sometimes from panel edit. 
This fixes that problem, I am using a ref here and updating the class using dom classList to avoid having to always re-render the full grid after mount
=> SceneGridLayout: Prevent panels from moving on mount

packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts, packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts, packages/scenes/src/variables/utils.ts
This PR syncs labels of the values in the group by variable similarly to what we introduced for ad-hoc filters.
Unlike ad-hoc filters, group by is a little bit more of a special case hence the reason why some of the changes below. The solution might not be optimal, so please feel free to suggested changes and improvements.
Changes:
- introduced custom URL sync handler
- it works similarly to the ad-hoc filters one
- this is needed as currently we use the one multi-value variable one and we don't want this changed for all variables
- the state of group by variable received a new prop: `urlOptions` where we store the options that we received via the URL
- when fetching the options, we concat the `urlOptions` with what we receive from the datasource (or with the `defaultOptions`)
- this is …
=> GroupByVariable: Sync label to URL

packages/scenes/src/components/NestedScene.tsx
- removes `cursor: pointer;` from the `NestedScene` wrapper
- might be missing something, but i don't think this is necessary
- most obvious place to spot the problems this causes is the [alerting landing page in ops](https://ops.grafana-ops.net/alerting)
- everything under `Insights` shows a pointer cursor 🤯 
- this means it can look like something is clickable when it's not (e.g. try clicking in the gap to the right of `Grafana-managed alert rules`)
=> NestedScene: Don't show `cursor: pointer;` for everything

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
Part of row repeat fixes https://github.com/grafana/grafana/pull/87539
So we have this problem in row repeats that when the variable changes (that you repeat by). All the panel query runners inside all the repeated rows were notified that their variable dependency changed and started issuing a new queries (even when their local value did not change) . 
So figured that this notification (via variableDependency) should not happen if there is a local SceneVariableSet with a local variable of the same name. 
Created a test case for this scenario all is fine. This logic make sense, the variable has not changed for the local scope (as there is a local variable with the same name that has not changed).
The only really hard puzzle piece to solve is that his completely breaks the RowRepeatBehavior …
=> SceneVariableSet: Do not propagate variable value changes when a local variable has the same name

packages/scenes/src/variables/groupby/GroupByVariable.tsx
Custom options do not make sense in the group by variable which is supposed to provide source of aggregations based on the data source provided dimensions.
Ref https://github.com/grafana/hyperion-planning/issues/46
=> Group by: Do not allow custom options

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Ran across this if statement in the old variable system a few weeks ago, https://github.com/grafana/grafana/blob/main/public/app/features/variables/state/actions.ts#L423 , I have had it on my todo to fix this in the new variable system. 
The condition fixes this issue https://github.com/grafana/grafana/issues/28635 
It's for variables with custom all value, when we interpolate a datalink with `${varName}` we do not use the URL state for all value (`$__all`) as we do not really know if the link is targeting Grafana or an external system, so that will always interpolate to the real value, so if the value is `All` then it would be all values or if a custom value is defined (say `.*`) the URL value will be `.*` . 
This new code (condition) will translate the URL value back to our meta All …
=> MultiValueVariable: Fixes setting value from url when url value is a custom all value

packages/scenes/src/variables/components/VariableValueSelect.tsx
Add missing `data-testid` in variable value select
<details>
<summary>📦 Published PR as canary version: <code>4.23.1--canary.742.9178393475.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.23.1--canary.742.9178393475.0
yarn add @grafana/scenes@4.23.1--canary.742.9178393475.0
```
</details>
=> VariableValueSelect: Add missing data-testids for e2e

packages/scenes/src/components/layout/SceneFlexLayout.tsx
Discovered that the `SceneFlexLayout` component was not respecting the `minWidth` and `minHeight` options if it doesn't have a parent, this pr fixes so that they are applied without having to have a parent.
The reason why it works when there is a parent is that `applyItemStyles` function is called with both the own `state` and `parentState` and there the `minWidth` and `minHeight` options are applied.
=> SceneFlexLayout: Min width/height option was ignored

packages/scenes/src/components/SceneRefreshPicker.tsx
When `autoOption` is undefined, the error prevents some of the demos from displaying.
Moved the fix out of:
- https://github.com/grafana/scenes/pull/744/files#r1611931529
so it can be merged earlier.
=> fix: undefined check on RefreshPicker.autoOption

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
We should be able to drag and drop rows across the dashboard if we are not dragging a row within another row. If we try to drag and drop a row after an uncollapsed row and all its panels, this should be a valid state.
Currently if we drop a row after an uncollapsed row it will become a child of that row, since we do not properly delimit between dropping an item in or outside the area of an uncollapsed row.
This PR changes that and checks whether the dragged row is dropped after all the previous rows children, in which case it will assume the layout as parent and allow the drop. If the row is dragged and dropped in between children of another row, it's parent will be considered the row that holds the children, this being an invalid state. We cannot have rows within rows. …
=> Allow drag and dropping rows in valid states

packages/scenes/src/components/VizPanel/seriesVisibilityConfigFactory.test.ts, packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Adds logic for a special case when current value is the ALL_VALUE but the variable has not enabled all value, in this case we should just pick the first option. 
Refactored the validation function a bit so we can simplify the long nested if/else statements and leverage early return pattern instead. 
Fixes https://github.com/grafana/grafana/issues/88391
<details>
<summary>📦 Published PR as canary version: <code>4.24.2--canary.757.9283024412.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.24.2--canary.757.9283024412.0
yarn add @grafana/scenes@4.24.2--canary.757.9283024412.0
```
</details>
=> MultiValueVariable: Fixes issue when value is all value but all value is not enabled

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
When the value of the adhoc filter gets long, you can't see the key and operator, which are arguably more important than showing a few more characters of the already truncated value.
Before: 
After:
Fixes: https://github.com/grafana/grafana/issues/88328
=> Variables: Prioritize showing adhoc variable key and operator

packages/scenes/src/variables/macros/timeMacros.test.ts, packages/scenes/src/variables/macros/timeMacros.ts
A bug was reported when resolving `$__timezone` in scenes compared with the behavior in Grafana Dashboards.
[In Grafana Dashboards, when the browser timezone is selected, the value of the timezone is resolved](https://github.com/grafana/grafana/blob/main/public/app/features/templating/macroRegistry.ts#L32). For scenes, the value returned is `browser`. This breaks some data sources queries when they use `$__timezone`.
|Before|After|
|-|-|
In Grafana, to get the browser timezone is done through `moment`. `moment` is not a dependency of Scenes and is not needed, so we're using `Intl`.
<details>
<summary>📦 Published PR as canary version: <code>4.24.3--canary.759.9299159504.0</code></summary>
<br />
```bash
npm install …
```
=> Macros: Resolve browser timezone for `$__timezone`

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Addresses this issue https://github.com/grafana/grafana/issues/47005#issuecomment-2089912829
Related PR in the Grafana repo: https://github.com/grafana/grafana/pull/87317
Is this a good place to add this? Also, are there some drawbacks that may cause performance issues?
<details>
<summary>📦 Published PR as canary version: <code>4.24.4--canary.716.9299472214.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.24.4--canary.716.9299472214.0
yarn add @grafana/scenes@4.24.4--canary.716.9299472214.0
```
</details>
=> VizPanelRenderer: Emit SetPanelAttention event

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
- adds support for `group` in `MetricFindValue` interface by collecting options by group before passing to `<Select>`
- adds unit test to check behaviour is working
For https://github.com/grafana/hyperion-planning/issues/33
<details>
<summary>📦 Published PR as canary version: <code>4.25.0--canary.758.9305474511.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.25.0--canary.758.9305474511.0
yarn add @grafana/scenes@4.25.0--canary.758.9305474511.0
```
</details>
=> AdHoc filters: Add support for adhoc filter value groups

packages/scenes/src/core/sceneGraph/index.ts, packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts
Additional functions on sceneGraph to search for a single scene object by its key (and optionally to check it matches a specific type).
Based on feedback here:
- https://github.com/grafana/scenes/pull/744#discussion_r1612215386
Please check the suitability of the labels.
<details>
<summary>📦 Published PR as canary version: <code>4.25.0--canary.753.9269482662.0</code></summary>
<br />
```bash
npm install @grafana/scenes@4.25.0--canary.753.9269482662.0
yarn add @grafana/scenes@4.25.0--canary.753.9269482662.0
```
</details>
=> feat: sceneGraph.findByKey(AndType)

packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx
Merges into https://github.com/grafana/scenes/pull/763
Adds the behavior to preserve custom value input value when opening the Select after adding a custom value. 
With this change we can completely revert https://github.com/grafana/grafana/pull/87843   (and do not need https://github.com/grafana/grafana/pull/88601)
=> Now works with custom value preserved

packages/scenes-app/src/demos/variables.tsx, packages/scenes/package.json, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/components/getOptionSearcher.test.ts, packages/scenes/src/variables/components/getOptionSearcher.ts, packages/scenes/src/variables/groupby/GroupByVariable.tsx, yarn.lock
The search / typing performance is terrible for the core Select component when we get over 10K items (with 100K options we are talking 1-3 seconds per keystroke).  
In this PR 
* I am moving the option filtering to be outside the Select component, and limiting the options we pass to the Select component to 10K.  
* Using uFuzzy for the actual filtering. 
* Adding a new demo to test a variable with many options 
* in order to properly memoize the uFuzzy instance, allOptions, haystack etc I created a new function called getOptionSearcher which replaces some of the logic we had in getOptionsForSelect. Added the same tests we have for getOptionsForSelect to the getOptionSearcher (plus a search test). The GroupBy variable is still using getOptionsForSelect (and I think it might be used by …
=> Variables: Search / typing performance improvements

package.json, yarn.lock
To match the version we have in all the packages, and to work
with lerna v6.
<details>
<summary>📦 Published PR as canary version: <code>4.26.1--canary.771.9386870862.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@4.26.1--canary.771.9386870862.0
npm install @grafana/scenes@4.26.1--canary.771.9386870862.0
yarn add @grafana/scenes-react@4.26.1--canary.771.9386870862.0
yarn add @grafana/scenes@4.26.1--canary.771.9386870862.0
```
</details>
=> fix: downgrade workspace prettier to 2.5.1

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
When a scene loads and VizPanels with variable dependencies are waiting to load, there's no indication that the panel will eventually load.
This PR sets the state of the PanelData to loading when we're waiting for the variable dependencies.
Fixes: https://github.com/grafana/grafana/issues/84574
One could argue that setting the LoadingState to "NotStarted" or introducing a new state called "WaitingForDependency" would make more sense. But it would also introduce a lot more changes to grafana as a whole.
Before (notice the loading indicator on the panel chrome is not running before the variable is loaded):
After:
=> SceneQueryRunner: Act as if we're loading when waiting for variables to load.

packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.ts
Fixes #773
<details>
<summary>📦 Published PR as canary version: <code>4.26.2--canary.774.9388258294.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@4.26.2--canary.774.9388258294.0
npm install @grafana/scenes@4.26.2--canary.774.9388258294.0
yarn add @grafana/scenes-react@4.26.2--canary.774.9388258294.0
yarn add @grafana/scenes@4.26.2--canary.774.9388258294.0
```
</details>
=> Variables: Support variable expressions inside custom values

packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/components/getOptionSearcher.test.ts, packages/scenes/src/variables/components/getOptionSearcher.ts, packages/scenes/src/variables/groupby/GroupByVariable.tsx
- marks variable value select `virtualized`
- makes the options and input state controlled outside of select for better performance
- extension of https://github.com/grafana/scenes/pull/763 for adhoc filters
- also means we can revert https://github.com/grafana/grafana/pull/87843 as this is cleaner 
- adds a demo page
<details>
<summary>📦 Published PR as canary version: <code>4.27.0--canary.766.9398430196.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@4.27.0--canary.766.9398430196.0
npm install @grafana/scenes@4.27.0--canary.766.9398430196.0
yarn add @grafana/scenes-react@4.27.0--canary.766.9398430196.0
yarn add @grafana/scenes@4.27.0--canary.766.9398430196.0
```
</details>
=> AdHocFiltersVariable: Performance improvements

packages/scenes/src/variables/components/VariableValueControl.tsx, packages/scenes/src/variables/components/VariableValueSelectors.tsx
when using the `VariableValueControl` there is not an option to hide the label in the variable value controller, this change provides an option to work alongside the variable-level hide config so users can hide the filters in the main control bar, and also hide the label in the places where the variable value controller is used.
=> provide an option to hide the label from the variable value controller

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
Fixes https://github.com/grafana/scenes/issues/739 
[Graphite has this old condition](https://github.com/grafana/grafana/blob/c6720f1c063d89da53751fd636e16264142d7d49/public/app/plugins/datasource/graphite/datasource.ts#L242C3-L244C6)
```ts
if (options.panelId) {
httpOptions.requestId = this.name + '.panelId.' + options.panelId;
}
```
which is causing duplicate requestId (and hence cancelled requests).
Think it should be fine to leave this undefined (it's optional in the type at least) 
<details>
<summary>📦 Published PR as canary version: <code>4.27.0--canary.776.9400928706.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@4.27.0--canary.776.9400928706.0
npm install @grafana/scenes@4.27.0--canary.776.9400928706.0
yarn add …
```
=> SceneQueryRunner: Do not set panelId by default

packages/scenes/src/components/SceneRefreshPicker.tsx
Fixes a minor issue with `refresh=` url state appearing in `scenes-react` demos, there is was a mismatch URL state and updateFromUrl
It's a bit messy, the "off state" for auto refresh is represented by an empty string (both in internal design system RefreshPicker and in state), so leaving it like that as changing that could be messy
=> SceneRefreshPicker: Fixes url state issue

packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.ts, packages/scenes/src/variables/macros/index.ts
Fixes issues interpolating a string like `"$toString"` , if there is no variable named `toString` this should leave the original string unchanged but due to using object property lookup we matched object prototype functions (Both on scopedVars and macros) 
<details>
<summary>📦 Published PR as canary version: <code>4.30.0--canary.785.9463381206.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@4.30.0--canary.785.9463381206.0
npm install @grafana/scenes@4.30.0--canary.785.9463381206.0
yarn add @grafana/scenes-react@4.30.0--canary.785.9463381206.0
yarn add @grafana/scenes@4.30.0--canary.785.9463381206.0
```
</details>
=> Variables: Fixes sceneInterpolator when string contains variables with object prototype function names

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
This PR adds operator in vertical mode for ad hoc filters.
=> AdHocFiltersVariable: Show operator in vertical mode

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
If `this.state.data` is undefined. We're going to create the object  `{ state: LoadingState.Loading }` because we're spreading undefined.
We can instead spread `emptyPanelData` and set data to a valid object.
=> SceneQueryRunner: When waiting for a variable to load, and PanelData is undefined, we should create a valid PanelData object.

packages/scenes/package.json, packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/services/UrlSyncManager.ts, packages/scenes/src/services/utils.ts, yarn.lock
Fixes issue with recent url change. 
When URL sync root was not the scene root (which is the case for data trails for now, might change it later). 
This fixes the state update from URL logic so that the URL sync root is also synced even when it has a parent. 
<details>
<summary>📦 Published PR as canary version: <code>5.0.1--canary.793.9496367270.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.0.1--canary.793.9496367270.0
npm install @grafana/scenes@5.0.1--canary.793.9496367270.0
yarn add @grafana/scenes-react@5.0.1--canary.793.9496367270.0
yarn add @grafana/scenes@5.0.1--canary.793.9496367270.0
```
</details>
=> UrlSync: Fixes issue with recent url sync change

packages/scenes/src/services/UrlSyncManager.ts
Missed to remove these log lines in prev merged PR 
<details>
<summary>📦 Published PR as canary version: <code>5.0.2--canary.794.9497058323.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.0.2--canary.794.9497058323.0
npm install @grafana/scenes@5.0.2--canary.794.9497058323.0
yarn add @grafana/scenes-react@5.0.2--canary.794.9497058323.0
yarn add @grafana/scenes@5.0.2--canary.794.9497058323.0
```
</details>
=> UrlSync: Remove console.log left in prev PR

packages/scenes/src/querying/layers/SceneDataLayerBase.test.ts, packages/scenes/src/querying/layers/SceneDataLayerBase.ts
Currently in core Grafana annotations queries will be issued when entering the dashboard no matterif the layer is enabled or not.
<details>
<summary>📦 Published PR as canary version: <code>5.0.3--canary.795.9498844134.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.0.3--canary.795.9498844134.0
npm install @grafana/scenes@5.0.3--canary.795.9498844134.0
yarn add @grafana/scenes-react@5.0.3--canary.795.9498844134.0
yarn add @grafana/scenes@5.0.3--canary.795.9498844134.0
```
</details>
=> Data layers: Don't run layer on activation if disabled

packages/scenes-app/src/demos/interopDemo.tsx, packages/scenes-react/src/index.ts, packages/scenes-react/src/interoperability/EmbeddedSceneWithContext.tsx, packages/scenes/src/components/EmbeddedScene.tsx
Use case 
* To help migration 
* To support mixing both forms 
Example: 
```tsx
export function getInteropDemo(defaults: SceneAppPageState) {
return new SceneAppPage({
...defaults,
subTitle: 'Testing using the hooks and plain react components from normal scene',
getScene: () => {
return new EmbeddedSceneWithContext({
...getEmbeddedSceneDefaults(),
key: 'Flex layout embedded scene',
body: new SceneFlexLayout({
direction: 'column',
children: [
new SceneFlexItem({
body: new VizPanel({
title: 'Graph',
pluginId: 'timeseries',
$data: getQueryRunnerWithRandomWalkQuery({}),
}),
}),
new SceneFlexItem({
body: new CustomSceneObject({}),
}),
],
}),
});
},
});
}
class CustomSceneObject extends SceneObjectBase<SceneObjectState> {
static Component = ({ model }: SceneComponentProps<CustomSceneObject>) => …
```
=> ScenesReact: Use new react components and hooks from inside existing EmbeddedScenes 

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/utils.ts
Sets variable error state if getTagKeys/getTagValues returns an error.
Lots of `@ts-expect-error` since `11.1.x` isn't out yet 😬 
<details>
<summary>📦 Published PR as canary version: <code>5.1.0--canary.790.9497828604.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.1.0--canary.790.9497828604.0
npm install @grafana/scenes@5.1.0--canary.790.9497828604.0
yarn add @grafana/scenes-react@5.1.0--canary.790.9497828604.0
yarn add @grafana/scenes@5.1.0--canary.790.9497828604.0
```
</details>
=> Add support for new getTagKeys/getTagValues interface

packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.ts
If a transformation passes a number down to the `sceneInterpolator` this will throw an error in the panel.
This fixes the crash by assuring only strings gets interpolated.
=> Scenes: Return value if not string in interpolator

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts
Fixes [#89270](https://github.com/grafana/grafana/issues/89270)
**Problem**
[_.mergeWith](https://lodash.info/doc/mergeWith) ignores `undefined` values from the source object. When clearing a `VizPanel` option, we set it to `undefined` so it was not working.
To be able to set an option as `undefined`, we have to treat that case in the customizer cb passed to `_.mergeWith`.
|Before|After|
|-|-|
<video src="https://github.com/grafana/scenes/assets/5699976/76ba9bfb-c0e7-4068-9394-bff9a3bafd14"></video>|<video src="https://github.com/grafana/scenes/assets/5699976/f5654061-c535-439c-a960-32732a3c140d"></video>
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.801.9610977729.0</code></summary>
<br />
```bash
npm install …
```
=> VizPanel: Clear options value when the option is undefined

packages/scenes/src/components/SceneTimePicker.test.tsx, packages/scenes/src/components/SceneTimePicker.tsx
Adds a new method, `toAbsolute` to the SceneTimePicker.
This is to help fix an issue where the `t a` shortcut to change the time range to an absolute time range does not work in the scenes architecture. A follow-up PR in the main Grafana repo will be made when this one is merged.
<details>
<summary>📦 Published PR as canary version: <code>5.2.0--canary.800.9594766304.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.2.0--canary.800.9594766304.0
npm install @grafana/scenes@5.2.0--canary.800.9594766304.0
yarn add @grafana/scenes-react@5.2.0--canary.800.9594766304.0
yarn add @grafana/scenes@5.2.0--canary.800.9594766304.0
```
</details>
=> Add `toAbsolute` method to SceneTimePicker

packages/scenes/src/components/SceneTimeRangeCompare.tsx, packages/scenes/src/querying/ExtraQueryProvider.ts, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
:wave: 
We found an issue in app o11y where changing time window comparison value causes query runner to re-run queries even if all queries have opted out of TWC. This causes unnecessary querying and side effects for us.
This PR fixes makes twc not trigger re-run if all queries are opted-out
Thanks!
=> TimeRangeCompare: Do not re-run queries if all have opted out of comparison

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
When changing panel type (plugin), each plugin has a specific field config that must override the ones selected by the user. This is mostly the color strategy.
In Grafana Dashboards, when changing the plugin type, the new options are computed by `VizPanel` manager but it always passes the `isPluginChanged` to `false`. 
This PR enables the option to recompute the options taking into account that the plugin has changed.
=> VizPanel: Allow to adapt color palette after plugin change

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Follow up on #805 
Fixes #89836
**Problem**
[`getPanelOptionsWithDefaults`](https://github.com/grafana/grafana/blob/0285278cfc5cf8e9780f7a0624a5f1c8c6e75590/packages/grafana-data/src/panel/getPanelOptionsWithDefaults.ts#L34) generates the default options for a given plugin. The third parameter allow to override color strategy default for the given options.
In Dashboards, when creating a VizPanel, we need to get the preferred plugin color strategy. If we pass the `isAfterPluginChange` to false when creating the `VizPanel`, the new options won't include the color strategy adapted to the just loaded panel. This creates the issue of always having 'classic-palette' as the default color.
**Solution**
When loading a plugin, always mark the `isAfterPluginChange` to `true` to load the color …
=> VizPanel: Load plugin prefered default options when activating

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts
This PR adds interpolation to the query options interval in the SceneQueryRunner.
=> Fix variable interpolation in query options interval

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Reverts grafana/scenes#806
This caused issues when viewing panels. It is discarding initial color mode options.
<details>
<summary>📦 Published PR as canary version: <code>5.3.4--canary.812.9764438508.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.3.4--canary.812.9764438508.0
npm install @grafana/scenes@5.3.4--canary.812.9764438508.0
yarn add @grafana/scenes-react@5.3.4--canary.812.9764438508.0
yarn add @grafana/scenes@5.3.4--canary.812.9764438508.0
```
</details>
=> Revert "VizPanel: Load plugin prefered default options when activating"

packages/scenes/src/components/SceneRefreshPicker.tsx
This reverts commit 54ff3dcbd885a95a0b20dd42152861f91a7e4281.
Reverts https://github.com/grafana/scenes/pull/784 that caused the initially provided refresh picker state to be reset because the lack of refresh query param would make the state fall back to default. That PR introduced a regression in core Dashboards - basically the preserved refresh starte was not respected anymore.
I think we need to handle OFF refresh as `null` or `undefined` rather than `''` to allow easier differentiation here, but for now I decide to revert it as it only affects scenes-react (WIP).
This is a part of an escalation fix: https://github.com/grafana/support-escalations/issues/11235
<details>
<summary>📦 Published PR as canary version: <code>5.3.5--canary.814.9776702793.0</code></summary>
<br />
:sparkles: …
=> Revert "SceneRefreshPicker: Fixes url state issue (#784)"

packages/scenes/jest.config.ts, packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.test.ts, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts, packages/scenes/utils/test/__mocks__/style.ts
- fixes the display of groups in adhoc filters
- we initially regressed this with https://github.com/grafana/scenes/pull/766
- this PR does a couple of things:
- creates a separate `getAdhocOptionSearcher` instead of trying to reuse the generic `getOptionSearcher` which is typed for `VariableOptions`
- ~will add some tests for this as well~ ✅ 
- moves the `handleOptionGroups` logic to `AdHocFilterRenderer`
- so the flow is something like:
- opening the option menu calls `model._getValuesFor`
- this in turn calls `ds.getTagValues`, which returns a `MetricFindValue[]` array containing an optional group parameter
- `_getValuesFor` then maps this to `SelectableValue[]` but keeps the group parameter
- this is set in state as `values` in `AdHocFilterRenderer`
- `AdHocFilterRenderer` then uses …
=> Adhoc filters: Fix regression with displaying groups

packages/scenes-app/src/demos/cssGridLayoutDemo.tsx, packages/scenes/src/components/layout/CSSGrid/SceneCSSGridLayout.tsx, packages/scenes/src/components/layout/LazyLoader.tsx
When using a `SceneCSSGridLayout`, the `isLazy` property and items setting their `isHidden` property dynamically, the `LazyLoader` would still be visible.
This PR just subscribes to the item's state and also hides the `LazyLoader`.
<details>
<summary>📦 Published PR as canary version: <code>5.3.8--canary.823.9872224365.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.3.8--canary.823.9872224365.0
npm install @grafana/scenes@5.3.8--canary.823.9872224365.0
yarn add @grafana/scenes-react@5.3.8--canary.823.9872224365.0
yarn add @grafana/scenes@5.3.8--canary.823.9872224365.0
```
</details>
=> LazyLoader: Hide wrapper if child is hidden 

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Fixes inconsistencies with setting panel attention from mouse movements. Requires [#90435](https://github.com/grafana/grafana/pull/90435) to be merged. I had some troubles testing it locally, as the keybindings didn't seem to work. Maybe my Scenes setup it a bit off?
=> VizPanelRenderer: Set attention with onMouseEnter

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Adds variable dependency config to SceneGridRow, fixing an issue where the row title wasn't updated when the variable option was changed.
=> Add variable dependency config to SceneGridRow

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/types.ts, packages/scenes/src/variables/utils.ts
- supports displaying groups in adhoc filter keys 
- supports displaying groups in groupby
- adds (skipped) unit tests for both
- can't enable the tests until the repo moves to use `@grafana/ui@11.1.0` 
<details>
<summary>📦 Published PR as canary version: <code>5.4.0--canary.816.9794480649.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.4.0--canary.816.9794480649.0
npm install @grafana/scenes@5.4.0--canary.816.9794480649.0
yarn add @grafana/scenes-react@5.4.0--canary.816.9794480649.0
yarn add @grafana/scenes@5.4.0--canary.816.9794480649.0
```
</details>
=> Adhoc filters/Group by: Support groups

packages/scenes/src/components/layout/LazyLoader.tsx
Not a big sample size, but I saw this error in our app logs:
https://ops.grafana-ops.net/a/grafana-lokiexplore-app/explore/service/Hosted%20Grafana%20-%20Prod/logs?patterns=%5B%5D&var-fields=&var-ds=grafanacloud-logs&var-filters=service_name%7C%3D%7CHosted%20Grafana%20-%20Prod&var-filters=kind%7C%3D%7Cexception&var-patterns=&var-lineFilter=%7C~%20%60%28%3Fi%29kl%5C.callbacks%5C%5Bt%5C.target%5C.id%5C%5D%20is%20not%20a%20function%60&var-logsFormat=%20%7C%20logfmt&urlColumns=%5B%5D&visualizationType=%22logs%22&var-labelBy=$__all&var-fieldBy=page_url&from=now-12h&to=now&timezone=browser
Basically trying to call an inexistent callback. By assumption is that it is a race condition, where the callback is deleted before the `IntersectionObserver` stopped observing. Thus, moving the deletion of …
=> fix(lazyloader): fix trying to run inexistent callbacks

packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
**Problem**
The default it was an empty object. In Grafana this was defaulted to an empty string and this is creating compatibility issues.
**Solution**
Setting empty string to the state should solve the problem
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.837.9977135077.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.4.1--canary.837.9977135077.0
npm install @grafana/scenes@5.4.1--canary.837.9977135077.0
yarn add @grafana/scenes-react@5.4.1--canary.837.9977135077.0
yarn add @grafana/scenes@5.4.1--canary.837.9977135077.0
```
</details>
=> QueryVariable: Query is empty string by default

packages/scenes-app/src/demos/dynamicPanelOptions.tsx, packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
This PR moves panel plugin logic from grafana, from `VizPanelManager` (related [PR](https://github.com/grafana/grafana/pull/90535) ) into the `VizPanel`. This is needed because the `VizPanel` is aware of when the plugin is updated and we need the new plugin to fetch default configs, to be able to merge existing options/fieldConfigs, if they exist, with default ones.
This also changes things a bit in the sense that we no longed create a new `VizPanel` but reuse the existing one by updating it's state with the updated options/fieldConfigs. In the `changePluginType` function we receive overwrite options and fieldConfigs which represent, in the context of core Grafana, configs that are cached when switching panels in panel edit. These configurations, if present, are passed to the VizPanel to …
=> Scenes: Move change panel plugin logic in VizPanel

packages/scenes/src/utils/SafeSerializableSceneObject.test.ts, packages/scenes/src/utils/SafeSerializableSceneObject.ts
This PR fixes an issue that may occur when the data source that interpolates queries uses `cloneDeep` to clone the provided query request. For example:
https://github.com/grafana/athena-datasource/blob/v2.17.1/src/datasource.ts#L104
https://github.com/grafana/grafana/blob/v11.1.2/public/app/plugins/datasource/cloudwatch/datasource.ts#L88
When such an object is cloned the previously unbound `SafeSerializableSceneObject.valueOf` would change `this` context that would point to the newly (cloned) created instance. This creates an issue with the code generated by typescript when using private properties (#). The diff of the compiled code can be observed here:
https://www.diffchecker.com/WLJEvKvj/
The `cloneDeep` _will not call_ the cloned object constructor - this means that the originally …
=> SafeSerializableSceneObject: Make sure valueOf is bound to the instance

packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Needed for https://github.com/grafana/grafana/pull/91139
<details>
<summary>📦 Published PR as canary version: <code>5.7.0--canary.849.10147076284.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.7.0--canary.849.10147076284.0
npm install @grafana/scenes@5.7.0--canary.849.10147076284.0
yarn add @grafana/scenes-react@5.7.0--canary.849.10147076284.0
yarn add @grafana/scenes@5.7.0--canary.849.10147076284.0
```
</details>
=> Allow setting _skipOnLayoutChange in SceneGridLayout

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
when we have chained variables in a repeat panel and one of them fails we do not update remaining ones and repeated panel does not appear because remaining variables are stuck in loading state that forces early return in repeat panel logic and does not render anything. 
In order to render the panel with some sort of error message all variables should finish updating.
part of https://github.com/grafana/grafana/pull/91149
<details>
<summary>📦 Published PR as canary version: <code>5.7.1--canary.850.10147682812.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.7.1--canary.850.10147682812.0
npm install @grafana/scenes@5.7.1--canary.850.10147682812.0
yarn add @grafana/scenes-react@5.7.1--canary.850.10147682812.0
yarn add …
```
=> SceneVariableSet: Update all variables in case of error

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx
This refers to #90538
**Problem**
After attempting to fix this in #838, we discovered that the panels were not receiving the intended event because they were receiving the general app event instead of the specific panel event.
**Solution**
This pull request addresses two main issues:
- Ensure that the event is propagated to the dashboard scene so that any events subscribed to the root receive it correctly
- Replace the event bus for the panel with the one created for the context.
This ensures that the event subscribed to is the same event emitted, as they are obtained through the same mechanism.
<details>
<summary>📦 Published PR as canary version: <code>5.7.1--canary.852.10167028474.0</code></summary>
<br />
```bash
npm install …
```
=> VizPanel: React to RefreshEvent for non-data changes

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
Fixes https://github.com/grafana/support-escalations/issues/11781
<details>
<summary>📦 Published PR as canary version: <code>5.7.3--canary.857.10198637822.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.7.3--canary.857.10198637822.0
npm install @grafana/scenes@5.7.3--canary.857.10198637822.0
yarn add @grafana/scenes-react@5.7.3--canary.857.10198637822.0
yarn add @grafana/scenes@5.7.3--canary.857.10198637822.0
```
</details>
=> AdHocFilters: Support custom filter keys

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
More test cases:
A throws, B and C do not throw
B throws, A and C do not throw
=> SceneVariableSetTest - add test cases when one of chained variables throws errors

packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/variables/variants/DataSourceVariable.test.ts
There are some old dashboards that have query variables that reference themself in the query, this is preventing the query runner from executing the variable query as it is waiting for the variable to load. 
I'm not confident this is the best solution to this issue. A different approach would be to remove the reference to itself when we build the scene, however this could potentially be quite messy. We should probably also look into if this is an issue with other variable types.
https://github.com/grafana/support-escalations/issues/11766
=> Add backwards compatibility for query variables referencing themselves

packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx, packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
In order to make the sticky controls work we cannot have an absolute wrapper around the grid (as this makes the div there the sticky lives not get the needed hight for sticky to work).
But in changing this to useMeasure and same CSS as in 
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/DashboardGrid.tsx#L327 
but I am running into the same problem I have always had in that when the wrapping div is not absolute I cannot reduce the size, the resize observer is not register any change to reduced viewport as the inner grid div current width is blocking a reduction in size. 
Have no idea why it works in DashboardGrid.tsx#L327
=> SceneGridLayout: Change to useMeasure and non absolute div wrapper

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts, packages/scenes/src/utils/wrapInSafeSerializableSceneObject.test.ts, packages/scenes/src/utils/wrapInSafeSerializableSceneObject.ts, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariable.tsx, packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
This PR brings backwards compatibility for `scopedVars.__sceneObject` and `SafeSerializableSceneObject`. (ref https://github.com/grafana/scenes/pull/828, https://github.com/grafana/scenes/issues/851)
With this change, Scenes apps using 5.8+ will be able to run smoothly in Grafana versions that do not contain https://github.com/grafana/grafana/pull/90833.
For versions that will have [this](https://github.com/grafana/grafana/pull/90833) included, that is :
- 11.2.x 
- 11.1.2+ (backport MERGED: https://github.com/grafana/grafana/pull/90837)
- 11.0.4+ (backport MERGED: https://github.com/grafana/grafana/pull/91240)
- 10.4.8+ (backport MERGED: https://github.com/grafana/grafana/pull/91242)
`scopedVars.__sceneObject` WILL use `SafeSerializableSceneObject`. For versions other than mentioned …
=> SafeSerializableSceneObject: Wrap only for supported Grafana version

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
This PR fixes an issue where in a variable with key-value pairs([esc](https://github.com/grafana/support-escalations/issues/11759)), setting the key in the url param would not update to it's value but instead create a new custom option with the key as a value. 
Before:
https://github.com/user-attachments/assets/cf3aca6a-cfc6-4c7f-825d-7f1bf1fc6ff3
After:
https://github.com/user-attachments/assets/575498fe-a385-43c0-a293-bd1d180e5d17
=> MultiValueVariable: Fix issue where url update would not take options into account

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
Fixes an issue where auto refresh would continue running even if the grafana tab would not be focused. This migrates the functionality from the old architecture
=> Allow auto refresh only if tab is visible

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
https://github.com/grafana/support-escalations/issues/12157
The refresh picker in scenes does not respect the min_refresh_interval from the config.
This PR makes sure we filter the list of intervals to only include intervals longer than the min config. Also sets the interval to the minimum interval in the list if updated from the URL with a bad interval.
=> Make SceneRefreshPicker respect config.minRefreshInterval

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx
A problem with rendering a child in isolation is that its parents are not active.
This is one of the main reasons we clone the panel in ViewPanelScene and PanelEditor so that we render a local VizPanel copy. But this local copy has a context problem. 
The panel could be a repeated panel and have local variable context, it could be inside a repeated row (with local variable values). In the future it could be inside layout containers have have local time range and variables. 
This creates a lot of extra complexity in ViewPanelScene and PanelEdit where we have to try to copy this local variable context. 
It would be a lot easier if we could just render the real source VizPanel we want to show directly, without any local clone & trying to re-create the context. 
The main problem of rendering …
=> SceneObjectBase: Support rendering a child out of context

packages/scenes/src/variables/components/VariableValueInput.tsx, packages/scenes/src/variables/variants/TextBoxVariable.tsx
**Problem**
When using data links to update the variable value, the variable scene object didn't get the state from the URL because it was not setting the state properly
**Fixes**
When any dashboard interaction updates the variable values through URL.
Depends on this fix, since AutoSizeInput ignores `value` prop https://github.com/grafana/grafana/pull/92997
=> TextBoxVariable: fixes issues with TextBox variable when being updated by URL 

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx
Reverts grafana/scenes#887
I did not end up needing this as a core feature, mainly because I needed the behavior to be recursive and it was pretty easy to accomplish with a external util function:
https://github.com/grafana/grafana/blob/1e884741f23cebc07097abfe5b51d09ff7568420/public/app/features/dashboard-scene/utils/utils.ts#L274
https://github.com/grafana/grafana/pull/93000/
=> Revert "SceneObjectBase: Support rendering a child out of context"

packages/scenes-app/src/demos/adhocFiltersDemo.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/DropdownItem.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/useFloatingInteractions.ts, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Code is rough, but creating a PR so that we can start the review while I do code clean up
Introduce the multi value ad hoc filters support in the new filters UI
<details>
<summary>📦 Published PR as canary version: <code>5.14.2--canary.889.10771581250.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.14.2--canary.889.10771581250.0
npm install @grafana/scenes@5.14.2--canary.889.10771581250.0
yarn add @grafana/scenes-react@5.14.2--canary.889.10771581250.0
yarn add @grafana/scenes@5.14.2--canary.889.10771581250.0
```
</details>
=> AdHocFilters - multi value support in new filters UI

packages/scenes/src/core/SceneObjectBase.tsx
Sometimes it's useful to move one instance to another and in those cases we get a console.warning that the parent changes, which can be annoying in both unit tests and in production code. 
This function enabled us those uses cases without that console.warn 
<details>
<summary>📦 Published PR as canary version: <code>5.14.3--canary.892.10793378428.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.14.3--canary.892.10793378428.0
npm install @grafana/scenes@5.14.3--canary.892.10793378428.0
yarn add @grafana/scenes-react@5.14.3--canary.892.10793378428.0
yarn add @grafana/scenes@5.14.3--canary.892.10793378428.0
```
</details>
=> SceneObjectBase: add clearParent

packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/sceneGraphEvents.tsx, packages/scenes/src/core/sceneGraph/index.ts, packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts
- Added a demo to show how bubble events traverse the scene graph.
- Added a sceneGraph.findDescendents (by type) utility function
[Screencast_20240725_145040.webm](https://github.com/user-attachments/assets/8c886a6c-c448-4b1a-b6ab-5c752763b844)
=> Demo: Demonstrate event traversal through scene graph

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/src/variables/variants/TestVariable.tsx
This PR changes then the `SceneVariableValueChangedEvent` is published. It should only publish, in the case of `All` value, only when options actually change. 
This will help us in various scenarios that are currently giving us headaches like [here](https://github.com/grafana/grafana/pull/93168) where the variable potentially `hasChanged`, after a dashboard refresh, for example, but in truth there is no change in the options, and that var is set only because it sees the `All` value selected.
Another example is in the case of variables that depend on themselves, case that is supported in the new arch due to backwards compat with the old arch. If the value is `All` then the variable is constantly considered as changed and thus publishes the event which will trigger an infinite query in the …
=> MultiValueVariabe: Change when value changed event is published

packages/scenes/src/variables/variants/LocalValueVariable.ts
isMulti and includeAll needs to be present for the interpolation of SQL queries to work. If this is not included the query would need to change if you change the repeating behavior of the panel.
<details>
<summary>📦 Published PR as canary version: <code>5.14.4--canary.900.10848367235.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.14.4--canary.900.10848367235.0
npm install @grafana/scenes@5.14.4--canary.900.10848367235.0
yarn add @grafana/scenes-react@5.14.4--canary.900.10848367235.0
yarn add @grafana/scenes@5.14.4--canary.900.10848367235.0
```
</details>
=> Include isMulti and includeAll in LocalValueVariable

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Adds descriptions for all the operators, instead of just a select few
=> Adhoc filters: Add descriptions for all operators

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
slack thread for context: https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1726085702354709
<details>
<summary>📦 Published PR as canary version: <code>5.14.4--canary.898.10848470476.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.14.4--canary.898.10848470476.0
npm install @grafana/scenes@5.14.4--canary.898.10848470476.0
yarn add @grafana/scenes-react@5.14.4--canary.898.10848470476.0
yarn add @grafana/scenes@5.14.4--canary.898.10848470476.0
```
</details>
=> AdHocVariable: Don't throw when operator is not found

.github/workflows/deploy-to-dev-portal-dev.yml, .github/workflows/deploy-to-dev-portal-prod.yml
Since the move to Turbo (done as part of adding scenes-react) docs builds
have been failing in CI ([example 1] and [example 2]). The config args
aren't being passed through to the website package since we're using turbo
now.
This commit skips using turbo altogether for docs builds, which seems to
be the simplest solution; I can't find a way to pass the correct config
args through turbo to the website package, so I'm just skipping it.
Should fix https://github.com/grafana/scenes/issues/895.
=> fix: docs builds in CI

packages/scenes-react/src/components/VizPanel.tsx, packages/scenes-react/src/hooks/useDataTransformer.ts, packages/scenes/src/index.ts, packages/scenes/src/querying/DataProviderProxy.ts
Main is broken after recent PR merged (by me), not sure why the PR was green. 
This should fix it (and forgot to rename the class before merging so doing that as well)
=> DataProviderProxy: Rename and fix imports

packages/scenes/src/components/SceneTimePicker.tsx, packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx
Apparently, the setWeekStart runtime function has stopped working some time ago (maybe due a browser update), not sure. 
Frontend platform added a weekStart prop to TimeRangePicker recently (but did not notify us about this) 
This updates SceneTimePicker to pass the weekStart state prop to TimeRangePicker 
I also have a a bit related PR that fixes weekStart for all scene app plugins (so TimeRangePicker uses the system or user weekStart by default) 
https://github.com/grafana/grafana/pull/93464
=> SceneTimeRange: Use new weekStart prop on TimeRangePicker

packages/scenes/src/components/SceneApp/SceneAppPageView.tsx, packages/scenes/src/components/SceneApp/utils.ts, packages/scenes/src/services/UrlSyncManager.ts, packages/scenes/src/services/useUrlSync.ts, packages/scenes/src/utils/utils.ts
Fixes: https://github.com/grafana/grafana/issues/93225
This changes the UrlSyncManager to use the `locationsService` from context making it possible to render 2 scenes app without them clashing on URL handling, which is needed for the sidecar project https://github.com/grafana/grafana/pull/91648.
See this draft PR for the Explore Traces app: https://github.com/grafana/explore-traces/pull/102 for usage.
=> Use locationService from context in UrlSyncManager

packages/scenes/src/core/SceneTimeRange.tsx
Not sure I fully understand this change (https://github.com/grafana/scenes/pull/420/ ) so this PR is reverting it.
Opening revert PR just to remember to have a discussion on this on next scenes sync. 
The original PR was fixing 
https://github.com/grafana/scenes/issues/457 
but after investing a similar issue (https://github.com/grafana/support-escalations/issues/12532) we have right now in main I think the problem is not in scenes but in the TimePicker and how it handle string raw values (it does handle them as UTC iso strings but just as plain strings) 
In my view the bug in https://github.com/grafana/scenes/issues/457  was not that the timezone was lost but the fact that we showed an iso string in those inputs to begin with. Just try setting absolute time range using the calendar dates …
=> SceneTimeRange: Fixes inconsistent representation of time range

packages/scenes/src/components/SceneTimePicker.test.tsx, packages/scenes/src/components/SceneTimePicker.tsx
Also added some tests :-)
Closes #909
<details>
<summary>📦 Published PR as canary version: <code>5.16.0--canary.915.11034968022.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.16.0--canary.915.11034968022.0
npm install @grafana/scenes@5.16.0--canary.915.11034968022.0
yarn add @grafana/scenes-react@5.16.0--canary.915.11034968022.0
yarn add @grafana/scenes@5.16.0--canary.915.11034968022.0
```
</details>
=> SceneTimePicker: Implement recently used absolute time ranges view

packages/scenes/src/variables/macros/AllVariablesMacro.test.ts, packages/scenes/src/variables/macros/AllVariablesMacro.ts
Fixes an issue where setting a datalink to another dashboard that included template vars and selecting the `All` value in the initial dashboard would generate the URL for the second dashboard using all the values concatenated instead of the special `All` value.
This PR addresses that and bring back the functionality from the old arch
Before:
https://github.com/user-attachments/assets/5493db27-27f0-4e15-8ae8-782f213620f8
After:
https://github.com/user-attachments/assets/86f92cc2-cb48-48ea-a1ef-d14a22abe5f6
Closes https://github.com/grafana/grafana/issues/90180
=> Fix showing all value in datalinks when linking to another db and including vars

packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Fixes row styling for rows with very large titles. This bug is also reproducible in the old arch
Before:
https://github.com/user-attachments/assets/889ec127-cceb-47a6-b0b8-2022237008ea
After:
https://github.com/user-attachments/assets/4fdd543e-1e4b-4e91-873b-821c25242c36
=> Fix row title styling for large titles

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
Related to https://github.com/grafana/grafana/pull/93756 where old dashboards with refresh: true would end up with refresh=true in URL which would set the auto refresh to first valid interval. 
The OSS PR fixed the issue but this PR is to make sure it can't be introduced again somehow by mistake
This PR 
* Never add refresh to URL unless it has a value (so no longer `&refresh=` added to URL)
* Never allow invalid interval values to set refresh to first valid valid value
=> Refresh: Improve / harden refresh url sync

packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
Alternative to https://github.com/grafana/grafana/pull/94216
<details>
<summary>📦 Published PR as canary version: <code>5.17.0--canary.929.11178151684.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.17.0--canary.929.11178151684.0
npm install @grafana/scenes@5.17.0--canary.929.11178151684.0
yarn add @grafana/scenes-react@5.17.0--canary.929.11178151684.0
yarn add @grafana/scenes@5.17.0--canary.929.11178151684.0
```
</details>
=> Annotations: Include templateSrv.getVariables with dashboard object in legacy annotation queries

packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
This fix moves logic from [this](https://github.com/grafana/grafana/pull/93327) into the `AnnotationDataLayer`. 
This is needed to add backwards compatibility to how the old arch worked with RefreshEvents. Plugin devs depend on this event. This need is better explained in the PR above.
<details>
<summary>📦 Published PR as canary version: <code>5.18.0--canary.930.11181993017.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.18.0--canary.930.11181993017.0
npm install @grafana/scenes@5.18.0--canary.930.11181993017.0
yarn add @grafana/scenes-react@5.18.0--canary.930.11181993017.0
yarn add @grafana/scenes@5.18.0--canary.930.11181993017.0
```
</details>
=> Emit RefreshEvent on annotation enable/disable

packages/scenes-react/src/components/VizPanel.tsx
When passing a VizPanel a dataProvider of type SceneDataTransformer (returned by useDataTransformer) it would log error that we are changing it's parent 
<details>
<summary>📦 Published PR as canary version: <code>5.16.4--canary.928.11176592185.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.16.4--canary.928.11176592185.0
npm install @grafana/scenes@5.16.4--canary.928.11176592185.0
yarn add @grafana/scenes-react@5.16.4--canary.928.11176592185.0
yarn add @grafana/scenes@5.16.4--canary.928.11176592185.0
```
</details>
=> VizPanel: Fixes issue with viz panel when passing it SceneDataTransformer

packages/scenes/src/variables/interpolation/formatRegistry.test.ts, packages/scenes/src/variables/interpolation/formatRegistry.ts, packages/scenes/src/variables/macros/AllVariablesMacro.test.ts
Tries to leverage the existing url sync handler interface / abstraction inside the variable interpolation value formatters. 
Alternative fix for  
https://github.com/grafana/scenes/pull/926
Fixes: https://github.com/grafana/grafana/issues/94303
=> Interpolation: Fixes queryparam variable format when used with adhoc filter variable

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/utils/date.ts, packages/scenes/src/utils/parseUrlParam.test.ts, packages/scenes/src/utils/parseUrlParam.ts
- Add check for invalid date values
- App was completely breaking when we passed in invalid values to `from` or `to` (we noticed that by accident somebody copy/pasted a url and it had `to=now)`)
- Validate `from` and `to` values before calculating the value
- Also fix issue where `from` value would revert to `1970` if setting the time range from: absolute date -> now 
- We were not properly parsing a human readable date style from url 
Fixes [#1295](https://github.com/grafana/app-observability-plugin/issues/1295)
Fixes [#1306](https://github.com/grafana/app-observability-plugin/issues/1306)
=> Add checks for valid dates before saving calculating values

docusaurus/docs/visualizations.md, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Data trails has this super awkward way to share config between builders where they wait for activation to call onOptionsChange. '
The reason for this hack is that it's not super easy to share config between builders (esp as one of the builders is created by a different path, so extracting the shared config to a factory function that creates the builder + shared config is not possible). 
https://github.com/grafana/grafana/blob/main/public/app/features/trails/Breakdown/LabelBreakdownScene.tsx#L323
One way to support shared config would be to move it to a function that takes in a builder, but for that pattern to feel nice I think having an function on the builder directly to enable this makes it so much more readable and clean (vs having to define a builder variable, pass it to shared config …
=> PanelBuilders: Mixin function to share config

packages/scenes/src/components/SceneRefreshPicker.test.ts, packages/scenes/src/components/SceneRefreshPicker.tsx
If a dashboard has refresh_interval set to an array with just an empty string in it `[""]` the parsing of the interval will fail and the dashboard will fail to load.
This fix filters out any intervals we're unable to parse.
<details>
<summary>📦 Published PR as canary version: <code>5.19.1--canary.933.11257845651.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.19.1--canary.933.11257845651.0
npm install @grafana/scenes@5.19.1--canary.933.11257845651.0
yarn add @grafana/scenes-react@5.19.1--canary.933.11257845651.0
yarn add @grafana/scenes@5.19.1--canary.933.11257845651.0
```
</details>
=> Fix a crash when refresh interval set to empty string

packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
In scenes, changing certain panel options, for example the "Show threshold labels" option on Gauge panels, wouldn't re-render the panel. Looking at the GaugePanel component's render function, we have the following:
```typescript
render() {
const { height, width, data, renderCounter, options } = this.props;
const { minVizHeight, minVizWidth } = this.calculateGaugeSize();
return (
<VizRepeater
getValues={this.getValues}
renderValue={this.renderValue}
width={width}
height={height}
source={data}
autoGrid={true}
renderCounter={renderCounter}
orientation={options.orientation}
minVizHeight={minVizHeight}
minVizWidth={minVizWidth}
/>
);
}
```
The options prop _does_ update, but `VizRepeater` is a pure component and since options isn't passed as a prop, the component doesn't re-render.
To fix …
=> VizPanel: Fix issue where changing panel options wouldn't cause re-render

packages/scenes-react/src/index.ts
Needed if we want to be able to use react-context hooks in dashboard scenes 
<details>
<summary>📦 Published PR as canary version: <code>5.16.3--canary.925.11130578774.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.16.3--canary.925.11130578774.0
npm install @grafana/scenes@5.16.3--canary.925.11130578774.0
yarn add @grafana/scenes-react@5.16.3--canary.925.11130578774.0
yarn add @grafana/scenes@5.16.3--canary.925.11130578774.0
```
</details>
=> SceneContextObject: Export context object

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.test.ts, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts, packages/scenes/src/variables/components/getOptionSearcher.test.ts, packages/scenes/src/variables/components/getOptionSearcher.ts
Prior to this change, we were leaving the order of the options in adhoc filters unchanged, which has led to some
[poor quality search results][example] across plugins using adhoc filters.
This change sorts the options in adhoc filters using ufuzzy, which should lead to better search results. This is the same approach used in Grafana core (see [1], [2], [3] for examples).
[example]: https://raintank-corp.slack.com/archives/C075BDBTX96/p1729076789303509
[1]: https://github.com/grafana/grafana/blob/ca1fd028a2a1aa0dd560d8220c9f04c243d77445/public/app/features/variables/pickers/OptionsPicker/reducer.ts#L264-L272
[2]: https://github.com/grafana/grafana/blob/ca1fd028a2a1aa0dd560d8220c9f04c243d77445/public/app/features/trails/services/search.ts#L13
[3]: …
=> feat: sort adhoc filter options using ufuzzy

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/sceneGraph/utils.ts
We currently have a bug in scenes where you cannot "apply" changes in inspect drawer because there is an error thrown when you hit "Apply" (only happens when the dashboard is NOT in edit mode). The error happens because we try go into edit mode while the inspect drawer is open the error is `'Cannot clone a SceneObject with a SceneObjectRef in state` which we throw from the cloning. 
* Remove throwing this error (replaced with a console.warning)
* Now clone callers can opt not to clone some objects by passing them in as undefined in the "withState" argument.  (makes is so we can clone the state of dashboards with overlay: undefined)
https://github.com/grafana/grafana/issues/95482
=> SceneObject: Improve cloning logic

packages/scenes/src/variables/components/VariableValueInput.tsx
Without max width, text variable expands infinitely causing strange issues like this:
https://github.com/user-attachments/assets/2a815f53-6858-47f4-942b-5d1e9cbf3cc2
Fixes: https://github.com/grafana/support-escalations/issues/13095
=> VariableValueInput: Set max width

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Rework backspace functionality to delete filter key, operator, values individually instead of whole filter.
I am adding additional property `forceEdit` on the `AdHocFilterWithLabels` type that is purely used to trigger UI change via useEffect because that was the cleanest way I could think of to trigger edit in separate filter pills that has no reference to each other.
<details>
<summary>📦 Published PR as canary version: <code>5.21.1--canary.942.11610448397.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.21.1--canary.942.11610448397.0
npm install @grafana/scenes@5.21.1--canary.942.11610448397.0
yarn add @grafana/scenes-react@5.21.1--canary.942.11610448397.0
yarn add @grafana/scenes@5.21.1--canary.942.11610448397.0
``` …
=> AdHocFilterCombobox: Improve backspace functionality to delete filter key, operator and values separately

packages/scenes/src/components/VizPanel/VizPanel.tsx
When changing the panel plugin the pluginVersion will not be correct, this means the migration will always run. It shouldn't have to run when changing from one plugin type to another.
=> Don't run migration when changing panel plugin

packages/scenes/src/components/VizPanel/VizPanel.tsx
In most cases we want to refresh the fieldConfig/options when changing plugin type, but in the case of Library Panels, for example, we only want to rerender the panel, without refreshing it's configs, since the existing ones are valid. Through this flag we can fix that [here](https://github.com/grafana/grafana/pull/95643) and avoid bugs where a lib panel has a set color mode, but after `changePluginType` the defaults are applied and the lib panel ones are overwritten
<details>
<summary>📦 Published PR as canary version: <code>5.22.0--canary.950.11661930270.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.22.0--canary.950.11661930270.0
npm install @grafana/scenes@5.22.0--canary.950.11661930270.0
yarn add …
```
=> VizPanel: Add flag to decide whether configs should be refreshed on `changePluginType`

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/sceneGraph/utils.ts
Was a bug in https://github.com/grafana/scenes/pull/944 where it now clones the state passed in with the `withState` function argument. This was not intended. 
I had this condition at one point in that PR but for some reason I thought I did not need it, but of course we do. 
<details>
<summary>📦 Published PR as canary version: <code>5.22.1--canary.953.11666335318.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.22.1--canary.953.11666335318.0
npm install @grafana/scenes@5.22.1--canary.953.11666335318.0
yarn add @grafana/scenes-react@5.22.1--canary.953.11666335318.0
yarn add @grafana/scenes@5.22.1--canary.953.11666335318.0
```
</details>
=> SceneObject: Cloning with state fix

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/services/UrlSyncManager.test.ts, packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/macros/timeMacros.test.ts, packages/scenes/src/variables/macros/timeMacros.ts
This PR fixes an issue with the time range picker: moving away from `default` or `browser` to another timezone, the URL parameter changes correctly. However, going back to `default` will leave the timezone parameter set to whatever have been picked previously.
This is because the time range picker sends an empty string as the value of the timezone and `getUrlState` omits the update due to empty string.
<details>
<summary>📦 Published PR as canary version: <code>5.21.1--canary.947.11593224430.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.21.1--canary.947.11593224430.0
npm install @grafana/scenes@5.21.1--canary.947.11593224430.0
yarn add @grafana/scenes-react@5.21.1--canary.947.11593224430.0
yarn add …
```
=> SceneTimeRange: Fix passing timezone URL parameter

packages/scenes/src/components/VizPanel/VizPanel.tsx
Previously when `forceRender` was called, for example when a change in the VizPanel's dependency config was detected, the VizPanelRenderer component itself would indeed re-render, but its children could potentially be pure components, like the StatPanel component, or they could be wrapped in VizRepeater, which is also pure, causing them not to re-render. These components won't re-render in cases where, for example, the panel contains data links containing template variables, as the field config object itself hasn't changed, just the value at which the variable points. By incrementing the `_renderCounter` when `forceRender` is called, panel components are also force to re-render.
<details>
<summary>📦 Published PR as canary version: <code>5.23.0--canary.954.11668840775.0</code></summary> …
=> VizPanel: Adjust forceRender logic

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/MultiValuePill.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
1. When editing value pre-fill input with the value for single value filters
2. Allow to select certain multi value to edit its content
<details>
<summary>📦 Published PR as canary version: <code>5.23.1--canary.955.11702691002.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.23.1--canary.955.11702691002.0
npm install @grafana/scenes@5.23.1--canary.955.11702691002.0
yarn add @grafana/scenes-react@5.23.1--canary.955.11702691002.0
yarn add @grafana/scenes@5.23.1--canary.955.11702691002.0
```
</details>
=> AdHocFiltersCombobox - Pre-fill filter combobox value on edit

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Fixes https://github.com/grafana/grafana/issues/96027 
The issue seems to be that both text & value are initialized to ALL_VARIABLE_VALUE, and in case the Select is not a multi value the correct label is not shown 
Think this could fix it 
<details>
<summary>📦 Published PR as canary version: <code>5.23.2--canary.959.11726132276.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.23.2--canary.959.11726132276.0
npm install @grafana/scenes@5.23.2--canary.959.11726132276.0
yarn add @grafana/scenes-react@5.23.2--canary.959.11726132276.0
yarn add @grafana/scenes@5.23.2--canary.959.11726132276.0
```
</details>
=> Variables: Saved default all value with non multi select fix

packages/scenes/src/variables/components/VariableValueSelectors.tsx
Fixes https://github.com/grafana/grafana/issues/91727
How to check:
1. create/edit variable
2. add label and save
3. remove label and save
Old: result blank variable label in UI. Disappears after refresh
New: variable label fallbacks to variable name
Don't see any risk here to change to `||` instead of `??`
<details>
<summary>📦 Published PR as canary version: <code>5.23.3--canary.963.11743338978.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.23.3--canary.963.11743338978.0
npm install @grafana/scenes@5.23.3--canary.963.11743338978.0
yarn add @grafana/scenes-react@5.23.3--canary.963.11743338978.0
yarn add @grafana/scenes@5.23.3--canary.963.11743338978.0
```
</details>
=> VariableLabel: change variable label check to OR instead of ??

packages/scenes-react/utils/test/__mocks__/style.ts, packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Extends this [PR](https://github.com/grafana/scenes/pull/956) to adhoc vars as well so all related variables get this feature.
Related [PR](https://github.com/grafana/grafana/pull/96077)
<details>
<summary>📦 Published PR as canary version: <code>5.24.0--canary.960.11775742614.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.24.0--canary.960.11775742614.0
npm install @grafana/scenes@5.24.0--canary.960.11775742614.0
yarn add @grafana/scenes-react@5.24.0--canary.960.11775742614.0
yarn add @grafana/scenes@5.24.0--canary.960.11775742614.0
```
</details>
=> Variables: Add new `allowCustomValue` flag to AdHoc Variable

packages/scenes-app/src/demos/panelHeaderActions.tsx, packages/scenes/src/components/VizPanel/VizPanelExploreButton.tsx, packages/scenes/src/index.ts, packages/scenes/src/utils/explore.test.ts, packages/scenes/src/utils/explore.ts
Hey,
On popular request, contributing a panel explore button derived from app o11y implementation. It's been copied around to other apps, so seems to make sense to contribute it to scenes.
Does this make sense? If so, I'll add tests. Also thinking it's maybe whorthwile to make a `getExploreUrl(sceneObject)` util as it's own thing in case you want something else than a button
=> Add VizPanelExploreButton scene object

packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/components/VariableValueSelect.test.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/variants/MultiValueVariable.ts
We are a feature request to offer the ability to select whether a variable can support custom values or just lock the options list to contain only queried option values. This change is needed in scenes to offer the functionality in dashboards. 
Since we currently allow custom values by default, we maintain this default but offer the option to disable the flag in dashboards variable settings.
Related [PR](https://github.com/grafana/grafana/pull/95949)
<details>
<summary>📦 Published PR as canary version: <code>5.24.0--canary.956.11779891409.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.24.0--canary.956.11779891409.0
npm install @grafana/scenes@5.24.0--canary.956.11779891409.0
yarn add …
```
=> Variables: Add new `allowCustomValue` flag to MultiVariables

packages/scenes-react/package.json, packages/scenes/package.json, yarn.lock
This PR relaxes scenes dependencies so consuming apps (like Grafana) don't bundle multiple copies of packages when they get patch or minor bumps.
Additionally it sets e2e-selectors as a peer dep to solve conflicts occurring within yarn lock in Grafana which has caused issues for those [that build Grafana](https://github.com/grafana/grafana/pull/92543#issuecomment-2387538247) from source in CI environments where yarn enables "hardening mode".
<details>
<summary>📦 Published PR as canary version: <code>5.24.1--canary.940.11818090538.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.24.1--canary.940.11818090538.0
npm install @grafana/scenes@5.24.1--canary.940.11818090538.0
yarn add …
```
=> Chore: Relax dependencies and move e2e-selectors to peerDeps

packages/scenes/package.json, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts, packages/scenes/src/variables/components/getOptionSearcher.ts, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts, yarn.lock
ensures that when searching `namespace`, we get exact results first ~~(although case-insensitive)~~.
Ref: https://raintank-corp.slack.com/archives/C0630AYC4SY/p1731592718073559
the code is pretty much copy-pasted in 3 places, probably should be extracted?
sample list:
```
client_service_namespace
namespace
alert_namespace
container_namespace
Namespace
client_k8s_namespace_name
```
=> Variables: Fix search result ordering to use match quality

packages/scenes/src/querying/layers/annotations/filterAnnotations.ts
Fixes an issue where dashboard-wide annotations (ones created via API without a defined `panelId`, which are given the `panelId` 0 when stored in the database) would not render on existing panels. (Newly created panels rendered the annotations correctly).
Not super familiar with the code so please let me know if there's a better way to fix this that I've missed. :)
Fixes the following issue: https://github.com/grafana/support-escalations/issues/13356
<details>
<summary>📦 Published PR as canary version: <code>5.23.4--canary.964.11745806385.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.23.4--canary.964.11745806385.0
npm install @grafana/scenes@5.23.4--canary.964.11745806385.0
yarn add …
```
=> Annotations: Fix issue where dashboard annotations weren't rendering

packages/scenes/src/variables/adhoc/patchGetAdhocFilters.ts
Hello Grafana team!
During development, I encountered a bug where originalGetAdhocFilters consistently tries to locate the default data source. This occurs because the data source name is not passed correctly, resulting in it being **undefined**.
This fix addresses the issue by ensuring that the data source name is properly passed, allowing originalGetAdhocFilters to function as intended.
Please review the changes, and if everything looks good, kindly merge them. Your feedback would be greatly appreciated!
=> Add missing parameter to patchGetAdhocFilters.ts

packages/scenes/src/components/SceneControlsSpacer.tsx, packages/scenes/src/core/SceneComponentWrapper.test.tsx, packages/scenes/src/core/SceneComponentWrapper.tsx, packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/types.ts
A big decision we made early on was to force activation of the scene object before it's component get's rendered. This was mainly to make sure parent SceneVariableSets where activated before child SceneQueryRunners come asking if their variables are "ready" or not. 
To solve this and ensure that all scene objects can run state initiation logic before children get rendered/activated, we made sure the in ComponentWrapper will not render the component until after activation. In retrospect I think this was a mistake. 
But this has some really big negative effects for React and rendering without flickering / intermediate empty states. 
An example of this problem was first scene in the SceneControlsSpacer object that renders a simple empty div but because it is rendered with a null value before …
=> SceneObject: Render before activation

packages/scenes-app/src/demos/index.ts, packages/scenes-app/src/demos/seriesLimit.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/components/VizPanel/VizPanelSeriesLimit.tsx, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
I really like https://github.com/grafana/scenes/pull/912 as a feature but there is something about the implementation that feels a bit messy / complex, feels like there should be an simpler way to accomplish this (I blame scenes arch here for making this tricky) 
This is one approach where it's implemented more as rendering optimization feature inside VizPanel rendering instead of as a data state feature via SceneDataTransformer. A lot of the complexity in https://github.com/grafana/scenes/pull/912 is dealing with the wrapping of the already set data provider and for the title item to find and update the data transformer. 
There is benefit to that data provider approach and that is that other behaviors attached to VizPanel that are using sceneGraph.getData to get the data would also get …
=> VizPanel: Limit series feature

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
Fixes concurrency issue during options update in ad hoc filters combobox. 
<details>
<summary>📦 Published PR as canary version: <code>5.28.1--canary.982.12087080743.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.28.1--canary.982.12087080743.0
npm install @grafana/scenes@5.28.1--canary.982.12087080743.0
yarn add @grafana/scenes-react@5.28.1--canary.982.12087080743.0
yarn add @grafana/scenes@5.28.1--canary.982.12087080743.0
```
</details>
=> AdHocFiltersCombobox: Prevent updating combobox options when input type changed during fetch

packages/scenes/src/variables/components/VariableValueSelect.test.tsx, packages/scenes/src/variables/variants/query/toMetricFindValues.ts, packages/scenes/src/variables/variants/query/utils.test.ts, packages/scenes/src/variables/variants/query/utils.ts
Fixes https://github.com/grafana/grafana/issues/96140 
A missed code in the old system was this: 
https://github.com/grafana/grafana/blob/main/public/app/features/variables/state/sharedReducer.ts#L157 
Where any non string text or value value was replaced with an empty string
=> Variables: Fixes issue when variable value was null

packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts, packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Fixes failing run: https://github.com/grafana/scenes/actions/runs/12181444222
https://github.com/grafana/scenes/pull/808 CI ran before merge of https://github.com/grafana/scenes/pull/988.
=> Lint: scenes/pull/808

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
The following should improve experience and fix regressions introduced by https://github.com/grafana/scenes/pull/955.
Fixes: https://github.com/grafana/scenes/issues/986
Adjustments:
1. highlight input value on edit (for easy deletion when typing)
2. prevent options filtering once you enter filter value edit (reenable after first onChange)
3. adjust multi-value experience to follow above
<details>
<summary>📦 Published PR as canary version: <code>5.29.0--canary.992.12182926395.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.29.0--canary.992.12182926395.0
npm install @grafana/scenes@5.29.0--canary.992.12182926395.0
yarn add @grafana/scenes-react@5.29.0--canary.992.12182926395.0
yarn add …
```
=> AdHocFiltersCombobox - Improve filter editing behaviour when pre-filling value on edit

packages/scenes-react/src/components/VizPanel.test.tsx, packages/scenes-react/src/components/VizPanel.tsx
- #761 
- VizPanel add missing props
- Naive attempt at adding missing VizPanel props. Perhaps more knowledgable people would know how to automatically add the VizPanelState from `scenes`. It looks like there might be some newer props in VizPanelState already
```
seriesLimit?: number;
seriesLimitShowAll?: boolean;
collapsible?: boolean;
collapsed?: boolean;
```
- The [grafana-attributions-app](https://github.com/grafana/grafana-attributions-app) was experimenting using scenes react, but almost every panel ended up needed something from the missing props 😆 .  
<details>
<summary>📦 Published PR as canary version: <code>5.31.0--canary.998.12301751531.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.31.0--canary.998.12301751531.0 …
```
=> feat: (scenes-react) - VizPanel add missing props and tests

packages/scenes/src/variables/groupby/GroupByVariable.tsx
When trying to use the Single select in db-o11y, realized we were sending incorrect data format. 
` "error": "json: cannot unmarshal string into Go struct field internalQueryModel.groupByKeys of type []string",
`
In this PR I'm wrapping the value in an array.
=> fix: wrap groupBy single-select value in an array

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx
Did a big mistake in https://github.com/grafana/scenes/pull/910 , I removed this setWeekStart as I could not see it having any impact, but did only check the weekstart shown in the calendar, now the weekstart used when evaluating datemath expressions like "This week" or "Previous week", those expression this setWeekStart (which updates moment locale setting) is needed 
Fixes https://github.com/grafana/support-escalations/issues/13898
=> SceneTimeRange: Fixes weekstart issue when evaluting data math

packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/variables/adhoc/patchGetAdhocFilters.ts, packages/scenes/src/variables/groupby/findActiveGroupByVariablesByUid.ts, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts
Use case - use datasource variable as a datasource for ad hoc filter and in a dashboard query. 
so we have datasource variable `dsVar` and it equals to `prom-1` as example then:
1. ds variable in filter and panel (both `${dsVar}` )
2. ds variable in filter (`${dsVar}`) and named ds in panel (`prom-1`) that are the same
3. named variable in filter (`prom-1`) and ds variable in panel (`${dsVar}`) that are the same
Issues solved:
1. `findAndSubscribeToAdHocFilters` did not get interpolated datasource name.
2. ad hoc filter options would not filter down options based on query in dashboard therefore interpolated datasource uuids in `getQueriesForVariables` 
adding dashboard JSON that replicates issue:
[dsVar as filter datasource-1733769038417.json](https://github.com/user-attachments/files/1806 …
=> Variables: Interpolate datasource uid when used with datasource variable

packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/core/SceneTimeZoneOverride.tsx, packages/scenes/src/utils/evaluateTimeRange.ts
So after testing https://github.com/grafana/scenes/pull/1002 in main it had some issues
mainly that the weekstart is only updated on scene time range activation, which only happens when the dashboard is mounted so if you change weekstart and go back to the dashboard the time range has not updated (even when you hit refresh on the time range picker). 
With this change we update the system weekstart when we evaluate the time range (with a quick cache var so we do not always call setWeekStart). 
There will still be a need for the user to manually hit refresh after updating time range (unless we in core call onRefresh after setting weekStart which we can do in the main repo PR)   
<details>
<summary>📦 Published PR as canary version: <code>5.35.0--canary.1007.12374452740.0</code></summary>
<br …
=> SceneTimeRange: Set weekstart when evaluating time range

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Use case: We have 2 ad-hoc variables at different scopes in the application, an "editing" variable at a lower scope, and a "submitted" variable at a higher scope. Both variables are interpolated by certain query providers. Our un-interpolated expression would look like this: `${AD_HOC_SUBMITTED} ${AD_HOC_EDITING}`. The submitted variable is rendered on the top scene, and on every route, but the "editing" variable only exists for a single route. Both variables are rendered in different areas of the UI.
When users are done configuring the lower scope variable, it is submitted, and moved to the higher scope variable. The value in the editing variable is deleted.
However since the `SceneVariableValueChangedEvent` is emitted whenever an individual ad-hoc variable's expression has changed, this …
=> AdHocFiltersVariable: provide updateFilters method to allow updating filters without emitting SceneVariableValueChangedEvent

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/utils.test.ts
fix for searching non-latin tpl vars.
see https://github.com/grafana/grafana/issues/83806#issuecomment-2565438090
related non-scenes PR: https://github.com/grafana/grafana/pull/98416
=> AdHocFilters: Fix matching non-latin template vars in filter

packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/utils.ts
sorting was carried out agains `option.text` instead of `option.label`
<details>
<summary>📦 Published PR as canary version: <code>5.36.2--canary.1015.12584248290.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.36.2--canary.1015.12584248290.0
npm install @grafana/scenes@5.36.2--canary.1015.12584248290.0
yarn add @grafana/scenes-react@5.36.2--canary.1015.12584248290.0
yarn add @grafana/scenes@5.36.2--canary.1015.12584248290.0
```
</details>
=> QueryVariable: Use correct option property for variable options sorting

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
We'd like to add a search input field to a page which already has AdHocFilters with a restricted set of keywords. We have the following requirements:
- when a search term is supplied, then all the queries on the page should be filtered as if there was a filter added for the a specific, fixed label. More precisely it should be equivalent to adding `specific_label=~.*searchTerm.*`
- but we don't want this new filter to be shown by the AdHocFilter control (we currently use VariableValueControl for that) or the URL
This PR enables us to achieve this by introducing the `hidden` property on AdHocFilters.
Related discussion: https://raintank-corp.slack.com/archives/C04FRQ2S0AV/p1732712478401569
=> AdHocFilters: add hidden option 

packages/scenes/src/querying/SceneQueryRunner.ts
compliments https://github.com/grafana/grafana/pull/98510. 
With both these PRs panel will redraw if you specify a variable in panel query options
<details>
<summary>📦 Published PR as canary version: <code>5.36.3--canary.1021.12630599445.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.36.3--canary.1021.12630599445.0
npm install @grafana/scenes@5.36.3--canary.1021.12630599445.0
yarn add @grafana/scenes-react@5.36.3--canary.1021.12630599445.0
yarn add @grafana/scenes@5.36.3--canary.1021.12630599445.0
```
</details>
=> ScenesQueryRunner: Add minInterval to variable dependencies

packages/scenes/src/variables/variants/MultiValueVariable.ts
fixes https://github.com/grafana/grafana/issues/98005
i think the variable edit page don't need current value to show. so i add a function `getOptionsForSelectWithoutCurrentValue`.
after this pr merged. i would change this line (https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/settings/variables/VariableEditorForm.tsx#L116) to use  `getOptionsForSelectWithoutCurrentValue`
=> Variables: current value

packages/scenes/src/index.ts, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts
When generating links to scenes apps in Explore or other external applications, we need to escape pipes and commas or scenes will be unable to parse the url parameters for variable values containing pipes or commas.
This PR exposes the methods scenes is using internally to build valid URLs that can be consumed by a scenes application. 
Also exposes `escapeLabelValueInRegexSelector` and `escapeLabelValueInExactSelector`.
<details>
<summary>📦 Published PR as canary version: <code>5.37.0--canary.1024.12749589889.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.37.0--canary.1024.12749589889.0
npm install @grafana/scenes@5.37.0--canary.1024.12749589889.0
yarn add @grafana/scenes-react@5.37.0--canary.1024.12749589889.0
yarn add …
```
=> sceneUtils: export methods for generating scenes URLs in external applications

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
stopping the bleed from https://github.com/grafana/grafana/issues/99021 where we can get a `number` instead of `string` in `option.label` in ad hoc filters which breaks the fuzzy search
<details>
<summary>📦 Published PR as canary version: <code>5.37.1--canary.1029.12889288329.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.37.1--canary.1029.12889288329.0
npm install @grafana/scenes@5.37.1--canary.1029.12889288329.0
yarn add @grafana/scenes-react@5.37.1--canary.1029.12889288329.0
yarn add @grafana/scenes@5.37.1--canary.1029.12889288329.0
```
</details>
=> AdHocFilterVariable: Force option label to be a string

packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx, packages/scenes/src/core/types.ts
Different layouts (row, grid, etc.) may have different requirements for handling drag/drop behavior, and so to allow for layout-specific event handling, I've added an optional method to the `SceneLayout` interface, `onDragStart`.
`VizPanelRenderer` finds the closest layout and grabs its hook(s) and then passes them through to `PanelChrome`.
We only need this one hook for now (no `onDragMove`, `onDragEnd`, etc.), but if we need to extend it later, there shouldn't be any problems.
Related: https://github.com/grafana/scenes/pull/993
Most of the code from the above PR will be moved to the main grafana repo, but this hook-handling code is still needed.
<details>
<summary>📦 Published PR as canary version: <code>5.38.0--canary.1028.12889195833.0</code></summary>
<br />
:sparkles: Test out this …
=> Layouts: Add ability to hook into VizPanelRenderer events

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
When `allowCustomValue:false`, meaning the user cannot write other values then the ones displayed, we should not show the regex related operators (` =~`, `!~` ) in the dropdown.
Relates to [db-o11y issue](https://github.com/grafana/grafana-dbo11y-app/issues/438)
=> feat: when allowCustomValue is false, do not show the regex operators

packages/scenes/src/index.ts, packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Assume the API endpoint that is called by `getTagKeysProvider` returns metadata needed for an ad-hoc filter value, that is not the key or key label. Currently, when defining `getTagKeysProvider` in an adHocVariable, we are only able to update the `key` or `keyLabel` props of the _wip ad-hoc filter. This means that we are forced to call the same API again in the `getTagValuesProvider` that we called in `getTagKeysProvider` to re-fetch the metadata associated with the selected key, or we must save the results of the API call made in `getTagKeysProvider` outside of the ad-hoc variable state.
In Explore Logs, we call the `detected_fields` api endpoint to get keys for Fields variables. This returns the desired parser to use when building Loki queries, but isn't part of the actual value that is …
=> AdHocFilters: allow setting filter meta in getTagKeysProvider

packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
This is just a test, want to see if there are other ways to fix the double queries this causes in main with repeated panels 
<details>
<summary>📦 Published PR as canary version: <code>5.39.0--canary.1030.12926943216.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.39.0--canary.1030.12926943216.0
npm install @grafana/scenes@5.39.0--canary.1030.12926943216.0
yarn add @grafana/scenes-react@5.39.0--canary.1030.12926943216.0
yarn add @grafana/scenes@5.39.0--canary.1030.12926943216.0
```
</details>
=> SceneVariableSet: Allow propagation of variable changes through local variable

packages/scenes/src/services/utils.ts, packages/scenes/src/variables/variants/CustomVariable.tsx
Attempts to fix https://github.com/grafana/scenes/issues/1027, not sure if it's the way to go or if it doesn't break other stuff that I might have missed. 
It seems that it only affects CustomVariables so we could isolate it there and turn on the `skipNextValidation` flag if there are no options and we have a value in the url.
=> Fix issue with custom variables losing url value when there are no options

CHANGELOG.md, packages/scenes-app/src/demos/cssGridLayoutDemo.tsx, packages/scenes/src/components/layout/LazyLoader.tsx
The LazyLoader hides empty panels with the CSS `:empty` pseudo class. That does work in Chrome, but Firefox seems to have some issues with it. To test this, I changed the CSS Grid Layout demo, to hide panels after a timeout. The result in Firefox looks like this:
https://github.com/user-attachments/assets/6e573e91-16bf-49d2-a5ec-c4aa33ff1919
The fix involves bypassing the conditional CSS classes. However, since the LazyLoader will be empty from the beginning and thus would be hidden immediately, we need to add an element to it while it has not been loaded. 
This seems to fix the bug:
https://github.com/user-attachments/assets/ebc1aa6a-1ae2-43ca-a826-5d0bf413467a
<details>
<summary>📦 Published PR as canary version: <code>5.41.1--canary.1039.13051061012.0</code></summary>
<br />
:sparkles: …
=> LazyLoader: Prevent empty panels from not being hidden

packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
:wave:  have a need to select default variable option that isn't necessarily the first one. Refactored a little bit to expose `getDefaultSingleState` method for picking the default option so it can be easily overridden, in the same way as `getDefaultMultiState`.
=> MultiValueVariable: Add `getDefaultSingleState` method

packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts
When gathering queries for variables, the query runners can also contain queries from other datasources (i.e. Expressions). These should not be retrieved as they lead to errors (i.e. queries specific to the Expressions datasource does not contain the `expr` property but `expression`).
Hence we need to check the queries' datasource as well. If the `datasource` or `datasource.uid` properties are missing, they are inferred from the query runner. If they are present, we check the UID to see if it matches.
Fixes https://github.com/grafana/scenes/issues/1043
<details>
<summary>📦 Published PR as canary version: <code>5.41.2--canary.1044.13114619048.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@5.41.2--canary.1044.13114619048.0
npm …
```
=> Variables: Prevent queries from runners which are not specific to the query runner datasource

packages/scenes-app/src/demos/variables.tsx, packages/scenes/src/utils/ControlsLabel.tsx, packages/scenes/src/variables/components/VariableValueSelectors.tsx
The new Grafanacon themes have higher borderRadius which make the variable controls look a bit bad 
Before: 
After:
=> Themes: Fixes variable labels to support border radius

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx
Fix needed after https://github.com/grafana/grafana/pull/99300/ (rows refactor) 
The `getLegacyPanelId` method was returning the id for the first part of the key in a clone chain.
This requires a way better fix as it was already clunky from the beginning (cloned panels are having keys like `panel-X-clone-ABC` where `ABC` is now the clone index while previously it was the variable value).
For the time being this is a hotfix to solve any active/potential incidents.
<details>
<summary>📦 Published PR as canary version: <code>6.0.2--canary.1053.13305029685.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.0.2--canary.1053.13305029685.0
npm install @grafana/scenes@6.0.2--canary.1053.13305029685.0
yarn add …
```
=> Fix the `getLegacyPanelId` method in `VizPanel`

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Fixes an issue in dashboards where adhocs do not show the regex operators even though they should appear since the variable settings UI page shows `Allow custom values` true, by default. This only happens when the flag is set by default and not explicitly in the model.
To maintain backwards comp, I added the `allowCustomValues` flag and set it to true by default (as custom values worked by default before this flag), but not in the model, so that it wouldn't change the dashboard model.
If I were to have added the flag in the constructor with a default value when undefined this issue wouldn't have happened, but then all dashboards would have their models changed and a new line for allowing custom values would be serialized in adhoc vars in already saved dashboards.
=> Fix issue were operators do not appear properly in adhoc vars

packages/scenes/src/components/SceneApp/SceneApp.test.tsx, packages/scenes/src/components/SceneApp/SceneAppPage.tsx
:wave: 
Upgrading App O11y to scenes v6, found it's possible to get into infinite loop when a `SceneAppPage` specifies it's fallback page as itself (see test).
The use case is that we want `SceneApp` to render initialization page regardless of route to do some initial loading of metadata. Did not find a better way to do `any route` than to have a page fallback to itself, let me know if I'm missing something :bow: 
The cause of infinite loop was fallback `Route` using `Component` insted of `element`, which causes fallback page to re-mount on every render. And remounting was causing it to update `initializedScene` state prop of parent, causing further re-renders.
=> Fallback page: fix infinite loop

packages/scenes/src/components/layout/grid/SceneGridLayout.tsx, packages/scenes/src/components/layout/grid/types.ts, packages/scenes/src/index.ts
Allow to hook into `onDragStart` event emitted by `PanelChrome` when dragging started.
Useful for drag'n'drop between layouts.
<details>
<summary>📦 Published PR as canary version: <code>6.1.1--canary.1059.13459243901.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.1.1--canary.1059.13459243901.0
npm install @grafana/scenes@6.1.1--canary.1059.13459243901.0
yarn add @grafana/scenes-react@6.1.1--canary.1059.13459243901.0
yarn add @grafana/scenes@6.1.1--canary.1059.13459243901.0
```
</details>
=> SceneGridLayout: Allow to hook into `onDragStart` event

packages/scenes/src/behaviors/SceneQueryController.ts, packages/scenes/src/behaviors/types.ts, packages/scenes/src/components/SceneRefreshPicker.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx
It turns out when the profiling measurements are reported the name is missing. I suspect this is because of some optimization when building the prod artifacts is removing `constructor.name`.
We can instead set the profiling names explicitly to make sure they are submitted.
=> Profiling: explicitly set profiling names

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx
We use tests a lot that verify scene object instance is what we expect, when these tests fail jest usually prints this 
```
Test suite failed to run
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'PanelTimeRange'
|     property '_variableDependency' -> object with constructor 'VariableDependencyConfig'
--- property '_sceneObject' closes the circle
at stringify (<anonymous>)
at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)
```
This PR fixes this to implement a custom toJSON function  
<details>
<summary>📦 Published PR as canary version: <code>6.2.0--canary.1070.13674378560.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.2.0--canary.1070.13674378560.0
npm …
```
=> SceneObjectBase: Fixes crash TypeError circular reference when stringifying scene object

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts, packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts, packages/scenes/src/variables/components/getOptionSearcher.ts, packages/scenes/src/variables/filter.test.ts, packages/scenes/src/variables/filter.ts, packages/scenes/src/variables/utils.test.ts, packages/scenes/src/variables/utils.ts
The recent improvement to filtering were only applied to the custom logic for the new ad hoc combobox so the issues we were solving did not apply to Select and Group By.
Therefore unifying the filtering logic and using the latest filtering implementation from the new Combobox component [link](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Combobox/filter.ts)
Note: new implementation simplifies symbol searching therefore combining the options searching for ad hoc filters into one
fixes https://github.com/grafana/grafana/issues/90459
<details>
<summary>📦 Published PR as canary version: <code>6.1.5--canary.1071.13674684765.0</code></summary>
<br />
```bash
npm install …
```
=> Variables: Unify options filtering to use most up to date implementation

packages/scenes/src/components/VizPanel/VizPanelExploreButton.tsx, packages/scenes/src/utils/explore.test.ts, packages/scenes/src/utils/explore.ts
In a Time Series panel using VizPanel from Grafana Scenes, I encountered an issue when using a mixed datasource setup with both Prometheus and Loki:
- The panel itself correctly displays data from both datasources.
- However, **clicking the Explore button redirects the user to Explore mode, but only Loki queries appear, while the Prometheus queries are missing**.
This happens because `getExploreURL` was not preserving the original datasource assignments from the panel when constructing the Explore URL. Instead, it was defaulting to the last interpolated query’s datasource, causing some queries to be omitted in the Explore view.
**Solution**
- If multiple unique datasource UIDs exist, the `getExploreURL` function now marks the Explore request as` "-- Mixed --"` instead of defaulting to …
=> fix: explore button to preserve datasource selection in mixed datasource panels

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.test.ts, packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.ts
This PR moves scope to adhoc conversion code from https://github.com/grafana/grafana/pull/101217 after the scopes lifting work and removal of [facades](https://github.com/grafana/grafana/pull/97176/files#diff-ff0ca5646e987fbf2d56d6c59e7fc2edbe2deba4ae94413b64a35511d39ff3a5).
<details>
<summary>📦 Published PR as canary version: <code>6.3.2--canary.1073.13788678829.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.3.2--canary.1073.13788678829.0
npm install @grafana/scenes@6.3.2--canary.1073.13788678829.0
yarn add @grafana/scenes-react@6.3.2--canary.1073.13788678829.0
yarn add @grafana/scenes@6.3.2--canary.1073.13788678829.0
```
</details>
=> AdhocVariable: Inject scopes in baseFilters

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
When removing scopes from the scopes selector, there was a bug where the adhoc filter would not clean up and clear the scope injected filters.
This fix cleans the adhoc filter from the scopes injected filters when the scopes are removed entirely from a dashboard.
<details>
<summary>📦 Published PR as canary version: <code>6.5.1--canary.1078.13965220580.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.5.1--canary.1078.13965220580.0
npm install @grafana/scenes@6.5.1--canary.1078.13965220580.0
yarn add @grafana/scenes-react@6.5.1--canary.1078.13965220580.0
yarn add @grafana/scenes@6.5.1--canary.1078.13965220580.0
```
</details>
=> AdHocFilters: Fix removing all scopes and cleaning up the adhoc

packages/scenes/package.json, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, scripts/dev.sh, yarn.lock
- updates the linking script to link to all `@grafana` core modules
- this removes the need for [webpack aliasing in core](https://github.com/grafana/grafana/blob/main/scripts/webpack/webpack.dev.js#L55-L58) when linking scenes locally to core
- adds a cleanup function to cleanup the links once the script shuts down
- adds systemjs types to devdeps to resolve the systemjs types used in data and runtime correctly otherwise this repo falls back to declarations in testing-library and gets grumpy 😠 
- see [related PR in core](https://github.com/grafana/grafana/pull/102449)
=> Local dev: link to all @grafana modules in core

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
This PR fixes an issue with scope injected filters where setting a new scope and then trying to edit the scope injected filters associated to the new scopes would not update properly on the first try. 
Before:
https://github.com/user-attachments/assets/1fad8486-4874-45ff-82c8-bd47a2bdbcf4
After:
https://github.com/user-attachments/assets/7780511b-6fed-4f56-8d90-f0eb21b4f552
Other things that I've tested:
- Reloading dashboard or copying url to a different browser tab maintains scope filters and/or edited scope filters
- Switching between dashboards from the scopes dashboard selector maintains scope filters and/or edited scope filters
- Removing scopes and re-adding them cleans filters and re-adds scope filters.
=> AdHocFilters: Fix issue where scope injected filter would not update properly

packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts, packages/scenes/src/variables/variants/MultiValueVariable.test.ts
Builds on top of https://github.com/grafana/scenes/pull/882.
The `GroupBy` variable extends `MultiValueVariable` but uses a custom `UrlSyncHandler` so we need to also implement browser history related methods in this custom handler so `changeValueTo` calls and sets the value properly. 
<details>
<summary>📦 Published PR as canary version: <code>6.6.3--canary.1087.14261442491.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.6.3--canary.1087.14261442491.0
npm install @grafana/scenes@6.6.3--canary.1087.14261442491.0
yarn add @grafana/scenes-react@6.6.3--canary.1087.14261442491.0
yarn add @grafana/scenes@6.6.3--canary.1087.14261442491.0
```
</details>
=> GroupByVariable: Add browser history action support for GroupBy var

packages/scenes/src/utils/ControlsLabel.tsx
https://github.com/grafana/grafana/pull/103451 needs these props in order not require a wrapping div (which cause issues with e2e tests) 
<details>
<summary>📦 Published PR as canary version: <code>6.7.0--canary.1091.14350229100.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.7.0--canary.1091.14350229100.0
npm install @grafana/scenes@6.7.0--canary.1091.14350229100.0
yarn add @grafana/scenes-react@6.7.0--canary.1091.14350229100.0
yarn add @grafana/scenes@6.7.0--canary.1091.14350229100.0
```
</details>
=> VariableControl: Add props needed in core dashboards

packages/scenes/src/index.ts, packages/scenes/src/variables/components/VariableValueSelect.test.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/variants/CustomVariable.tsx, packages/scenes/src/variables/variants/DataSourceVariable.tsx, packages/scenes/src/variables/variants/TestVariable.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
* In order to switch betwen single and multi select while visible (mounted) we need to subscribe to state on a higher level than we did
* Renamed renderSelectForVariable MultiOrSingleValueSelect and made it a proper react component, it now subscribe to state. Removed state subscription from the lower level components, they get the state instead. 
* This is for the live editing of variable options in the edit pane
=> Variables: Switch between multi and single select if state changes

packages/scenes/src/index.ts
Missed that this was exported in https://github.com/grafana/scenes/pull/1096 
RenderSelectForVariable was renamed to MultiOrSingleValueSelect and is now React component.
=> Variables: Rename renderSelectForVariable to MultiOrSingleValueSelect   

packages/scenes/src/components/VizPanel/VizPanel.test.tsx, packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Move showMenuAlways VizPanelRenderer.tsx prop out of collapse conditional. In Logs Drilldown we have a situation where we'd like to `showMenuAlways` but do not use collapsible. [upgrade to Scenes6](https://github.com/grafana/logs-drilldown/pull/1019/files#diff-0c9eb85b8eb906fbac0d474a7c68685514172ee72d0597664fa8618f27826087)
I'm not totally familiar with the change to making `showMenuAlways` conditional on the `collapsible` property [PR](https://github.com/grafana/scenes/pull/1040/files#diff-b4e762e26aeb297a8f36c1ada3213ecd5a9bcd972799a753018dccf96fc75a30R195
).🤔 @tskarhed let me know what you think.
=> fix: (VizPanelRenderer) - move showMenuAlways prop to the top level

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/variables/TestScene.ts, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
The problem is that we notified scene objects in a recursive way, meaning whatever first child we start with we notify it's children, and it's children. 
This means that if we have something higher up in the scene tree that removes scene objects when a variable value change this reaction will not trigger until after the nested children have received the variable value change notification. 
Example
* Row 
* Row repeat behavior    
* GridItem
* VizPanel
*  VizPanelQueryRunner 
When the variable value changed we want the row repeat behavior to get notified before GridItem children. This code change makes sure we go down each level and notify in depth order. 
<details>
<summary>📦 Published PR as canary version: <code>6.9.1--canary.1104.14589006500.0</code></summary>
<br />
:sparkles: Test out …
=> Variables: Notify scene objects in depth order

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
This PR changes the look of match-all filters, which are basically cleared filters that still show in the list of filters.
Also turns the info icon that shows information about injected filters into a normal icon without a hover effect.
https://github.com/user-attachments/assets/c3b14686-68e5-436d-873f-47978bac6a46
=> AdHocFIlters: New designs for match-all filter

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
Through this PR, origin filters such as scope or dashboard originated filters will now allow a user to remove all mulit-values on edit. On removal of all values, the edited filter will become a match-all filter basically cancelling it alltogether.
https://github.com/user-attachments/assets/5de0cf4c-0fd7-4ede-961b-5a454c23fbf2
NOTE: Builds on top of this [PR](https://github.com/grafana/scenes/pull/1095)
=> AdHocFilters: Removing multi-values from origin filters turns them to match-all filters

packages/scenes/src/core/SceneObjectBase.test.ts, packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/variables/TestScene.ts, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/sets/SceneVariableSet.ts
Reverts grafana/scenes#1104
I just had realisation that we don't need this change, going to test https://github.com/grafana/grafana/pull/104312 without it
=> Revert "Variables: Notify scene objects in depth order"

packages/scenes-app/src/demos/adhocFiltersDemo.tsx, packages/scenes/src/index.ts, packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts, packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.test.ts, packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.ts
This PR adds support for dashboard level filters, which are filters set in the schema, under the adhoc variables `baseFilter` property. This new type of baseFilter will need a specific `origin: 'dashboards'` property to indicate it is a dashboard level filter.
Dashboard level filters will stick on your dashboard, they can be cleared (become a regex match-all filter) but not removed, their value can be edited and afterwards restored. Going to another dashboard with this filter will maintain it if there is another dashboard level filter with the same key or remove it, unless the filter is edited. If it is edited it will maintain it across dashboards as a normal filter.
This PR also simplifies the code a bit by not carrying original values (the values that an edited filter restores to), but …
=> AdHocFilters: Dashboard level filters

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx
Fixes incorrect percent of interval calculation.
`intervalMs / percent` works for the default ` { percent: 10 }` `refreshOnActivate` value but not any other value.
Found the problem by setting it to 1% which should have invalidated my 5m time range in 2.4s but it didn't.
=> SceneTimeRange: Fix calculatePercentOfInterval

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
Adds better tooltips for the new injected filters.
<details>
<summary>📦 Published PR as canary version: <code>6.10.4--canary.1118.14886789462.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.10.4--canary.1118.14886789462.0
npm install @grafana/scenes@6.10.4--canary.1118.14886789462.0
yarn add @grafana/scenes-react@6.10.4--canary.1118.14886789462.0
yarn add @grafana/scenes@6.10.4--canary.1118.14886789462.0
```
</details>
=> AdHocVariable: Add more suggestive injected filters tooltips

packages/scenes/src/components/VizPanel/VizPanel.tsx
<details>
<summary>📦 Published PR as canary version: <code>6.11.1--canary.1127.15046943713.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.11.1--canary.1127.15046943713.0
npm install @grafana/scenes@6.11.1--canary.1127.15046943713.0
yarn add @grafana/scenes-react@6.11.1--canary.1127.15046943713.0
yarn add @grafana/scenes@6.11.1--canary.1127.15046943713.0
```
</details>
=> VizPanel: Allow passing partial state when cloning

packages/scenes/src/variables/variants/ScopesVariable.test.tsx, packages/scenes/src/variables/variants/ScopesVariable.tsx
For some reason I think ScopesService in core is changing value state even when scope names have not changed. I find the core ScopesService and ScopesSelectorService a bit hard to follow so opting to add this change to be on the safe side on the scenes part at least. 
<details>
<summary>📦 Published PR as canary version: <code>6.14.0--canary.1130.15248914373.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.14.0--canary.1130.15248914373.0
npm install @grafana/scenes@6.14.0--canary.1130.15248914373.0
yarn add @grafana/scenes-react@6.14.0--canary.1130.15248914373.0
yarn add @grafana/scenes@6.14.0--canary.1130.15248914373.0
```
</details>
=> ScopesVariable: Only emit value changed when value has changed

packages/scenes/src/components/layout/SceneFlexLayout.tsx
`SceneFlexItem` accepts `wrap` property but does not do anything with it. However I have a use case for it when rendering `VariableValueSelectors()` inside a `SceneFlexItem` :)
=> SceneFlexItem: respect `wrap` property

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts, packages/scenes/src/variables/utils.ts
Escapes hash chars in AdHoc variable values.
Fixes https://github.com/grafana/scenes/issues/1138
=> AdHocFiltersVariableUrlSyncHandler: fix url state containing `#` char

packages/scenes/src/variables/variants/ScopesVariable.test.tsx, packages/scenes/src/variables/variants/ScopesVariable.tsx
The reload behavior is waiting for scopes (as it always set to loading initially until state from context is read) 
But we need to emit the value changed event even when scopes is empty for this scenario to also always prompt a reload  
<details>
<summary>📦 Published PR as canary version: <code>6.17.0--canary.1136.15305220090.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.17.0--canary.1136.15305220090.0
npm install @grafana/scenes@6.17.0--canary.1136.15305220090.0
yarn add @grafana/scenes-react@6.17.0--canary.1136.15305220090.0
yarn add @grafana/scenes@6.17.0--canary.1136.15305220090.0
```
</details>
=> ScopesVariable: Emit value changed when there no scopes selected

packages/scenes/src/variables/groupby/GroupByVariable.test.tsx, packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts
Fixes an edge case where moving from a dashboard with an unmodified default value will carry that value to another dashboard that does not have default values. This is undesired, when moving with an unmodified default value, we do not want to carry the filter to another dashboard within the scope dashboard selector.
=> GroupBy: Fix edge cases on dashboard default values

packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts, packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
This exposes `scopes` in the DS query method when there is an annotation query
Related to https://github.com/grafana/hyperion-planning/issues/246
<details>
<summary>📦 Published PR as canary version: <code>6.18.2--canary.1144.15561582453.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.18.2--canary.1144.15561582453.0
npm install @grafana/scenes@6.18.2--canary.1144.15561582453.0
yarn add @grafana/scenes-react@6.18.2--canary.1144.15561582453.0
yarn add @grafana/scenes@6.18.2--canary.1144.15561582453.0
```
</details>
=> Scopes: Add annotation query support

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts, packages/scenes/src/variables/utils.ts
Origin filters have been moved to a separate property within the adhoc variable - `originFilters`. 
This change and other refactors in this PR are aiming to simplify the logic related to origin filters.
<details>
<summary>📦 Published PR as canary version: <code>6.19.0--canary.1132.15579595251.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.19.0--canary.1132.15579595251.0
npm install @grafana/scenes@6.19.0--canary.1132.15579595251.0
yarn add @grafana/scenes-react@6.19.0--canary.1132.15579595251.0
yarn add @grafana/scenes@6.19.0--canary.1132.15579595251.0
```
</details>
=> AdHocVariable: Refactor origin filters

packages/scenes/package.json, yarn.lock
Scenes is currently targetting `@grafana/i18n` `>=12.1.0` for peerDependencies but any package manager that automatically installs peer deps will now fail on install as 12.1.0 doesn't exist in the registry. This PR sets it to `*` so installs complete whilst we wait on the 12.1.0 release.
=> i18n: fixes peer dependencies

packages/scenes/src/querying/SceneQueryRunner.test.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap, packages/scenes/src/variables/sets/SceneVariableSet.test.tsx, packages/scenes/src/variables/types.ts
This is related to row repeats: https://github.com/grafana/grafana/pull/104312 
The issue with the current way scene query runner records variable values on deactive, is that it can then record a value that was either just set or removed. So it will record a value that has not actually been used in a query. 
By changing to record values on every query we can be sure that when the scene query runner re-activates that it will compare against the variables that it used when it last issued a query. 
This scenario is mainly relevant for row / tab repeats where the first row get's a local variable value or it get's removed, this should trigger a new query on the first row but because scene query runner records the value on deactivate it records the new value and when it- reactivates it thinks …
=> SceneQueryRunner: Detect local variable change

packages/scenes/src/core/SceneObjectBase.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx, packages/scenes/src/core/sceneGraph/sceneGraph.ts, packages/scenes/src/core/types.ts
Noticed that findObject would always return the last match (if multiple objects match predicate), this fixes it by adding support for early exit from forEachChild (by returning false, same way lodash forEach works )
<details>
<summary>📦 Published PR as canary version: <code>6.23.0--canary.1165.15877190588.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.23.0--canary.1165.15877190588.0
npm install @grafana/scenes@6.23.0--canary.1165.15877190588.0
yarn add @grafana/scenes-react@6.23.0--canary.1165.15877190588.0
yarn add @grafana/scenes@6.23.0--canary.1165.15877190588.0
```
</details>
=> sceneGraph: findObject should return first match

packages/scenes/jest.config.ts, packages/scenes/src/components/SceneTimeRangeCompare.test.tsx, packages/scenes/src/components/SceneTimeRangeCompare.tsx
Related to: https://github.com/grafana/grafana/pull/104672
For some use cases of `SceneTimeRangeCompare`, requiring the checkbox to toggle the comparison selection is redundant. For example, if time comparison is enabled in panel options (like in the PR above), it becomes an additional step to enable time comparison selection, especially considering that `NO_PERIOD_VALUE` is always included in the select options and can be used to turn comparison off.
In this PR, we add optional `hideCheckbox` option to `SceneTimeRangeCompare`.
Before (now the default behavior, hideCheckbox undefined):
After (hideCheckbox = true):
=> SceneTimeRangeCompare: Add option to hide checkbox

packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.test.ts, packages/scenes/src/variables/variants/MultiValueVariable.ts
Fixes https://github.com/grafana/grafana/issues/96336 
Fixes https://github.com/grafana/support-escalations/issues/17059 
Got a bit interested in why scenes changed this behavior, and it's because in scenes the fieldPath is interpolated by the variables (instead of in a later state), this was a good change as it enables new dynamic features but because MultiValueVariable does not support object values it did not implement any support for fieldPath. 
When value is an array I think we can preserve this behavior. It should be easy to support long-term. There is a downside in that, ideally, we should have different syntax for property vs array index lookup. But think this should be fine.
=> MultiValueVariable: Support field path array index

packages/scenes/src/variables/variants/query/QueryVariable.test.tsx, packages/scenes/src/variables/variants/query/QueryVariable.tsx
One day hackathon effort :) 
Adds ability to add addition "static" options to query variable options, defined in the same way as custom variable options.
They are prepended by default, but can be optionally appened or sorted in per defined sort order.
Use case is to be able to add options like `{ label: "not set", value: "" }` or `{ label: "any production cluster", value: ".*-prod-.*"}`
This is needed for https://github.com/grafana/grafana/issues/102229, with Grafana PR to follow.
=> QueryVariable: Add ability to provide custom static options

packages/scenes/src/core/SceneTimeRange.test.tsx, packages/scenes/src/core/SceneTimeRange.tsx
This PR fixes a bug where user couldn't select default timezone. See the issue below for additional info and steps to reproduce. 
Fixes: https://github.com/grafana/grafana/issues/107734
This notion of default time zone is a bit confusing because [here](https://github.com/grafana/grafana/blob/e14c17ef69ca86bf5397a6c0d0d2459316f1cf0a/packages/grafana-data/src/datetime/timezones.ts#L8-#L12) we have default as empty string - and in the old arch when we have this empty string we resolve it to default time zone from user profile using `config.bootData.user.timezone` [here](https://github.com/grafana/grafana/blob/20c700dd52373c7b4e6f9560d0c2e35985308cfb/public/app/features/profile/state/reducers.ts#L113-L115).
But in https://github.com/grafana/scenes/pull/1109, we've introduced defaulting to …
=> Time zone selection: When selecting Default in time zone picker, interpolate timezone from user profile setting

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Set the key in the originalValues map to also contain the origin for cases where we have 2 filters with the same key originating from 2 different origins.
=> AdHocFilters: Refactor original values to take origin in key as well

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
- updates the `z-index` of the `AdHocFiltersCombobox`
- this ensures it can correctly render within `Drawer`/`Modal` components which currently have [lower z-indices](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/themes/zIndex.ts#L7)
<details>
<summary>📦 Published PR as canary version: <code>6.24.1--canary.1166.15878540264.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.24.1--canary.1166.15878540264.0
npm install @grafana/scenes@6.24.1--canary.1166.15878540264.0
yarn add @grafana/scenes-react@6.24.1--canary.1166.15878540264.0
yarn add @grafana/scenes@6.24.1--canary.1166.15878540264.0
```
</details>
=> AdHocFiltersCombobox: Update z-index

packages/scenes/src/variables/variants/CustomVariable.test.ts, packages/scenes/src/variables/variants/CustomVariable.tsx
It was pointed out (as a bug) that custom variable does not properly recognize options separated with new line, like so:
```
label-1 : value-1,
label-2 : value-2,
label-3 : value-3,
```
Seems easy enough to fix
=> Custom variable: support newline separated options

packages/scenes/src/behaviors/SceneRenderProfiler.ts, packages/scenes/src/behaviors/types.ts, packages/scenes/src/components/SceneRefreshPicker.tsx, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/core/SceneTimeRange.tsx, packages/scenes/src/utils/getDataSource.ts, packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx, packages/scenes/src/variables/components/VariableValueSelect.tsx, packages/scenes/src/variables/variants/MultiValueVariable.ts, packages/scenes/src/variables/variants/ScopesVariable.tsx
This PR improves the `SceneRenderProfiler` by adding new interactions tracking and better profile management.
- Improved `startProfile` method to handle overlapping profiles by continuing existing profiles with crumbs or properly stopping tail recording phases
- Added interaction type constants for consistent profiling:
- `REFRESH_INTERACTION` for manual and auto refresh actions
- `TIME_RANGE_CHANGE_INTERACTION` for time range modifications
- `FILTER_*_INTERACTION` for ad-hoc filter operations (add/remove/change/restore)
- `VARIABLE_VALUE_CHANGED_INTERACTION` for variable value changes
- `SCOPES_CHANGED_INTERACTION` for scopes modifications
- Added profiling to previously untracked interactions: ad-hoc filter manipulations, variable value selections, and scopes changes
- Enhanced plugin …
=> Enhance `SceneRenderProfiler` with additional interaction tracking

packages/scenes/src/behaviors/SceneQueryController.ts, packages/scenes/src/behaviors/SceneRenderProfiler.ts, packages/scenes/src/components/VizPanel/VizPanel.tsx, packages/scenes/src/index.ts, packages/scenes/src/querying/SceneQueryRunner.ts, packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx, packages/scenes/src/utils/getDataSource.ts, packages/scenes/src/variables/variants/query/QueryVariable.tsx
This refactoring improves the modularity of the `SceneRenderProfiler` by making it optional and supporting dependency injection patterns.
- **SceneQueryController**: Accept optional `profiler` parameter in constructor instead of auto-instantiating
- **SceneRenderProfiler**: Make `queryController` optional and add `setQueryController()` method
- **API**: Export `SceneRenderProfiler` class for external use (see https://github.com/grafana/grafana/pull/108658)
- **Cleanup**: Simplify `startProfile` logic and improve logging consistency
No breaking changes to existing API.
<details>
<summary>📦 Published PR as canary version: <code>6.28.5--canary.1198.16615923333.0</code></summary>
<br />
```bash
npm install …
```
=> Make `SceneRenderProfiler` optional and injectable

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
https://github.com/user-attachments/assets/80acf8e8-e8c4-4416-8f81-e3594c725193
Currently, single value origin filters cannot be turned into match-all filters by removing their value, this PR addresses this issue.
=> AdHocFilters: Removing value from an origin filter will turn it into a matchAll filter

packages/scenes/src/behaviors/SceneRenderProfiler.ts
When users switch browser tabs during performance profiling, `requestAnimationFrame` callbacks get paused and can resume later when tab is activated back. This results in massive frame times (i.e. hours instead of milliseconds) being recorded and meaningless profiling data.
**Primary Protection: Page Visibility API**
- Immediately cancels profiling when tab becomes inactive
- Uses `document.visibilitychange` event for instant response
**Fallback Protection: Frame Length Detection**
- Detects tab inactivity via frame duration > 1000ms
- Serves as backup if visibility events are missed
```typescript
// Primary: Page Visibility API
document.addEventListener('visibilitychange', () => {
if (document.hidden && this.#profileInProgress) {
this.cancelProfile();
}
});
// Fallback: Frame length …
```
=> SceneRenderProfiler: Handle tab inactivity 

packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.test.ts, packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.ts
https://github.com/user-attachments/assets/05ab23d8-708e-4eb9-9bcb-15935d7b0136
Allow scope injected filters that have regex operators to merge their values by using the regex OR (`|`) operator.
<details>
<summary>📦 Published PR as canary version: <code>6.29.2--canary.1202.16723575264.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.29.2--canary.1202.16723575264.0
npm install @grafana/scenes@6.29.2--canary.1202.16723575264.0
yarn add @grafana/scenes-react@6.29.2--canary.1202.16723575264.0
yarn add @grafana/scenes@6.29.2--canary.1202.16723575264.0
```
</details>
=> AdHocFilters: Scope injected filter values with regex operators also get merged

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Adds new operators to the AdHocFiltersVariable.
This is the result of an internal Slack chat where it was discussed that having `>=` and `<=` would be useful for example when searching for HTTP status codes.
=> Add new operators to AdHocFiltersVariable

packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Adds the `hidden` filter functionality to the new adhoc combobox layout as well.
<details>
<summary>📦 Published PR as canary version: <code>6.29.8--canary.1216.17039188390.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.29.8--canary.1216.17039188390.0
npm install @grafana/scenes@6.29.8--canary.1216.17039188390.0
yarn add @grafana/scenes-react@6.29.8--canary.1216.17039188390.0
yarn add @grafana/scenes@6.29.8--canary.1216.17039188390.0
```
</details>
=> AdHocFilters: Fix hidden filters in new combobox layout

.gitignore, packages/scenes/src/behaviors/SceneRenderProfiler.ts
Rapid user interactions mixed performance data from multiple actions into a single profile.
When a new profile is requested while trailing frames are being recorded, cancel the current profile and start fresh. Each interaction now gets its own isolated measurement.
1. Open a dashboard with random walk panel with no delay and set auto refresh to 5s
2. Slow down `/api/annotations` requests to for example 4s (using Requestly for example).
3. Observe console with `localStorage.setItem('grafana.debug.scenes', 'true')`. While the tail is being recorded (2s), and the refresh happens, the profile should be cancelled and a new one should be started. _Before this change, refresh event would be added as a crumb of the initial interaction profile, and the profile would never end._
4. Slow down …
=> SceneRenderProfiler: Handle overlapping profiles by cancelling previous profile

packages/scenes/src/variables/types.ts
**Related Grafana PR:** https://github.com/grafana/grafana/pull/109225
Extended the state of the scene variables to have a new option called `showInControlsMenu`. This option can be used to render the variable under a dropdown menu instead of the default dashboard controls (currently only supported by Grafana dashboards). 
<details>
<summary>📦 Published PR as canary version: <code>6.31.0--canary.1208.17233161250.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.31.0--canary.1208.17233161250.0
npm install @grafana/scenes@6.31.0--canary.1208.17233161250.0
yarn add @grafana/scenes-react@6.31.0--canary.1208.17233161250.0
yarn add @grafana/scenes@6.31.0--canary.1208.17233161250.0
```
</details>
=> Feat: Add `showInControlsMenu` to `SceneVariableState`

packages/scenes/src/components/layout/grid/SceneGridRow.tsx, packages/scenes/src/components/layout/grid/types.ts
adjusting row panel count to account for the new `repeatedPanels` property
<details>
<summary>📦 Published PR as canary version: <code>6.31.1--canary.1227.17262127065.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.31.1--canary.1227.17262127065.0
npm install @grafana/scenes@6.31.1--canary.1227.17262127065.0
yarn add @grafana/scenes-react@6.31.1--canary.1227.17262127065.0
yarn add @grafana/scenes@6.31.1--canary.1227.17262127065.0
```
</details>
=> SceneGridRow: Adjust row panel count to account for repeats

packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx, packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
https://github.com/user-attachments/assets/0a09143a-67fa-4629-a15c-a22125c4794f
*Note on video: the applicability API is not working so all filter pills are valid here*
Modifications have been brought to injected filters.
Before this PR, when switching dashboards, if there were multiple filters of different types with the same key, e.g.: a dashboard default filter and a normal user added filter, then these two filters would be merged into one -- basically the user value would be used to edit the default filter.
The same would not happen to scopes which means we have an inconsistent experience.
Due to rising complexities around merging multiple filter types together when they have the same key, a decision was made to disallow merging of different filter types into one everywhere, which is …
=> AdHocFilters: Remove merging of different filter type with same keys

packages/scenes/src/variables/interpolation/formatRegistry.test.ts
A few spaces snuck in and is causing linting errors in CI.
=> Fix pettier issue

packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
This adds functionality to handle item positions when other items in the layout grows or shrinks. It turns out relying completely on react grid for this functionality did not work out when dealing with repeating panel inside rows.
https://github.com/grafana/grafana/issues/110273
<details>
<summary>📦 Published PR as canary version: <code>6.34.1--canary.1243.17576735400.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.34.1--canary.1243.17576735400.0
npm install @grafana/scenes@6.34.1--canary.1243.17576735400.0
yarn add @grafana/scenes-react@6.34.1--canary.1243.17576735400.0
yarn add @grafana/scenes@6.34.1--canary.1243.17576735400.0
```
</details>
=> SceneGridLayout: Adjust item y position for all children after a breakpoint

packages/scenes/src/components/SceneTimePicker.tsx, packages/scenes/src/locales/en-US/grafana-scenes.json
This PR extends the TimePicker and passes the move duration tooltip, so the component shows the panning interval.
<details>
<summary>📦 Published PR as canary version: <code>6.36.0--canary.1248.17797615374.0</code></summary>
<br />
```bash
npm install @grafana/scenes-react@6.36.0--canary.1248.17797615374.0
npm install @grafana/scenes@6.36.0--canary.1248.17797615374.0
yarn add @grafana/scenes-react@6.36.0--canary.1248.17797615374.0
yarn add @grafana/scenes@6.36.0--canary.1248.17797615374.0
```
</details>
=> SceneTimePicker: Pass move duration tooltip

.github/workflows/node-ci.yml, .prettierignore, lerna.json, package.json, packages/scenes-app/.config/webpack/webpack.config.ts, yarn.lock
To be able to enable OIDC trusted publishing for NPM packages in this repo we first need to update lerna to v9.
I added a dummy commit to scenes-react (now removed) to check that lerna and auto continue to work fine. We should get a canary release below if that's the case!
<details>
<summary>📦 Published PR as canary version: <code>6.39.2--canary.1259.18162516235.0</code></summary>
<br />
```bash
npm install @grafana/scenes@6.39.2--canary.1259.18162516235.0
npm install @grafana/scenes-react@6.39.2--canary.1259.18162516235.0
yarn add @grafana/scenes@6.39.2--canary.1259.18162516235.0
yarn add @grafana/scenes-react@6.39.2--canary.1259.18162516235.0
```
</details>
=> Chore: bump lerna to v9
